### ISSUE TITLE
istio bookinfo with auto sidecar injection enabled not working with vcluster istiolate mode

### ISSUE THREAD

**Issue by GOVYANSONG** [loft-sh/vcluster#1015]
### What happened?

I was trying the istio bookinfo sample app within a namespace e.g. bookinfo with istio-injection=enabled inside vcluster. After the app was deployed, no pod was ever created in that namespace. If namespace is created without the label, all is fine.

### What did you expect to happen?

I would expect the bookinfo app to have all pods created and running.

### How can we reproduce it (as minimally and precisely as possible)?

1. create namespace vclab on host cluster
2. create vcluster with following command:
   vcluster create local --distro=k3s --connect=false --namespace vclab -f values.yaml --isolate

values.yaml

multiNamespaceMode:
enabled: false
fallbackHostDns: true
isolation:
enabled: true
resourceQuota:
enabled: false
limitRange:
enabled: false
networkPolicy:
enabled: false
sync:
nodes:
enabled: true
enableScheduler: true
syncAllNodes: true

1. get kubeconfig with command:
   vcluster connect local -n vclab --update-current=false --server=https://192.168.49.2:xyz --service-account admin --cluster-role cluster-admin --insecure
2. create namespace bookinfo inside the vcluster with label istio-injection=enabled
3. deploy istio bookinfo sample app and observe the deployment progress and check pod status

### Anything else we need to know?

My environment is:

ubuntu 20.04 host os
minikube v1.30.1
istio 1.17.2

### Host cluster Kubernetes version

<details>

```
$ kubectl version
# paste output here
```

clientVersion:
buildDate: "2023-04-14T13:21:19Z"
compiler: gc
gitCommit: 4c9411232e10168d7b050c49a1b59f6df9d7ea4b
gitTreeState: clean
gitVersion: v1.27.1
goVersion: go1.20.3
major: "1"
minor: "27"
platform: linux/amd64
kustomizeVersion: v5.0.1

</details>

### Host cluster Kubernetes distribution

<details>

```
minikube v1.30.1
```

</details>

### vlcuster version

<details>

```
$ vcluster --version
# paste output here
```

v0.15.0
</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
# Write here
```

k3s
</details>

### OS and Arch

<details>

```
OS: Linux ubuntu 5.4.0-147-generic #164-Ubuntu SMP Tue Mar 21 14:23:17 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
Arch:
```

</details>

**Comment by matskiv** [comment]
Hello,
thank you for providing the detailed steps for reproducing the issue, that is much appreciated.
Would you be able to provide the Pod status or events that can be observed when the bookinfo app is failing to deploy? That might speed up issue resolution because trying to reproduce would take longer time, and I am still catching up after being away for almost 2 weeks :)

**Comment by GOVYANSONG** [comment]
@matskiv thanks for following up with this issue. I just reproduced the issue and checked the log of the pod of local-0 (vcluster name is local). It contains some warnings: 

I0425 11:46:17.652120       7 event.go:294] "Event occurred" object="bookinfo/productpage-v1-d4f8dfd97" fieldPath="" kind="ReplicaSet" apiVersion="apps/v1" type="Warning" reason="FailedCreate" message="Error creating: pods \"productpage-v1-d4f8dfd97-ts65z\" is forbidden: violates PodSecurity \"baseline:latest\": non-default capabilities (container \"istio-init\" must not include \"NET_ADMIN\", \"NET_RAW\" in securityContext.capabilities.add)"

I will also try to troubleshoot more on my end.

**Comment by GOVYANSONG** [comment]
After updated podsecurityprofile to privileged and re-deployed the sample app, all is good. thanks for the assistance.

**Comment by matskiv** [comment]
No problem. Yeah, this is behaving as designed. Just beware that with privileged PSS you are basically losing isolation.
