### ISSUE TITLE
Support syncing PersistentVolumes to the host cluster

### ISSUE THREAD

**Issue by siredmar** [loft-sh/vcluster#102]
Currently it does not work to create a PersistentVolume within a vcluster.
Allow creating PersistentVolumes within the vcluster and sync them back to the host cluster just like the `sync-node-changes` parameter.

**Comment by FabianKramm** [comment]
@siredmar thanks for creating this issue! As discussed in slack, we could add an option to sync persistent volumes from the vcluster to the host cluster.

**Comment by matskiv** [comment]
This was implemented in #116
