### ISSUE TITLE
OCI support for helm images on init configmap

### ISSUE THREAD

**Issue by dukanto** [loft-sh/vcluster#1034]
### Is your feature request related to a problem?

When deploying a new vcluster, helm charts can be configured in the init configmap in order to install them on cluster initialization.
Currently, there are options for both public and private helm repos.

Since helm 3, charts can also be distributed via OCI registries, however, when trying to pull an image from an OCI registry, it does not work, as it tries to pull it as a regular helm registry, giving the following error:

`init-manifests-controller:  unable to pull chart test-init-chart: error executing helm pull test-init-chart test-init-chart --repo oci://REGISTRY/group/test-init-chart --version v0.6.0 --username USER --password PASS --insecure-skip-tls-verify --kubeconfig /tmp/3506194302 --namespace : Error: looks like "oci://REGISTRY/group/test-init-chart" is not a valid chart repository or cannot be reached: object required`

### Which solution do you suggest?

Implement a way to detect if the registry is OCI and act accordingly when getting the chart

### Which alternative solutions exist?

*No response*

### Additional context

Official helm registry package has support for detecting if a registry is OCI and acts accordingly:
[https://github.com/helm/helm/blob/main/pkg/registry/util.go#L45](https://github.com/helm/helm/blob/main/pkg/registry/util.go#L45)

**Comment by ishankhare07** [comment]
Hi @dukanto , thanks for creating this issue. Going through the helm docs I found that although this is possible in helm 3, its only enabled by default since `v3.8.0` of helm. However this can be enabled by setting the `HELM_EXPERIMENTAL_OCI` env variable in prior version. Can you give that a try maybe?

You can refer the relevant section in the docs here – https://helm.sh/docs/topics/registries/#enabling-oci-support-prior-to-v380

**Comment by dukanto** [comment]
Hi @ishankhare07!
Thank you for your response!

I tried enabled `HELM_EXPERMIENTAL_OCI` in `syncer` container as you mentioned:

```
k exec -it vctest2-vcluster-55dccf5d5d-kw7lp -c syncer -- sh
~ $ env | grep HELM
HELM_EXPERIMENTAL_OCI=true
```

However, when running the pull, I've got the same message:
`info   execute command: helm pull helm-vc-test helm-vc-test --repo oci://REGISTRY/group/helm-vc-test --version v0.6.0 --username USER --password PASS --insecure-skip-tls-verify --kubeconfig /tmp/774795287 --namespace`

Any other ideas are welcome :)

Thanks again for your support

**Comment by dukanto** [comment]
Hi, @ishankhare07
Just double checked, and I'm running `vcluster:0.15.0`

I've made a couple of tests in the syncer container, so I could get a clearer image on what's going on:
```
~ $ helm version
version.BuildInfo{Version:"v3.11.3", GitCommit:"323249351482b3bbfc9f5004f65d400aa70f9ae7", GitTreeState:"clean", GoVersion:"go1.20.3"}
```

--- 
Currently, the command generated by pkg/helm/helm.go **run** is the following:
`helm pull NAME CHART_NAME --repo REPO --version VERSION [--insecure-skip-tls-verify]`
>Note that NAME === CHART_NAME, since CHART_NAME is assigned to Chart.Name on **pullChartArchive**

However, AFAIK, in order to pull from an OCI registry, command should be:
`helm pull REPO/CHART_NAME --version VERSION [--insecure-skip-tls-verify]`


PS: you are completely right about logging in into a private registry, since username and password flags are not recognized so currently I'm using a public repo, since it's located in an private network. However, it would be lovely that the `helm registry login` could be executed.
The only thing to note, is that the flag for insecure login is --insecure:
`helm registry login -u USER -p PASS REPO (w/o the oci:// part) [--insecure]`

**Comment by ishankhare07** [comment]
Thanks @dukanto , I'll review this soon and keep you updated
