### ISSUE TITLE
with syncer.persistentvolumes enabled, PVC in vcluster NS replicates PV to vcluster (but not PVC)

### ISSUE THREAD

**Issue by joaocc** [loft-sh/vcluster#1041]
### What happened?

In EKS with vcluster-eks v0.15.0, creating a PVC in the namespace of the vcluster, with `syncer.persistentvolumes.enabled: true` creates a PV inside vcluster (but not the PV).
This happens with single namespace install.

### What did you expect to happen?

both the PV and the PVC replicated into vcluster (but, not sure where I would expect PVC to appear in vcluster (as it is a namespaced resource)

### How can we reproduce it (as minimally and precisely as possible)?

Didn't test, but should be something like this

* in EKS, install `vclu1` using helm chart v0.15.0 in namespace `vclu1`, using `syncer.persistentvolumes.enabled: true`
* manually create a PVC (pvc1) in `vclu1` namespace, and wait for it to become available, and bound to PV `pv-some-UUID`
* list PVs and PVCs inside `vclu1`:
  * `pv-some-UUID` is shown, and marked as claimed by `pvc1`
  * `pvc1` is not listed as PVC in any na

### Anything else we need to know?

*No response*

### Host cluster Kubernetes version

<details>

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-14T13:14:41Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"26+", GitVersion:"v1.26.2-eks-a59e1f0", GitCommit:"8b68f4b95d7121d039ceebd30870e48acc7772e4", GitTreeState:"clean", BuildDate:"2023-03-09T19:59:45Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Host cluster Kubernetes distribution

<details>

```
EKS 1.26
```

</details>

### vlcuster version

<details>

0\.15.0

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
eks
```

</details>

### OS and Arch

<details>

```
amd64
```

</details>

**Comment by rohantmp** [comment]
Hi, PVC syncing happens only from host->virtual precisely because of the issue you mentioned. We don't know which namespace to sync the pvc to!

You could create the PVC in the vcluster and it would be synced to the host cluster and then you would have it visible in both places

**Comment by joaocc** [comment]
Hi. Not sure I understood (maybe you mistyped the PVC sync direction?). Thx

**Comment by rohantmp** [comment]
> install vclu1 using helm chart v0.15.0 in namespace vclu1


> manually create a PVC (pvc1) in vclu1 namespace

You created the PVC in the host cluster (same namespace as vcluster) and want it to appear in the vcluster right? That's the desired sync direction I was saying doesn't work for PVCs.

@matskiv and I were discussing this and realized the fact that you're seeing the PV at all is a bug. A PV belonging to a PVC in the host cluster should not be seen by the vcluster.

**Comment by ishankhare07** [comment]
Hi @joaocc , I tried reproducing this issue at my end but was unable to do so. It would be good if you can double check this and if you're able to reproduce this then please share with us the exact manifests that you applied
