### ISSUE TITLE
Generic Syncer Not Deleting CRDs

### ISSUE THREAD

**Issue by psubacz** [loft-sh/vcluster#1047]
### What happened?

There appears to be a deviation from expected and actual behavior if crd is manipulated in the vcluster. The expected behavior is that when created, modified, or deleted in the vlcuster, the change will be reflected in the synced host copy.

### What did you expect to happen?

Resources created, modified, or deleted on the vcluster are reflected in the sync to the host cluster.

### How can we reproduce it (as minimally and precisely as possible)?

* Create a multiname-spaced vlcuster with Generic sync enabled.
* Apply CRDs
* delete the CRDs on the vlcuster

### Anything else we need to know?

*No response*

### Host cluster Kubernetes version

Client Version: [version.Info](http://version.Info){Major:"1", Minor:"27", GitVersion:"v1.27.1",
Server Version: [version.Info](http://version.Info){Major:"1", Minor:"24", GitVersion:"v1.24.9+k3s1"

### Host cluster Kubernetes distribution

AWS EKS 1.23

### vlcuster version

vcluster version 0.15.0

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

k3s(default)

### OS and Arch

mac ventura 13.3.1

**Comment by ishankhare07** [comment]
Hi @psubacz , thanks for reporting this. I'm not super familiar with karpenter, but it seems like this can only be reproduced on AWS infra. Can you verify if this is the case with any other tool as well? We have through examples of some other tools in the examples directory, can you give any of them a try as try reproducing this issue?

This helps us rule out if this is really a:
* Issue with vcluster generic sync
* Issue specific to generic sync with karpenter
* Issue specific to aws karpenter or some misconfiguration – unrelated to vcluster generic sync
