### ISSUE TITLE
Helm nameOverride definied but not used

### ISSUE THREAD

**Issue by markusobsil** [loft-sh/vcluster#1050]
### What happened?

When I tried to configure the name of a vcluster by using the helm chart via a values, I took a look at the current helm chart. I can see that a helper for the [vcluster.name](https://github.com/loft-sh/vcluster/blob/main/charts/k3s/templates/\_helpers.tpl#L5) which uses by default the release name of the helm chart, but supports overriding it with the nameOverride. This looks fine for me. But, when I take a look at the templates folder I can see that the [vcluster.name](http://vcluster.name) is not used.
`➜  templates grep -r "vcluster.name" *  _helpers.tpl:{{- define "vcluster.name" -}}  _helpers.tpl:app.kubernetes.io/name: {{ include "vcluster.name" . }} `

All object names refer to the .Release.Name only, e.g.
`➜  templates head pdb.yaml  {{- if and (.Values.enableHA) (.Values.podDisruptionBudget.enabled) (gt (int .Values.replicas) 1) -}} apiVersion: policy/v1 kind: PodDisruptionBudget metadata:   name: {{ .Release.Name }}`

### What did you expect to happen?

I expect that either the use of nameOverride is supported or that the [vcluster.name](http://vcluster.name) is removed from the chart helper and it is not supported to set the vcluster name via helm values. I, for sure, would prefer the support to set the name of the vcluster per values.yaml.

### How can we reproduce it (as minimally and precisely as possible)?

Add the nameOverride values to the values.yaml file and run a helm template. You will see that this has no impact on the name of the objects.

### Anything else we need to know?

*No response*

### Host cluster Kubernetes version

<details>
Does not depend on Kubernetes version.
</details>

### Host cluster Kubernetes distribution

<details>
Does not depend on Kubernetes cluster distribution.
</details>

### vlcuster version

<details>

```
$ vcluster --version
vcluster version 0.15.0
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
k3s
```

</details>

### OS and Arch

<details>

```
Does not depend on OS and Arch
```

</details>

**Comment by ishankhare07** [comment]
Hi @markusobsil , thanks for creating this issue. Its a good catch that name override is not being used in chart templates anywhere. As far as I can see, using the helm command with a given release name should give you a similar functionality. If there is a usecase which is not solved by this – you can hightlight that, otherwise I guess it would be a fair call to remove it from helpers vs an unnecessary refactoring of all chart values and whever its being used

**Comment by markusobsil** [comment]
Hi @ishankhare07,
no I have no use case which is not solved by using the release name. I use a full gitops approach (powered by ArgoCD), where application names must be unique and have a 1:1 relationship to the underlying helm charts. Even here (where you have a more complex setup than using a helm install command) it works fine. 
So I stick to my suggestion to either remove the helper or use the helper.
