### ISSUE TITLE
docs: namespace mismatch in installation instructions

### ISSUE THREAD

**Issue by joebowbeer** [loft-sh/vcluster#1058]
### What happened?

Referring to these instructions:

[https://www.vcluster.com/docs/getting-started/deployment](https://www.vcluster.com/docs/getting-started/deployment)

The text says that namespace is `vcluster-my-vcluster`

> Let's create a virtual cluster `my-vcluster` in namespace `vcluster-my-vcluster`

But the helm and kubectl instructions create namespace `host-namespace-1`, e.g.,

```
helm upgrade --install my-vcluster vcluster \
  --values vcluster.yaml \
  --repo https://charts.loft.sh \
  --namespace host-namespace-1 \
  --repository-config=''
```

### What did you expect to happen?

helm and kubectl deploy to the documented namespace.

### How can we reproduce it (as minimally and precisely as possible)?

[https://www.vcluster.com/docs/getting-started/deployment](https://www.vcluster.com/docs/getting-started/deployment)

### Anything else we need to know?

*No response*

### Host cluster Kubernetes version

<details>

```
$ kubectl version
N/A
```

</details>

### Host cluster Kubernetes distribution

<details>

```
N/A
```

</details>

### vlcuster version

<details>

```
$ vcluster --version
N/A
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
N/A
```

</details>

### OS and Arch

<details>

```
OS: N/A
Arch: N/A
```

</details>

**Comment by matskiv** [comment]
Thank you for notifying us! This is fixed now :)
