### ISSUE TITLE
linode lke - vcluster create - MountFailed on pod my-cluster

### ISSUE THREAD

**Issue by tglunde** [loft-sh/vcluster#1063]
### What happened?

using quickstart guide I am creating a new cluster with 'vcluster create my-cluster --isolate' on a fresh install of LKE in linode cloud with kubernetes cluster version 1.26. 
The command does not return until timeout and the mu-cluster pod remains in state Error.

This is the error:
Pod my-cluster-0: MountVolume.MountDevice failed for volume "pvc-443f06c5191c4286" : rpc error: code = Internal desc = Unable to find device path out of attempted paths: [/dev/disk/by-id/linode-pvc443f06c5191c4286 /dev/disk/by-id/scsi-0Linode_Volume_pvc443f06c5191c4286] (FailedMount)

### What did you expect to happen?

vcluster create command to succeed without error.

### How can we reproduce it (as minimally and precisely as possible)?

create a LKE cluster on linode with version 1.26 with 16GB node pool

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:13:27Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:33:12Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Host cluster Kubernetes distribution

<details>

```
# Write here
LKE Linode v.126
```

</details>

### vlcuster version

<details>

```console
$ vcluster --version
vcluster version 0.15.0
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
k3s # if thats the default
```

</details>

### OS and Arch

<details>

```
OS: macos ventura
Arch: arm64
```
</details>

**Comment by tglunde** [comment]
sorry, but other stateful sets with PVC can be handled by the cluster with no issue. Do you know what is special with the PVC declaration of vcluster or do you have special pre-requesites?

**Comment by tglunde** [comment]
Thank you for the workaround - that works - but still confused about what makes the pvc fail. Any ideas what is special here?

**Comment by matskiv** [comment]
There is nothing special in PVC: https://github.com/loft-sh/vcluster/blob/cf91a6705d9192578f020ca6ad73327e0708014c/charts/k3s/templates/statefulset.yaml#L46-L56
and the default values used there^ define just the size: https://github.com/loft-sh/vcluster/blob/cf91a6705d9192578f020ca6ad73327e0708014c/charts/k3s/values.yaml#L196-L205

Perhaps you are setting a non-default `storageClassName` on your other PVCs?

**Comment by tglunde** [comment]
Thx for sharing the template. Yes I will look into the storageClassName, but I am not aware of a special one.

**Comment by tglunde** [comment]
sorry for bothering you, but I have now found that my own statefulset does have same error when starting it on the 1.26 lke cluster - I will forward this issue to the linode folks. 
thx for your time.
