### ISSUE TITLE
Question - Isolating vcluster from the host

### ISSUE THREAD

**Issue by JStyle21** [loft-sh/vcluster#1067]
Hi,

I have a question, i'm trying to create a cluster inside of a cluster that way i could manipulate it without having an impact on the original one whilst also still being connected to it so i could exchange info with it but i'm interested in this communication being secure and one way i.e. i want to get info about the host so i could replicate the config in the vcluster but at the same time i don't want anyone from the host to be able to look inside my vcluster or intercept the communication.

Is that something that is achievable or does this require additional development or product integration?

The currently offered isolation mode protects the host from the vcluster but what about the other direction? :)

Any comments are welcomed, if this isn't the right place to have a discussion i'm sorry but i didn't find any other places listed anywhere.

**Comment by matskiv** [comment]
Interesting question. It depends on what sort of permissions other actors in the host cluster have. E.g. if they can get/list Secrets or Pods on the cluster level, or in the vcluster namespace, they will be able to get some(or full with the Secrets) access to the vcluster. The access via Pod get/list permissions can be mitigated with [this feature](https://www.vcluster.com/docs/operator/security#secret-based-service-account-tokens) in v0.15.1+. Then there is also the potential to read data with the pod/exec permission, and maybe some other loopholes too (mounting PV to a pod in a different ns :thinking: ?). There is nothing we can do to protect against users with high permissions in the host cluster.
Then there is network POV, and there a NetworkPolicy with strict ingress rules could be helpful. We don't have any examples of that though, but contributions are obviously welcomed! :)

**Comment by JStyle21** [comment]
@matskiv it's a great summary however our use case is a bit more complex and different.
We would like to discuss it with you in private if possible.

Can you share some contact info so we can arrange a discussion?

**Comment by matskiv** [comment]
@JStyle21 You can find me in the Slack that Loft uses for their open-source projects here - https://slack.loft.sh/
Does that work? :)
