### ISSUE TITLE
vcluster disconnect command doesn't work if custom context name was used

### ISSUE THREAD

**Issue by kostis-codefresh** [loft-sh/vcluster#1073]
### What happened?

I used a custom context name for the vcluster connect command. This broke the vcluster disconnect command

```
➜  workspace vcluster connect target-vcluster-prod -n target-vcluster-prod  --server=https://prod.tf-demo.sales-dev.codefresh.io --kube-config-context-name vcluster_lala
warn   There is a newer version of vcluster: v0.15.2. Run `vcluster upgrade` to upgrade to the newest version.

done √ Switched active kube context to vcluster_lala
- Use `vcluster disconnect` to return to your previous kube contexttt
- Use `kubectl get namespaces` to access the vcluster
➜  workspace vcluster disconnect
fatal  current selected context is not a vcluster context
```

### What did you expect to happen?

The vcluster disconnect command to work

### How can we reproduce it (as minimally and precisely as possible)?

Just use a custom name for context

### Anything else we need to know?

Apparently the code splits the context name with the underscore character and tries to guess which vcluster it belong to

[https://github.com/loft-sh/vcluster/blob/45db0d826d5c44294338ed442f4c1e8f142586a2/cmd/vclusterctl/cmd/find/find.go#L110](https://github.com/loft-sh/vcluster/blob/45db0d826d5c44294338ed442f4c1e8f142586a2/cmd/vclusterctl/cmd/find/find.go#L110)

### Host cluster Kubernetes version

<details>

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.13-eks-0a21954", GitCommit:"6305d65c340554ad8b4d7a5f21391c9fa34932cb", GitTreeState:"clean", BuildDate:"2023-04-15T00:33:45Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Host cluster Kubernetes distribution

<details>

```
EKS 1.24
```

</details>

### vlcuster version

<details>

```
$ vcluster --version
vcluster version 0.14.2
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
k0s
```

</details>

### OS and Arch

<details>

```
OS: Linux (WSL)
Arch: x86
```

</details>

**Comment by FabianKramm** [comment]
@kostis-codefresh thanks for creating this issue! We'll take a look and fix this issue ASAP!
