### ISSUE TITLE
allow limiting usable storageClasses for PVCs in vcluster

### ISSUE THREAD

**Issue by JuniorJPDJ** [loft-sh/vcluster#1079]
### Is your feature request related to a problem?

I'm giving vcluster away to my friend. I'd like to allow him to use some storage classes, but I can't limit that now and he can use all storageClasses from the host cluster. Additionally setting other default storage class for vcluster pods would be a cool addition too.

### Which solution do you suggest?

Give syncer an option to limit usable storage classes on PVCs.

### Which alternative solutions exist?

*No response*

### Additional context

*No response*

**Comment by matskiv** [comment]
There are a few ways to achieve this now:
a) use an admission controller in the host cluster
b) enable [sync of StorageClasses](https://www.vcluster.com/docs/architecture/synced-resources) from virtual cluster to host, then only the SCs that exist in vcluster will be usable + you will be able to set the default one inside vcluster. This combines well with the [init manifests feature](https://www.vcluster.com/docs/operator/init-manifests) to manage the SCs from the vcluster helm values.

We can leave this issue up for further discussion, but I don't think this will have a high priority because of the available workarounds.

**Comment by jpruciak** [comment]
Does a mean that I need to define/write own admission controller?
B is a bad idea, as a guest cluster can be modified by it's own administrator and the admin can define classes I don't want on my host cluster what can give an access to things I don't want to give him.

**Comment by matskiv** [comment]
> Does a mean that I need to define/write own admission controller?

Yes. But you can use one of the existing tools that will greatly simplify it for you - OPA Gatekeeper, JSPolicy, Kyverno or Kubewarden. 
We are working on some commercial features that might help here as well, let me know if you would like to hear more.

> B is a bad idea, as a guest cluster can be modified by it's own administrator and the admin can define classes I don't want on my host cluster what can give an access to things I don't want to give him.

Yes, that is true. On its own, it would not be a completely secure solution. But combined with the admission control, it would be a good user experience IMHO.

**Comment by JuniorJPDJ** [comment]
Sure, tell me more please ;)

**Comment by JuniorJPDJ** [comment]
helm template like this works like a charm:

```
{{- range .Values.storageClassNamespacePolicies }}
apiVersion: policy.jspolicy.com/v1beta1
kind: JsPolicy
metadata:
  name: "{{ .namespace }}-storageclass.r00t.party"
spec:
  type: Mutating
  operations: ["CREATE", "UPDATE"]
  scope: Namespaced
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: {{ .namespace }}
  matchPolicy: "Equivalent"
  apiGroups: [""]
  apiVersions: ["v1"]
  resources: ["persistentvolumeclaims"]
  javascript: |
    const allowedStorageClasses = {{ mustToJson .allowedStorageClasses }};
    const defaultStorageClass = {{ mustToJson .defaultStorageClass }};

    if(!allowedStorageClasses.includes(request.object.spec?.storageClassName)){
      request.object.spec.storageClassName = defaultStorageClass;
      mutate(request.object);
    }
{{- end }}
```

with values like this:
```
storageClassNamespacePolicies:
  wvffle:
    namespace: wvffle
    defaultStorageClass: wvffle
    allowedStorageClasses:
      - wvffle
      - wvffle-hdd
```

thank you very much for showing me jsPolicy ;)

**Comment by matskiv** [comment]
I think this issue should be closed.
There are some workarounds to achieve the desired outcome without adding new flags, so I think it is unlikely to be added.
