### ISSUE TITLE
vcluster delete doesn't delete the vcluster resources

### ISSUE THREAD

**Issue by tomsherrod** [loft-sh/vcluster#1084]
### What happened?

vcluster list

NAME   NAMESPACE   STATUS    CONNECTED   CREATED                         AGE     CONTEXT
vc1    vc1         Running               2023-06-16 19:33:08 -0400 EDT   1m34s   clustername

vcluster delete vc1
info   Delete vcluster vc1...
done √ Successfully deleted virtual cluster vc1 in namespace vc1
done √ Successfully deleted virtual cluster pvc data-vc1-0 in namespace vc1

kubectl -n vc1 get po
NAME                                           READY   STATUS    RESTARTS   AGE
coredns-56d44fc4b4-p72gn-x-kube-system-x-vc1   1/1     Running   0          104s
vc1-0                                          2/2     Running   0          2m11s
tosher@cldlgn03:\~/pipeops/vcluster/vcluster1$ kubectl -n vc1 get pvc
NAME         STATUS        VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-vc1-0   Terminating   pvc-9d75b190-1d19-4e14-82ac-0941ffecd03d   5Gi        RWO            default        2m15s

After waiting some time whilst typing this in:
kubectl -n vc1 get po
NAME                                           READY   STATUS    RESTARTS   AGE
coredns-56d44fc4b4-p72gn-x-kube-system-x-vc1   1/1     Running   0          6m47s
vc1-0                                          2/2     Running   0          7m14s
t

vcluster list

NAME   NAMESPACE   STATUS   CONNECTED   CREATED   AGE   CONTEXT
No entries found

kubectl -n vc1 get pvc
NAME         STATUS        VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-vc1-0   Terminating   pvc-9d75b190-1d19-4e14-82ac-0941ffecd03d   5Gi        RWO            default        10m

### What did you expect to happen?

vcluster delete to remove the vcluster resources.

### How can we reproduce it (as minimally and precisely as possible)?

create vcluster in aks
values.yaml:
vcluster:
resources:
limits:
memory: 4Gi
requests:
cpu: 400m
memory: 512Mi
syncer:
resources:
limits:
cpu: 2000m
memory: 2Gi
requests:
cpu: 40m
memory: 128Mi
storage:
className: default
rbac:
clusterRole:
create: true
sync:
nodes:
enabled: true
syncAllNodes: true
ingresses:
enabled: true
persistentvolumes:
enabled: true
hoststorageclasses:
enabled: true

### Anything else we need to know?

*No response*

### Host cluster Kubernetes version

<details>

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.10", GitCommit:"e770bdbb87cccdc2daa790ecd69f40cf4df3cc9d", GitTreeState:"clean", BuildDate:"2023-05-17T14:12:20Z", GoVersion:"go1.19.9", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.6", GitCommit:"8ca0b02ea721e1631a58bd9c59073608b8b632a5", GitTreeState:"clean", BuildDate:"2023-05-19T03:29:42Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Host cluster Kubernetes distribution

<details>

```
AKS
```

</details>

### vlcuster version

<details>

```
$ vcluster --version
vcluster version 0.15.2
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
k3s(default)
```

</details>

### OS and Arch

<details>

```
OS: Ubuntu 22.04.2 LTS
Arch: x86_64
```

</details>

**Comment by rohantmp** [comment]
Hmm, can you provide the yaml of the deployment and pvc in the vcluster namespace?
Vcluster will use the locally installed version of the helm binary if there is one, is there a locally installed helm version?

**Comment by tomsherrod** [comment]
Thanks for following up.

 helm version
version.BuildInfo{Version:"v3.9.2", GitCommit:"1addefbfe665c350f4daf868a9adc5600cc064fd", GitTreeState:"clean", GoVersion:"go1.17.12"}

Attached are statefulset yaml and pvc yaml. I did not see a deployment.

[data-vc1-0.txt](https://github.com/loft-sh/vcluster/files/11811499/data-vc1-0.txt)
[vc1.sts.txt](https://github.com/loft-sh/vcluster/files/11811500/vc1.sts.txt)

**Comment by rohantmp** [comment]
> Attached are statefulset yaml and pvc yaml. I did not see a deployment.

Yup, that's the one. My bad!

> Attached are statefulset yaml and pvc yaml. I did not see a deployment.

Hmm, the PVC from the issue description is in Terminating stage.
That means the deletion timestamp was set, but the PVC in the attached file doesn't have a deletion timestamp. 

Was looking to debug why the PVC was stuck deleting and why the StatefulSet appeared to not be Terminating when the PVC was. This leads me to believe that this PVC manifest is from another deployment or taken prior to going to going into Terminating stage. Unfortunately, I can't draw any conclusions from this.

Next time: Are you able to reproduce this consistently? If yes, we need to figure out which objects have begun Terminating, and which ones haven't. So can we check the yaml of the PV and StatefulSet immediately after deletion, and 2 minutes after deletion.  Thanks :)

**Comment by tomsherrod** [comment]
My misunderstanding. I stepped through it a couple of times, capturing more information.
Yes, I can reproduce it. The statefulset is immediately gone after the vcluster delete.
I've attached 3 files.
vc.running.txt -- has the namespace contents, pvc and sts yaml, once running.
vc.deleted.txt -- has the namespace contents, pvc and pod yaml, once deleted...blockOwnerDeletion true, is that correct?
vc.deleted.fewminslater.txt -- same as deleted, just a few minutes later.

[vc.deleted.fewminslater.txt](https://github.com/loft-sh/vcluster/files/11818193/vc.deleted.fewminslater.txt)
[vc.deleted.txt](https://github.com/loft-sh/vcluster/files/11818194/vc.deleted.txt)
[vc.running.txt](https://github.com/loft-sh/vcluster/files/11818195/vc.running.txt)

**Comment by tomsherrod** [comment]
Resolved the issue.
Found the core symptom, statefulset deletion left pods around.
After some additional testing and log diving, found the core issue to be a malformed cni install.
Once a valid cni manifest used in the cluster creation, statefulset deletion worked.
vcluster delete works as expected.

Thanks for the review and follow up.
