### ISSUE TITLE
Add `appVersion` to helm chart

### ISSUE THREAD

**Issue by ibrokethecloud** [loft-sh/vcluster#1101]
### Is your feature request related to a problem?

Using vcluster helm chart with k3s `HelmChart` crd works fine until a user attempts to delete the CRD.

The HelmController leverages klipper-helm which queries `appVersion`

[https://github.com/k3s-io/klipper-helm/blob/master/entry#L4-L31](https://github.com/k3s-io/klipper-helm/blob/master/entry#L4-L31)

If `appVersion` is not found, klipper assumes no chart is installed and skips the uninstall.

### Which solution do you suggest?

Introduction of a default `appVersion` in the charts.

Happy to work with the team and provide the PR for this.

### Which alternative solutions exist?

*No response*

### Additional context

*No response*

**Comment by neogopher** [comment]
Hi @ibrokethecloud, :wave: 
Thanks for creating the issue. Yeah, please do take a shot at it and let us know in case of assistance required of any kind.
Really looking forward to your PR!! :slightly_smiling_face:

**Comment by ibrokethecloud** [comment]
Hi @neogopher PR: https://github.com/loft-sh/vcluster/pull/1103 should address this.
