### ISSUE TITLE
Error: unable to create required kubernetes system namespace kube-system: rpc error: code = Unknown desc = database is locked

### ISSUE THREAD

**Issue by davidberglund** [loft-sh/vcluster#1107]
### What happened?

Error when trying to install vcluster in an NS on OpenShift (private, on prem).
I'm following this guide
Running:
`vcluster create my-vcluster -f values.yaml`
With

```
openshift:
  enable: true
```

in values.yaml

One error that stands out to me:
`E0705 10:52:57.695463       7 controller.go:238] unable to create required kubernetes system namespace kube-system: rpc error: code = Unknown desc = database is locked`

### What did you expect to happen?

Successful installation of a virtual cluster inside a namespace in OpenShift.

### How can we reproduce it (as minimally and precisely as possible)?

Run
`vcluster create my-vcluster -f values.yaml`
With

```
openshift:
  enable: true
```

in values.yaml

### Anything else we need to know?

*No response*

### Host cluster Kubernetes version

<details>

```
$ kubectl version
# paste output here
```

</details>

### Host cluster Kubernetes distribution

<details>

```
K8s v1.25.7
OpenShift v4.12.11
```

</details>

### vlcuster version

<details>

```
$ vcluster --version
# 0.15.2
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
# k3s, not sure about the version?
```

</details>

### OS and Arch

<details>

```
OS: OpenSUSE Tumbleweed
Arch: AMD
```

</details>

**Comment by FabianKramm** [comment]
@davidberglund thanks for creating this issue! This usually means there is a problem with the underlying storage used (are you using a NFS style file system?). You can verify that its that problem via using the non persistent option:
```yaml
openshift:
  enable: true

storage:
  persistence: false
```

**Comment by davidberglund** [comment]
Thanks, that got me passed the error. The default storageclass in this cluster is NFS (I understand why that is probably not ideal for something like dqlite (or etcd).

How do I specify the desired storageclass to use then?

**Comment by lizardruss** [comment]
@davidberglund You can specify it through the chart values like this:
```yaml
storage:
  className: other-storage-class
```

**Comment by davidberglund** [comment]
Thanks, I missed that. I see now that it's clearly defined in the values.yaml
