### ISSUE TITLE
Add Homebrew installation method to the docs

### ISSUE THREAD

**Issue by architchandra** [loft-sh/vcluster#1109]
### Is your feature request related to a problem?

I was looking for a method to install vCluster on my Mac using Homebrew but couldn't find it in the docs. Find an [issue](https://github.com/loft-sh/vcluster/issues/402) related to it which had already been resolved but ideally should have found that info in the [docs](https://www.vcluster.com/docs/getting-started/setup).

### Which solution do you suggest?

Add Homebrew installation instructions for Mac in the docs.

### Which alternative solutions exist?

*No response*

### Additional context

*No response*

**Comment by ishankhare07** [comment]
Hi @architchandra , Thanks for creating this issue. As you pointed out, we already have the formula for homebrew working with the vcluster and it would help to have this listed in the docs. Would you mind opening a docs PR for the same and adding a section for homebrew

**Comment by architchandra** [comment]
@ishankhare07 - Please see if the PR is okay.
