### ISSUE TITLE
Question: how to use Workload Identity with vcluster on GKE?

### ISSUE THREAD

**Issue by philippart** [loft-sh/vcluster#1118]
I am running crossplane (this is just an example, the same applies to all kinds of workload) in vcluster in a GKE cluster.

When running crossplane directly in GKE I can configure Workload Identity as described [here](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) to control access to GCP services.

However when running crossplane inside vcluster, even if I sync the crossplane service account on the host namespace, how can I configure workload identity? I dont see how to configure this unless the crossplane pod in the host namespace also runs with a host namespace service account (effectively having 2 service accounts - one for each API server)??
Or am I on the wrong track here?

**Comment by philippart** [comment]
As a matter of fact the crossplane pod on the host namespace runs with the "vc-workload-vcluster" service account so I configured workload identity for that but it's still not working.

**Comment by matskiv** [comment]
Hello @philippart 
I have played quite a bit with AWS IRSA, and I think GKE workload identity is quite similar. There is a multiple ways to configure this depending on your use case and security requirements. I will reach out to you via Slack so you don't have to spill anything sensitive here publicly.

**Comment by rohantmp** [comment]
Closing this for now. Please reopen if this is a mistake.

**Comment by miguepintor** [comment]
@philippart were you able to make it works? could you share your solution?
Thanks in advance
