### ISSUE TITLE
vcluster isolated mode on openshift fails to start

### ISSUE THREAD

**Issue by lburgazzoli** [loft-sh/vcluster#1131]
### What happened?

I've tried to create a vcluster on OpenShift with isolation mode but it failed to deploy, here the output of the vcluster command:

```
info   Waiting until namespace is terminated...
info   Creating namespace vcluster-my-cluster
info   failed to find IPv6 service CIDR: couldn't find host cluster Service CIDR ("Service "" is invalid: spec.clusterIPs[0]: Invalid value: []string{"2001:DB8::1"}: IPv6 is not configured on this cluster")
info   Chart not embedded: "open charts/vcluster-0.15.2.tgz: file does not exist", pulling from helm repository.
info   Create vcluster my-cluster...
info   execute command: helm upgrade my-cluster https://charts.loft.sh/charts/vcluster-0.15.2.tgz --kubeconfig /var/folders/09/7xy_p0ks4p15rm9m_q29ylkw0000gp/T/1234618777 --namespace vcluster-my-cluster --install --repository-config='' --values /var/folders/09/7xy_p0ks4p15rm9m_q29ylkw0000gp/T/3294931957 --values values.yaml
done √ Successfully created virtual cluster my-cluster in namespace vcluster-my-cluster
fatal  finding vcluster pod: context deadline exceeded - can't find a running vcluster pod in namespace vcluster-my-cluster
```

Going into the created namespace, we can see that the replicaset has been created but it won't become ready:

```
NAME                          READY   AGE
statefulset.apps/my-cluster   0/1     6m13s
```

checking the events, we can see there is a warning:

```
- apiVersion: v1
  count: 18
  eventTime: null
  firstTimestamp: "2023-08-01T11:41:34Z"
  involvedObject:
    apiVersion: apps/v1
    kind: StatefulSet
    name: my-cluster
    namespace: vcluster-my-cluster
    resourceVersion: "10450279"
    uid: 1de0e90e-4e71-4f72-b475-63372714b451
  kind: Event
  lastTimestamp: "2023-08-01T11:47:02Z"
  message: 'create Pod my-cluster-0 in StatefulSet my-cluster failed error: pods "my-cluster-0"
    is forbidden: unable to validate against any security context constraint: [provider
    "anyuid": Forbidden: not usable by user or serviceaccount, provider restricted-v2:
    .containers[0].runAsUser: Invalid value: 12345: must be in the ranges: [1000690000,
    1000699999], provider restricted-v2: .containers[1].runAsUser: Invalid value:
    12345: must be in the ranges: [1000690000, 1000699999], provider "restricted":
    Forbidden: not usable by user or serviceaccount, provider "ibm-restricted-scc":
    Forbidden: not usable by user or serviceaccount, provider "nonroot-v2": Forbidden:
    not usable by user or serviceaccount, provider "nonroot": Forbidden: not usable
    by user or serviceaccount, provider "ibm-anyuid-scc": Forbidden: not usable by
    user or serviceaccount, provider "hostmount-anyuid": Forbidden: not usable by
    user or serviceaccount, provider "ibm-anyuid-hostpath-scc": Forbidden: not usable
    by user or serviceaccount, provider "hostnetwork-v2": Forbidden: not usable by
    user or serviceaccount, provider "hostnetwork": Forbidden: not usable by user
    or serviceaccount, provider "hostaccess": Forbidden: not usable by user or serviceaccount,
    provider "ibm-anyuid-hostaccess-scc": Forbidden: not usable by user or serviceaccount,
    provider "node-exporter": Forbidden: not usable by user or serviceaccount, provider
    "ibm-privileged-scc": Forbidden: not usable by user or serviceaccount, provider
    "privileged": Forbidden: not usable by user or serviceaccount]'
  metadata:
    creationTimestamp: "2023-08-01T11:41:34Z"
    name: my-cluster.17773f95277dcaaa
    namespace: vcluster-my-cluster
    resourceVersion: "10452576"
    uid: bde4b2ed-88b5-4906-922f-3b755c62aa78
  reason: FailedCreate
  reportingComponent: ""
  reportingInstance: ""
  source:
    component: statefulset-controller
  type: Warning
```

### What did you expect to happen?

The vcluster shoudl start

### How can we reproduce it (as minimally and precisely as possible)?

create a values.yaml as describe in the [running-on-openshift](https://www.vcluster.com/docs/operator/restricted-hosts#running-on-openshift) guide:

```
openshift:
  enable: true
```

Then try to create a cluster wit isolated mode turned on:

```
vcluster create my-cluster -f values.yaml --isolate
```

check the replica set status and events in the vcluster namespace `vcluster-my-cluster`

### Anything else we need to know?

doing the same without isolation result in an vcluster instance being created

### Host cluster Kubernetes version

<details>

```
$ kubectl version
# paste output here
```

</details>

### Host cluster Kubernetes distribution

<details>

```
OpenShift 4.12.24 running on IBM Cloud
```

</details>

### vlcuster version

<details>

```
vcluster version 0.15.2
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
k3s
```

</details>

### OS and Arch

<details>

```
OS: macOS Ventura 13.5
Arch: Apple M1
```

</details>

**Comment by FabianKramm** [comment]
@lburgazzoli thanks for creating this issue! We will need to investigate this

**Comment by lburgazzoli** [comment]
@FabianKramm if you need any additional info, let me know and I'll be more than happy to help

**Comment by ishankhare07** [comment]
@lburgazzoli thanks for creating this issue. I can see that the vcluster detail logs report some issues with the valid user ID ranges for the `runAsUser` argument. Unfortunately I don't have an opnshift setup on my machine locally to test this but probably looking at / fiddling with these values might help you:
https://github.com/loft-sh/vcluster/blob/main/charts/k3s/values.yaml#L318-L322

Although the documentation suggests otherwise for openshift, it seems like its not working in your case. Let me know if it works for you or whatever update you have post trying this out 🙂

**Comment by matskiv** [comment]
@lburgazzoli When you tried it last time, with the helm values mentioned in the previous comment, have you used the `--isolate` CLI flag? 
If yes, please try it without that flag, as it seems to be not compatible with OpenShift. But setting the `securityContext. runAsNonRoot: true` on OpenShift will achieve the same result as the flag.

**Comment by FabianKramm** [comment]
Closing this for now, feel free to reopen if still a problem

**Comment by lburgazzoli** [comment]
@FabianKramm sorry, I had no time to test and get back to you. Will eventually re-open in case I'll hot the issue again once I have some more time to work again with vcluster.

Thx for the support

**Comment by gnunn1** [comment]
I ran into the same issue, adding the anyuid scc to the serviceaccounts vcluster uses did the trick for me (below is assuming the vcluster name is `vcluster`, changing the name will result in a different serviceaccount name so adjust accordingly).

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scc-anyuid
  namespace: vcluster
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - anyuid
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sa-to-scc-anyuid
  namespace: vcluster
subjects:
  - kind: ServiceAccount
    name: vc-vcluster
  - kind: ServiceAccount
    name: vc-workload-vcluster
roleRef:
  kind: Role
  name: scc-anyuid
  apiGroup: rbac.authorization.k8s.io
  ```
