### ISSUE TITLE
vcluster 0.15.3 reports 0.0.1

### ISSUE THREAD

**Issue by xrstf** [loft-sh/vcluster#1145]
### What happened?

I downloaded the freshly baked 0.15.3 release of vcluster in order to try it out. I then followed https://www.vcluster.com/docs/getting-started/deployment

### What did you expect to happen?

`vcluster create my-vcluster` should have worked without issues in a kind cluster. Instead I got this warning:

> warn   There is a newer version of vcluster: v0.15.2. Run `vcluster upgrade` to upgrade to the newest version.

And vcluster says

>  $ vcluster --version
> vcluster version 0.0.1

Consequently, the pod inside my kind cluster is also borked:

> Failed to pull image "ghcr.io/loft-sh/vcluster:0.0.1": rpc error: code = NotFound desc = failed to pull and unpack image "ghcr.io/loft-sh/vcluster:0.0.1": failed to resolve reference "ghcr.io/loft-sh/vcluster:0.0.1": ghcr.io/loft-sh/vcluster:0.0.1: not found

v0.15.2 works just fine on my machine.

### How can we reproduce it (as minimally and precisely as possible)?

* Download the latest release.
* Try it out.

### Host cluster Kubernetes version

<details>

```console
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:58:30Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-15T00:36:28Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Host cluster Kubernetes distribution

<details>

```
# Write here
```

</details>

### vlcuster version

<details>

```console
$ vcluster --version
vcluster version 0.0.1
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
k8s
```

</details>

### OS and Arch

<details>

```
OS: Ubuntu
Arch: amd64
```
</details>

**Comment by FabianKramm** [comment]
Hey @xrstf ! Thanks for creating this issue! Yes we migrated from buildx to goreleaser and seems like this was missed, we will release v0.15.4 shortly that fixes this, sorry for the incovenience

**Comment by xrstf** [comment]
No worries, just letting you know :)

**Comment by xrstf** [comment]
v0.15.4 fixes all issues reported in this ticket. Thanks!
