### ISSUE TITLE
Docs about logging not up to date

### ISSUE THREAD

**Issue by lorenzo-w** [loft-sh/vcluster#1155]
Commit 53900fd deprecated `hostpathMapper` chart value, yet the current [docs page about monitoring & logging](https://www.vcluster.com/docs/operator/monitoring-logging#enabling-hostpath-mapper) still instructs operators to enable hostpath mapping via that value.

I updated my vcluster to v0.15.5 and now hostpath mapper isn't deployed enymore and logging via Promtail+Loki stopped functioning. What are the plans for this? How can I get logging to work again with v0.15.5?

**Comment by lorenzo-w** [comment]
Hello @ishankhare07, thanks for the quick response!
I had already found the repo you mentioned and expected as much, but I wasn't sure about its status, so I wanted to ask first.
I'll deploy the external host path mapper to my cluster and report back with results.

**Comment by lorenzo-w** [comment]
So I tried to deploy [vcluster-hostpath-mapper](https://github.com/loft-sh/vcluster-hostpath-mapper) to my cluster, but faced a few issues along the way, the last one of which still remains unsolved:

1. vcluster-hpm is not provided by the repo https://charts.loft.sh, so I had to resort to deploying it directly from Git via FluxCD. This first created an issue where including the commit tag into the chart version [created an invalid label](https://github.com/loft-sh/vcluster-hostpath-mapper/blob/0848929be7bba5a8513addab91233834c6e7fc2e/chart/hpm/templates/daemonset.yaml#L13C6-L13C6), as the full version string contained a "+". I was able to solve this by instructing FluxCD to only use the chart semver without the commit tag.
2. The chart seems to expect a value for either `.Values.serviceAccount.name` or `.Values.VclusterReleaseName` and fails to deploy if none is provided. I could only find out about these values by reading through the resource template. They should be documented at least in `values.yaml`, even better in a README.
3. The chart image seems to be private, so I wasn't able to pull it and had to open an [issue](https://github.com/loft-sh/vcluster-hostpath-mapper/issues/4) on the repo

**Comment by ishankhare07** [comment]
Hi @lorenzo-w , the image mismatch issue has been solved with https://github.com/loft-sh/vcluster-hostpath-mapper/pull/5

I'm documenting the readme instructions for hostpath mapper component in the readme while the main docs site is yet to be fully restructured. 

to sum up the instructions:
1. You would have to deploy which daemonset in the same host namespace of your target vcluster
2. Your `.Values.VclusterReleaseName` should match the release name of the target vcluster
3. Your vcluster needs to be deployed with the [MountPhysicalHostPaths](https://github.com/loft-sh/vcluster/blob/53900fd03d3e9d348e5528a1bdafedc20050f8f2/cmd/vcluster/context/flag_options.go#L76) flag enabled as you pointed out. Will update this in the readme soon

**Comment by ishankhare07** [comment]
@lorenzo-w Thanks for the confirmation. Also the chart in the loft repo isn't private, its just a pre release so won't show using the normal helm commands. You can verify with the following command
```shell
helm repo update loft
helm search repo loft/vcluster-hpm --devel  # this is temporary until we have a GA release
```
