### ISSUE TITLE
Question: can I deploy newer k8s vcluster in an older k8s cluster?

### ISSUE THREAD

**Issue by felipecrs** [loft-sh/vcluster#1188]
Hi, this is just a question (because I didn't find any other place to post):

Is it ok to deploy a newer k8s vcluster on top of an older k8s cluster? Any caveats I should be aware of?

For example, my cluster provider currently can only provide me a 1.23 k8s cluster. But I want to certify my application against 1.25-1.28.

Is it safe to deploy newer k8s vclusters on top of 1.23?

There is nothing in the documentation about it. If this is not recommended, I would expect to find some paragraph explaining that. Otherwise, if this is supported, I would expect this to be highlighted as a Pro of vcluster (since it's big deal for me, it could be for others too).

**Comment by matskiv** [comment]
Hello @felipecrs 
This should work, but there are some limitations when it comes to specific APIs, e.g. if the host Kubernetes version does not support ephemeralContainers, then it won't work in the vcluster.
We don't have an exhaustive list of the unsupported features, and we don't have any explicit version support matrix.
Docs contributions are, of course, welcomed. Just FYI, we are refactoring docs at the moment, so have a look at open PRs about that before contributing.

**Comment by felipecrs** [comment]
This is interesting. Thanks a lot for the response.

Can I assume that whatever gets synced to the host cluster (like pods, pvcs), can suffer such kind of incompatibility?

**Comment by matskiv** [comment]
Yes, correct. But AFAIK, so far there has been no breaking incompatibility, just the new features may be affected.

**Comment by felipecrs** [comment]
Got it. Thank you! Unfortunately there is no easy way to capture all these things.

Maybe the best is to try by installing and running some E2E test suite of the application to verify the functionality is preserved.
