### ISSUE TITLE
Add support for Horizontal Pod Autoscaler

### ISSUE THREAD

**Issue by FabianKramm** [loft-sh/vcluster#12]

**Comment by Ab-hishek** [comment]
Since, the deployments, replicasets, statefulsets work similarly as it would in the underlying host cluster, wouldn't the pod autoscaler be taken care of by the host cluster?

**Comment by FabianKramm** [comment]
@Ab-hishek no they would not as the horizontal pod autoscaler object is not synced to the host cluster (we could think about that though). However with version v0.3.0-beta.0 and upward support is possible as we have fake kubelet endpoints that allow the api server to retrieve the correct pod metrics
