### ISSUE TITLE
More than one defaultImageRegistry 

### ISSUE THREAD

**Issue by trowaflo** [loft-sh/vcluster#1200]
### Is your feature request related to a problem?

In our organization we use 1 proxy registry for 1 external registry. Until version 0.14.2 everything is fine, we could use the default registry (defaultImageRegistry: dockerproxy) for hub.docker.com.

But after that and moving to the ghcr register, there are 2 registers to connect to, and you can only specify the values ​​once.

E.g.:
- dockerproxy for hub.docker.com
- ghcrproxy for ghcr.io

```
      - image: {{ .Values.defaultImageRegistry }}{{ .Values.vcluster.image }}
        name: vcluster
...
      - name: syncer
        {{- if .Values.syncer.image }}
        image: "{{ .Values.defaultImageRegistry }}{{ .Values.syncer.image }}"
        {{- else }}
        image: "{{ .Values.defaultImageRegistry }}ghcr.io/loft-sh/vcluster:{{ .Chart.Version }}"
        {{- end }}
```

For now we are not stuck because we can manually specify the docker hub image name/tag in the values. But this is not optimal.

### Which solution do you suggest?

Have the ability to specify different ImageRegistry per image used.

e.g:

```
      - image: {{ .Values.vcluster.imageRegistry | default .Values.defaultImageRegistry }}{{ .Values.vcluster.image }}
        name: vcluster
...
      - name: syncer
        {{- if .Values.syncer.image }}
        image: "{{ .Values.syncer.imageRegistry | default .Values.defaultImageRegistry }}{{ .Values.syncer.image }}"
        {{- else }}
        image: "{{ .Values.syncer.imageRegistry | default .Values.defaultImageRegistry }}ghcr.io/loft-sh/vcluster:{{ .Chart.Version }}"
        {{- end }}

```

**Comment by ThomasK33** [comment]
Hey @trowaflo 👋 

Adding a per-component image registry to every image is currently out of scope, as it's not a popular use case for the individual developer and would add more maintenance overload.

Here are some alternative ways to get your problem solved:
- look into mutating webhooks modifying the image in use (see this Kyverno examples: [Prepend Image Registry](https://kyverno.io/policies/other/m-q/prepend-image-registry/prepend-image-registry/) and [Replace Image Registry](https://kyverno.io/policies/other/rec-req/replace-image-registry/replace-image-registry/))
- Configuring your organization's registry to support multiple source registries.

**Comment by trowaflo** [comment]
Hi @ThomasK33 

Thx for your responses

Unfortunately, I cannot to implement the suggested solutions.

I'm currently working within a large enterprise environment, which operates on a shared infrastructure. Unfortunately, I don't have cluster admin privileges and there's no possibility of obtaining them. Additionally, the registry resources are shared, and I can't challenge the policy of separating proxy registries that has been enforced.

Interestingly, we have multiple proxy registries associated with a single registry, depending on whether we're working inside or outside the cluster.

We've implemented vCluster to overcome our lack of cluster admin rights. We need these rights to install certain Custom Resource Definitions (CRDs) that are crucial for ArgoCD to function. Our deployment process takes place externally from the physical cluster, with the proxy registries hosted on a dedicated VLAN. ArgoCD manages the deployment sources from within the vCluster, targeting the physical clusters via the available proxy registries on the infrastructure VLAN.

So I've identified two potentials workarounds for myself:

1. Utilize the images currently published on Docker Hub (but I think you will probably stop this publication one day).
2. Internally host the chart within our private repositories and customize it according to our needs, as suggested, pointing image to ghcr.io registryproxy for vcluster resource, and docker hub registryproxy for k3s resources.

**Comment by FabianKramm** [comment]
@trowaflo can you not just define the image directly and set without the default registry:
```
syncer:
  image: ...

vcluster:
  image: ...
```

**Comment by trowaflo** [comment]
Ah, of course! I need to include all images in the values.
It was just too simple for me to think about.

Thanx

**Comment by ThomasK33** [comment]
Assuming you've found a suitable solution for your case, I'll close this issue for now.

Please feel free to reopen it at any time if you like.
