### ISSUE TITLE
mapServices .fromVirtual and .toVirtual are missing array indication (values.yaml)

### ISSUE THREAD

**Issue by joaocc** [loft-sh/vcluster#1205]
### What happened?

All values.yaml have a commented-out documentation that is incorrect

```yaml
  # fromVirtual:
  #   from: my-namespace/name
  #   to: host-service
```

### What did you expect to happen?

According to the rest of documentation and with the templates, it should be:
```yaml
  # fromVirtual:
  #   - from: my-namespace/name
  #     to: host-service
```

### How can we reproduce it (as minimally and precisely as possible)?

N/A

### Host cluster Kubernetes version

N/A

### Host cluster Kubernetes distribution

N/A

### vlcuster version

N/A

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

N/A

### OS and Arch

N/A

**Comment by ThomasK33** [comment]
Hey @joaocc 👋 

Yep, we overlooked this one.
I'll open a PR to fix it soon.
