### ISSUE TITLE
Etcd Cluster Remain Out-of-Sync After Ceph Recovery, Causing Service Disruptions in vClusters

### ISSUE THREAD

**Issue by nics90** [loft-sh/vcluster#1210]
### What happened?

In our production environments, we utilize vClusters with Rook Ceph as the underlying storage solution. We've observed the following:

1. OSD Failures Impact Etcd Cluster: When Ceph OSD failures occur at the Rook level, it is expected behavior for the Etcd cluster to get temporarily out of sync.

2. Etcd Out-of-Sync After Ceph Recovery: After Ceph cluster recovery and restoration to a healthy state, we've noticed that the Etcd cluster remains out of sync.
   
3. Etcd Pod Crashes Persist: Restarting the Etcd pods does not resolve the issue. They continue to crash due to the out-of-sync Etcd cluster.
   
4. Impact on vCluster Pods: As a result of the out-of-sync Etcd cluster, other vCluster pods also experience crashes, leading to broader service disruptions.

### What did you expect to happen?

On backend storage recovery, etcd pods should sync up properly. 

### How can we reproduce it (as minimally and precisely as possible)?

To reproduce the issue, follow these steps:

1. Provision a Kubernetes cluster with Rook Ceph installed and operational.
2. Bring down a subset of Ceph OSDs to simulate failures in the Ceph cluster. Observe the Ceph cluster's transition to an unhealthy state.
3. During the Ceph cluster's unhealthy state, monitor the behavior of Etcd pods. Attempt to terminate Etcd pods; they may become stuck in the "Terminating" state.
4. Bring up the previously downed OSDs to restore the Ceph cluster to a healthy state.
5. After restoring the Ceph cluster to health, observe the behavior of Etcd pods within the vCluster. Note that the Etcd pods may go out of sync.

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.9", GitCommit:"6df4433e288edc9c40c2e344eb336f63fad45cd2", GitTreeState:"clean", BuildDate:"2022-04-13T19:57:43Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.9", GitCommit:"6df4433e288edc9c40c2e344eb336f63fad45cd2", GitTreeState:"clean", BuildDate:"2022-04-13T19:52:02Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

```
</details>

### Host cluster Kubernetes distribution

<details>

```
k8s
```

</details>

### vlcuster version

<details>

```console
$ vcluster --version
vcluster version 0.14.1
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
k8s
```

</details>

### OS and Arch

<details>

```
OS: Ubuntu 20.04
Arch: x86_64

Linux 5.4.0-150-generic #167-Ubuntu SMP Mon May 15 17:35:05 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

```
</details>

**Comment by ThomasK33** [comment]
Hey @nics90 👋 

To me, this seems like an etcd issue, given that the etcd cluster is not coming back up after the storage issues and is not forming a consensus.
Because of this, any application that tries to interact with etcd, in this case, Kubernetes, will transitively not work correctly.
I'd recommend opening an issue in the etcd repo/project.

Is there anything on the vCluster side we could do to help regarding this?

**Comment by ThomasK33** [comment]
Hey @nics90, any news regarding this issue?

**Comment by ThomasK33** [comment]
Hey @nics90 👋 , assuming we didn't hear back from you, this issue seems outdated.

I will close it for now, but please feel free to reopen it if necessary.
