### ISSUE TITLE
First Time Start-up: failed to ensure that service CIDR range

### ISSUE THREAD

**Issue by leasley199** [loft-sh/vcluster#1228]
### What happened?

This might just be a first time stand-up gambit but when trying to stand-up the instance I am receiving the following error on the syncer container. 
```sh
failed to ensure that service CIDR range is written into the expected location: Get "https://192.168.1.10:443/api/v1/namespaces/my_namespace/secrets/vc-vcluster-config"
```

On the docs that I have read I can't seem to find anything related to this. help please? 

It appears that we are missing a config item for syncer?

### What did you expect to happen?

vcluster pod to go green and use the application as desired. 

### How can we reproduce it (as minimally and precisely as possible)?

```sh
helm install my-vcluster loft/vcluster --version 0.15.7  -n my_namespace
```

### Anything else we need to know?

NA

### Host cluster Kubernetes version

Server Version: v1.25.10+rke2r1        #RKE2

### Host cluster Kubernetes distribution

Rancher Enterprise Kubenetes

### vlcuster version

0.15.7 via helm

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

default

### OS and Arch

OS:  RHEL 8
Arch: amd64

**Comment by ishankhare07** [comment]
Hi @leasley199 , thanks for creating this issue. Can you please help us with more details like what your vcluster configuration looks like. Include your syncer logs that helps us examine more into what might be causing it

**Comment by ishankhare07** [comment]
Hi @leasley199 , try reproducing this with the latest charts and reopen with more details if you still encounter this issue
