### ISSUE TITLE
Move projected tokens into Secrets or a CSI

### ISSUE THREAD

**Issue by mlbiam** [loft-sh/vcluster#1232]
### Is your feature request related to a problem?

Currently a `Pod` that is synced into a host cluster contains its ServiceAccount token in an annotation that is then projected into a volume via the `projected` configuration.  This approach is at-best an anti-pattern because it requires very long lived tokens (right now 10 years) that can't be refreshed and is at worst a security vulnerability because now any audit infrastructure that logs the contents of a Pod's manifest is logging a long lived secret that can be used against a vcluster.  Additionally, a webhook for `Pods` will also receive these tokens.  (see Ian Coldwater and Brad Geesanan KubeCon 2021 talk - https://www.google.com/search?q=ian+coldwater+brad+geeseman+kubernetes+security&oq=ian+coldwater+brad+geeseman+kubernetes+security&aqs=chrome..69i57j33i10i160l2j33i299l2.23543j0j7&sourceid=chrome&ie=UTF-8#fpstate=ive&vld=cid:5116fc0e,vid:JBbVTmrZ45E,st:574).  Since a `Pod` would have a much lower security threshold then a `Secret`, it may be easier to get someone to create an exfiltrating webhook without them realizing they're exfiltrating their own tokens.

This issue extends to external services as well, potentially a Vault integration, because the token projected will be allowed by Vault for up to ten years, exposing not just the vCluster but also external services that the vCluster uses.

The only mitigations right now is to:

1. Disable all tokens in a `Pod`, which may not be acceptable if the `Pod` needs to work with external services
2. Delete `Pods` periodically to invalidate tokens - Adds a layer of complexity
3. Use a 3rd party identity such as a service mesh, SPIRE, etc. - Adds additional complexity

### Which solution do you suggest?

There are likely two approaches:

**Create `Secret` objects in the host cluster** - When a `Pod` is synced into the host cluster, any project tokens can be created in a `Secret` in the host cluster.  Since `Secret` objects are updated in Pods that mount them, the vCluster can regenerate these tokens on a more periodic basis.   This has the downside of creating objects in etcd that contain tokens, but this is a much lower security risk then having ten year tokens (https://www.macchaffee.com/blog/2022/k8s-secrets/#:~:text=It's%20no%20secret%20that%20Kubernetes,this%20decision%20and%20seeking%20alternatives.)

**Create a token CSI** - This would probably be the *best* solution from a security standpoint since the token would only ever exist on the node that the `Pod` is running on.  

### Which alternative solutions exist?

For accessing the API server of the vCluster, none

For accessing external services, such as Vault, an external identity injector such as a service mesh or SPIRE

**Comment by ishankhare07** [comment]
Hi @mlbiam , thanks for creating this issue. Have you looked into this feature of vcluster - https://www.vcluster.com/docs/operator/security#secret-based-service-account-tokens

**Comment by FabianKramm** [comment]
I'll close this for now as it seems this is already implemented, if I'm mistaken, please feel free to reopen

**Comment by mlbiam** [comment]
Thanks @ishankhare07  for the quick response!  

@FabianKramm  I would re-open this issue for two reasons:

1. I don't see a great reason for syncing to a `Secret` not to be the default.  It's better then embedding the token in the`Pod` spec.  Maybe an argument for being more simply designed but you're already syncing `ConfigMap`s by default and while a hard coded `Secret` isn't great, it's far better then being embedded in the `Pod` spec
2. A CSI would be better then a `Secret`, especially in production environments.
