### ISSUE TITLE
Add --delete-namespace flag in vcluster delete command

### ISSUE THREAD

**Issue by Chakravarti-Baratam** [loft-sh/vcluster#126]
Add  --delete-namespace flag in vcluster delete command, like vcluster create command is having  --create-namespace flag

**Comment by FabianKramm** [comment]
@Chakravarti-Baratam thanks for creating this issue! Yes we can add this

**Comment by Chakravarti-Baratam** [comment]
Thank you. May I know the tentative ETA for this.

**Comment by FabianKramm** [comment]
@Chakravarti-Baratam should be implemented in the next weeks

**Comment by matskiv** [comment]
Seems like this was addressed in #135 - closing.
