### ISSUE TITLE
Throw error when vcluster create command is invoked with existing vcluster name

### ISSUE THREAD

**Issue by Chakravarti-Baratam** [loft-sh/vcluster#127]
Currently vcluster create command is gracefully returning even though there is vcluster is existing with given name.
If two users are trying to create vcluster with same name, this behaviour is not correct.

So, throw error when vcluster create command is invoked with existing vcluster name

Also, it is better to have separate vcluster upgrade command.

**Comment by FabianKramm** [comment]
@Chakravarti-Baratam currently we have an upgrade flag for that as `vcluster create --upgrade=false` will throw an error like you want. In feature we might disable this by default

**Comment by matskiv** [comment]
As mentioned by Fabian, this is achievable with the `--upgrade=false` flag, and since v0.5.0 the default value for the flag is "false".
