### ISSUE TITLE
vcluster connect no longer allows passing commands with "--"

### ISSUE THREAD

**Issue by ttreptow** [loft-sh/vcluster#1272]
### What happened?

Adding commands after vcluster connect using -- no longer works in version 0.16.0.

For example (from the `vcluster connect` help message):
`vcluster connect test -n test -- kubectl get ns`

> 08:10:17 fatal vcluster connect VCLUSTER_NAME [flags]
Invalid Args: received 4 arguments, expected 1, extra arguments: "kubectl, get, ns"
Run with --help for more details on arguments

Probably caused by #1191 

### What did you expect to happen?

vcluster executes the command passed after the "--"

### How can we reproduce it (as minimally and precisely as possible)?

vcluster create test

vcluster connect test -- kubectl get ns

### Host cluster Kubernetes version

1.25

### Host cluster Kubernetes distribution

RKE2

### vlcuster version

0.16.0

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

1.25 (k3s)

### OS and Arch

linux amd64

**Comment by mikehorgan** [comment]
Seeing the same behavior - makes 0.16.0 unusable for me.

**Comment by valkmit** [comment]
Confirmed seeing the same behavior

**Comment by ThomasK33** [comment]
Hey @ttreptow,

Thanks for reporting this issue, I just merged a PR that fixes this/re-enables this again.

I'll cook a new patch release soon.
