### ISSUE TITLE
Node Syncer error when underlying node name is long

### ISSUE THREAD

**Issue by kirinnee** [loft-sh/vcluster#1288]
### What happened?

When using EKS, node-syncer will throw the error:
```
Reconciler error Node "ip-10-10-121-247.ap-southeast-1.compute.internal" is invalid: metadata.labels: Invalid value: "ip-10-10-121-247-ap-southeast-1-compute-internal.nodes.vcluster.com": must be no more than 63 characters
```

### What did you expect to happen?

No error

### How can we reproduce it (as minimally and precisely as possible)?

deploy vcluster on EKS with karpenter

### Anything else we need to know?

- [Reference Slack thread](https://loft-sh.slack.com/archives/C01N273CF4P/p1696734478111499)
- consequence of [this PR](https://github.com/loft-sh/vcluster/pull/1259)

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.28.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.25.12-eks-2d98532
```

</details>

### Host cluster Kubernetes distribution

<details>

```
EKS v1.25.12-eks-2d98532
```

</details>

### vlcuster version

<details>

```console
$ vcluster --version
# paste output here
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>
```
k3s(default)
```
</details>

### OS and Arch

<details>

```
OS: Linux
Arch: aarch64
```
</details>

**Comment by Symbianx** [comment]
We're also having this issue causing all our pods to be stuck in `Pending` state on the vcluster side.

**Comment by ishankhare07** [comment]
Hi @kirinnee and @Symbianx , we have decided to revert the PR which introduced this change. Thanks for reporting this issue
