### ISSUE TITLE
Cannot create services after Cluster-IP range has been extended in host cluster

### ISSUE THREAD

**Issue by cpockrandt** [loft-sh/vcluster#1289]
### What happened?

I set up a vCluster based on k0s with helm chart version 0.15.7. The Kubernetes host cluster runs 1.25.10. When we ran out of ClusterIPs, the admins of the Kubernetes cluster extended the range. I am able to create a service in the host cluster, but the same service cannot be created in the vcluster, giving the following error message: `The Service "test" is invalid: spec.clusterIPs: Invalid value: []string{"192.168.211.208"}: failed to allocate IP 192.168.211.208: the provided IP (192.168.211.208) is not in the valid range. The range of valid IPs is 192.168.210.0/24`

```
---
apiVersion: v1
kind: Service
metadata:
  name: test
spec:
  ports:
    - port: 80
  type: LoadBalancer
```

Is it possible that during the setup of the vcluster, it detected the ClusterIP range and stored it and did not detect the updated ClusterIP range?

### What did you expect to happen?

Service is created.

### How can we reproduce it (as minimally and precisely as possible)?

-

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Host cluster Kubernetes distribution

<details>

```
# Write here
```

</details>

### vlcuster version

<details>

```console
$ vcluster --version
# paste output here
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
# Write here
```

</details>

### OS and Arch

<details>

```
OS: 
Arch:
```
</details>

**Comment by ishankhare07** [comment]
Hi @cpockrandt , I think this is in line with the behavior. The error clearly states the issue in this case the new valid range after it was updated in the host cluster is `192.168.210.0/24` which assigned svc ip does not fall in.
```
ipcalc 192.168.210.0/24                                                                                                                                                                   
Address:   192.168.210.0        11000000.10101000.11010010. 00000000
Netmask:   255.255.255.0 = 24   11111111.11111111.11111111. 00000000
Wildcard:  0.0.0.255            00000000.00000000.00000000. 11111111
=>
Network:   192.168.210.0/24     11000000.10101000.11010010. 00000000
HostMin:   192.168.210.1        11000000.10101000.11010010. 00000001
HostMax:   192.168.210.254      11000000.10101000.11010010. 11111110
Broadcast: 192.168.210.255      11000000.10101000.11010010. 11111111
Hosts/Net: 254                   Class C, Private Internet
```

You can check the current CIDR range being used by the vcluster by checking the args for the vcluster container under the argument `--service-cidr=<cidr_range>`

**Comment by cinimins** [comment]
Hi @ishankhare07  Thank you for your quick reply. The previous range was /24 and it was extended to /23, so the new IP is within the range, but I suspect vcluster did not automatically detect the new CIDR range.

I could not find the argument `--service-cidr` in `kubectl describe`, the only thing I found was `serviceCIDR: CIDR_PLACEHOLDER` in the secret/vc-vc-config. The question is: can I fix this without uninstalling and reinstalling the vcluster?

**Comment by cpockrandt** [comment]
Hi @ishankhare07  Thank you for your quick reply. The previous range was /24 and it was extended to /23, so the new IP is within the range, but I suspect vcluster did not automatically detect the new CIDR range.

I could not find the argument `--service-cidr` in `kubectl describe`, the only thing I found was `serviceCIDR: CIDR_PLACEHOLDER` in the secret/vc-vc-config (my vcluster instance is named `vc`). The question is: can I fix this without uninstalling and reinstalling the vcluster?

**Comment by ishankhare07** [comment]
@cpockrandt  you should find that if you describe the vcluster pod itself. Below is the example of my system's
![Untitled](https://github.com/loft-sh/vcluster/assets/7482025/1a1751b8-3c27-4bc3-bc5c-ad8249a370e3)

**Comment by ishankhare07** [comment]
You would have to update the range in the configmap named `vc-cidr-<vcluster_name>` or override the helm `.Values.serviceCIDR`

**Comment by cpockrandt** [comment]
I do not have the `--service-cidr` argument in my setup, and I do not have a configmap named `vc-cidr-<vcluster_name>`. Setting the `.Values.serviceCIDR` to `192.168.210.0/23` did not fix the issue.

![image](https://github.com/loft-sh/vcluster/assets/7328307/7c839927-32d6-48e5-b809-32412ab30f5c)

![image](https://github.com/loft-sh/vcluster/assets/7328307/b5abb56f-80a3-47a1-bf74-1aa07298fad3)

**Comment by cpockrandt** [comment]
I found a secret with the name `vc-vc-config` that contained the correct serviceCIDR. I got it to work by restarting the statefulset. Changing the secret does not trigger a restart of the vcluster pod when using helm upgrade, hence the mounted secret was outdated.

Suggestion: Would it be possible to add something like the hash value of the secret to the annotation of the statefulset, such that it forces a reployment of the statefulset, when the secret is changed?

**Comment by ishankhare07** [comment]
@cpockrandt I discussed this internally with the team and we think for now it's not something that we want to add to the supported use cases and add to the complexity of the charts. The best way would be to manually restart that pod for now
