### ISSUE TITLE
CoreDNS Pending with SyncError

### ISSUE THREAD

**Issue by ichasepucks** [loft-sh/vcluster#1293]
### What happened?

CoreDNS is failing to start on my vcluster with the following error message:
```
Error syncing to physical cluster: admission webhook "validation.gatekeeper.sh" denied the request: [restricted-capabilities] PSP-CAPABILITIES: Pod/coredns-6ccdd78696-b58cb-x-kube-system-x-k6-operator-vcluster in the namespace k6-operator-system: init container <coredns> has a disallowed capability. Allowed capabilities are ["AUDIT_WRITE"]
```

### What did you expect to happen?

CoreDNS to start

### How can we reproduce it (as minimally and precisely as possible)?

I just installed the vcluster with an Ingress.  I suspect our host clusters may be set to Restricted https://kubernetes.io/docs/concepts/security/pod-security-standards/.  The namespace is provided to us with admin access but no access outside the namespace.

### Host cluster Kubernetes version

<details>

```console
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.26.7-eks-2d98532
```

</details>

### Host cluster Kubernetes distribution

<details>

```
EKS
```

</details>

### vlcuster version

<details>

```console
vcluster version 0.15.7
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
k3s
```

</details>

### OS and Arch

<details>

```
OS: Linux
Arch: amd64
```
</details>

**Comment by FabianKramm** [comment]
@ichasepucks thanks for the issue! CoreDns needs the `NET_BIND_SERVICE` capability from v1.11.0 on as it listens on a below 1024 port. You will need to allow this in your gatekeeper policy. The `NET_BIND_SERVICE` capability doesn't impose any security risk and is even allowed by the strict "restriced" policy of Kubernetes itself (https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted).

**Comment by ichasepucks** [comment]
@FabianKramm, thanks for the reply.  I'm working with our cluster administrators to try to allow this.  Good to know this requirement now.  I'll close this issue.
