### ISSUE TITLE
Sync Deployment, Statefulset, Jobs and other resources

### ISSUE THREAD

**Issue by kirinnee** [loft-sh/vcluster#1298]
### Is your feature request related to a problem?

Yes, in-hopes of doing telemetry only on the host cluster. i hope to be able to access metadata on the virtual cluster without installing observability agents on the virtual cluster.

Example use cases:
- obtaining number of replica requests vs actual replicas
- health of statefulsets

Observability agents tested:
- [OTEL kubeletstats (Reciever)](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/kubeletstatsreceiver/README.md)
- [OTEL k8scluster (Reciever)](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/kubeletstatsreceiver/README.md)
- [OTEL k8sevents (Reciever)](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/kubeletstatsreceiver/README.md)
- [OTEL k8sattributes (Processor)](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/kubeletstatsreceiver/README.md)
- [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics)

### Which solution do you suggest?

Simplest way would be to sync deployments as `fake-deployments` or shims that contains the same metadata from virtual to host

### Which alternative solutions exist?

deploying all observability agents into each virtual cluster

**Comment by matskiv** [comment]
As an alternative approach, instead of creating some shims, vcluster could produce the metrics that are needed, and the host agent would just need to collect. This is just a quick idea, open for a discussion ofc.

**Comment by rohantmp** [comment]
One point re: 

> Simplest way would be to sync deployments as fake-deployments or shims that contains the same metadata from virtual to host

If you're trying to get  useful data like requested replicas vs ready replicas, copying the metadata from virtual to host wouldn't work. That's in spec and status. If you copy spec, it will try to reconcile on the host cluster.

**Comment by rohantmp** [comment]
Closing this for now as the suggested approach seem not to be feasible and it has been inactive for some time. Feel free to reopen if you feel this needs more discussion :)
