### ISSUE TITLE
Complete Doc Review: Fix/Enchnace doc issues for complete documentation files 

### ISSUE THREAD

**Issue by syedzubeen** [loft-sh/vcluster#1312]
### What happened?

This reviews typos/grammatical enhancements for the entire docs for the devpod.

### What did you expect to happen?

NA

### How can we reproduce it (as minimally and precisely as possible)?

NA

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Host cluster Kubernetes distribution

<details>

```
# Write here
```

</details>

### vlcuster version

<details>

```console
$ vcluster --version
# paste output here
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
# Write here
```

</details>

### OS and Arch

<details>

```
OS: 
Arch:
```
</details>

**Comment by FabianKramm** [comment]
@syedzubeen did you mean to open this issue in DevPod?

**Comment by syedzubeen** [comment]
@FabianKramm 
I just completed one for DevPod: https://github.com/loft-sh/devpod/issues/755
Now working on this one for Vluster.

**Comment by syedzubeen** [comment]
This is ready for review.

**Comment by alexandradragodan** [comment]
Hey, @syedzubeen 
Thanks a lot for your contribution!

Closing this issue now as the PR got merged. 
Please feel free to reopen if there's any open findings.
