### ISSUE TITLE
Kuberenetes service with "IPv4/IPv6 dual-stack" creation fails inside vcluster

### ISSUE THREAD

**Issue by karthick-kk** [loft-sh/vcluster#1318]
### What happened?

I have a host cluster where IPV4/IPV6 dualstack is configured. I tried to create a sample service which gets created and allocated with both IPV4 and IPV6.
 
 svc.yaml
 ```
 apiVersion: v1
kind: Service
metadata:
  name: test-nginx-svc
spec:  
  type: "ClusterIP"
  ipFamilyPolicy: "PreferDualStack"
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: nginx
 ```
 
On Host Cluster:
###############
```
❯ kubectl describe svc test-nginx-svc
Name:              test-nginx-svc
Namespace:         default
Labels:            <none>
Annotations:       <none>
Selector:          app.kubernetes.io/name=nginx
Type:              ClusterIP
IP Family Policy:  PreferDualStack
IP Families:       IPv4,IPv6
IP:                10.99.11.238
IPs:               10.99.11.238,fc00:2000::f18f
Port:              http  8080/TCP
TargetPort:        80/TCP
Endpoints:         <none>
Session Affinity:  None
Events:            <none>
```
Service-CIDR:
```
❯ vcluster get service-cidr
10.96.0.0/12,fc00:2000::/112
```

We have a vcluster(0.16.3) running on this host. When we try to create the same sample service in vcluster, we get the error below

```
❯ kubectl apply -f svc.yaml          
The Service "test-nginx-svc" is invalid: spec.clusterIPs[1]: Invalid value: []string{"10.103.233.199", "fc00:2000::819d"}: IPv6 is not configured on this cluster
```
Also attached is the vcluster values.yaml

Are we missing any configuration here?

### What did you expect to happen?

Kubernetes service is expected to be created as same as host cluster with IPV4 and IPV6

### How can we reproduce it (as minimally and precisely as possible)?

Steps defined in "What happened?"

### Host cluster Kubernetes version

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:22:29Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.16", GitCommit:"51e33fadff13065ae5518db94e84598293965939", GitTreeState:"clean", BuildDate:"2023-07-19T12:19:24Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
```

### Host cluster Kubernetes distribution

K8S
``
v1.24.16
```



### vlcuster version


```console
❯ vcluster --version
vcluster version 0.16.3
```

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
v1.28.2+k3s1
```

</details>

### OS and Arch

<details>

```
OS: Ubuntu 18.04.5
Arch: x86_64
```
</details>
[values.yaml.txt](https://github.com/loft-sh/vcluster/files/13165580/values.yaml.txt)

**Comment by FabianKramm** [comment]
@karthick-kk thanks for creating this issue! I think you need to enable that within the vcluster, could you send the vcluster logs here?

**Comment by karthick-kk** [comment]
Please find attached vcluster log
[vcluster-log-dualstack.txt](https://github.com/loft-sh/vcluster/files/13224113/vcluster-log-dualstack.txt)

**Comment by karthick-kk** [comment]
> @karthick-kk thanks for creating this issue! I think you need to enable that within the vcluster, could you send the vcluster logs here?

Thanks for the pointer

We managed to get it working after adding the IPV6 CIDR to the serviceCIDR flag of values.yaml as documented in https://docs.k3s.io/installation/network-options#dual-stack-ipv4--ipv6-networking
