### ISSUE TITLE
Unknown flag coredns-enabled

### ISSUE THREAD

**Issue by markusobsil** [loft-sh/vcluster#1319]
### What happened?

When you deploy vcluster via helm chart and disabled coredns deployment, the vcluster Pod does not start, because of a configuration error. 
When you take a look at the logs, you can see:
```
> k logs vcluster01-0 syncer
F1025 11:45:08.925527       1 main.go:35] unknown flag: --coredns-enabled
```
So it seems it is caused here:
https://github.com/loft-sh/vcluster/blob/main/charts/k3s/templates/statefulset.yaml#L307

### What did you expect to happen?

The vcluster pod should start without deploying a Core DNS deployment within the vcluster.

### How can we reproduce it (as minimally and precisely as possible)?

Deploy the latest version of vcluster helm chart on a kubernetes (in my case kind) cluster:

```
> cat values-no-coredns.yaml
coredns:
  enabled: false
```

```
> helm install vcluster01 loft-sh/vcluster -n vcluster01 --version 0.16.4 --create-namespace --values values-no-coredns.yaml                                  kind-kind:default
NAME: vcluster01
LAST DEPLOYED: Wed Oct 25 13:42:42 2023
NAMESPACE: vcluster01
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Thank you for installing vcluster.

Your vcluster is named vcluster01 in namespace vcluster01.
```

```
> k logs vcluster01-0 syncer
F1025 11:45:08.925527       1 main.go:35] unknown flag: --coredns-enabled
```

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-14T13:14:41Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-05-12T19:03:40Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Host cluster Kubernetes distribution

<details>

```
kind v0.19.0 go1.20.4 darwin/amd64
```

</details>

### vlcuster version

<details>

```console
$ vcluster --version
vcluster version 0.15.0
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
k3s helm chart version 0.16.4
```

</details>

### OS and Arch

<details>

```
OS: 
Arch:
```
</details>

**Comment by matskiv** [comment]
Good catch :+1: 
https://github.com/loft-sh/vcluster/blob/ee8da39b4aadaf79567c225a839f80bc8b0014a3/charts/k3s/templates/statefulset.yaml#L306-L308
Yeah, this condition should also check that `.Values.pro` is true.

@markusobsil Since it is Hacktoberfest now, are you interested in contributing a fix? :)
