### ISSUE TITLE
Copy secrets from host cluster to vcluster seems not working

### ISSUE THREAD

**Issue by yangyang919** [loft-sh/vcluster#1347]
### What happened?

Following the guide, we have configured generic sync, the vcluster can be launched, but secrets are not copied.

Our config:

```
vcluster:
  image: rancher/k3s:v1.23.5-k3s1

syncer:
  env:
    - name: DEBUG
      value: "true"
      
multiNamespaceMode:
  enabled: true
sync:
  secrets:
    all: true
    enabled: true
  generic:
    role:
      extraRules:
        - apiGroups: [""]
          resources: ["secrets"]
          verbs: ["create", "delete", "patch", "update", "get", "list", "watch"]
    clusterRole:
      extraRules:
        - apiGroups: [""]
          resources: ["secrets"]
          verbs: ["create", "delete", "patch", "update", "get", "list", "watch"]
    config: |-
      version: v1beta1
      import:
        - kind: Secret
          apiVersion: v1
```

### What did you expect to happen?

Our requirement is simple, just wanna copy secrets from host cluster to vcluster. I suspect the documentation does not specify the details clearly. Maybe the supported feature is not working as we thought? From the doc, the config is very easy...

https://www.vcluster.com/docs/syncer/other_resources/config_syntax#host-to-virtual-sync

### How can we reproduce it (as minimally and precisely as possible)?

just create a vcluster using our config, then check whether secrets can by synced to vcluster

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:41:42Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.7", GitCommit:"84e1fc493a47446df2e155e70fca768d2653a398", GitTreeState:"clean", BuildDate:"2023-07-19T12:16:45Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.26) exceeds the supported minor version skew of +/-1
```

</details>

### Host cluster Kubernetes distribution

<details>

```
# Write here
community version
```

</details>

### vlcuster version

<details>

```console
$ vcluster --version
# paste output here
vcluster version 0.16.3
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
# Write here
k3s
```

</details>

### OS and Arch

<details>

```
OS: Mac 14.1
Arch:
```
</details>

**Comment by joaocc** [comment]
Did you try https://github.com/flanksource/vcluster-sync-host-secrets to replicate secrets from host to vcluster?

**Comment by ishankhare07** [comment]
hi @yangyang919 , what is the source host cluster namespace that you are expecting to sync secrets from?
the secrets will only be synced from the namespaces being used by the vcluster.
There's no way you should be syncing secrets from all namespaces of host to vcluster

**Comment by joaocc** [comment]
That is indeed not the case. As per the documentation, only secrets with annotations are synchronized. And the nice people at flanksource added a way to specify different target vcluster-internal-namespace in each secret.

**Comment by yangyang919** [comment]
hi @ishankhare07 I am trying to sync the secrets either from host namespace or any other namespace. Any place is fine. But from the documentation, it didn't clearly say only host cluster namespace is allowed: https://www.vcluster.com/docs/syncer/other_resources/config_syntax#host-to-virtual-sync
The generic sync from host to virtual cluster

**Comment by yangyang919** [comment]
@joaocc I see what the plugin tries to do. I am wondering whether generic sync also provide similar features? At least from this doc: https://www.vcluster.com/docs/syncer/other_resources/config_syntax#host-to-virtual-sync, it makes me understand that any secrets from host cluster can be synced to vclusters...Does it mean the doc is somehow a bit misleading?

**Comment by joaocc** [comment]
It seems so, but I haven't tested it. However it seems the control we can get via https://github.com/flanksource/vcluster-sync-host-secrets is more fine grained (in our specific case). We get to specify exactly which secret is syncronized to which vcluster-namespace. If you decide to take the generic sync route pls share your findings. thx

**Comment by yangyang919** [comment]
@joaocc yes, this plugin is the solution. That particular feature of syncing the secrets in generic sync is aimed at syncing secrets generated "for" vcluster's resources, not dedicated for our use case
