### ISSUE TITLE
Map headless from hostcluster to vcluster does not work

### ISSUE THREAD

**Issue by tamasborsstriva** [loft-sh/vcluster#1394]
### What happened?

from vcluster the mapped mongodb service is inaccessible

service is mapped to the vcluster, but can not be used:

![vcluster](https://github.com/loft-sh/vcluster/assets/93583313/b0d45773-dfe8-4d5f-8ca2-dc040dae83fa)

### What did you expect to happen?

access to mapped mongodb service from vcluster with `mongodb-headless.mapServices.svc.cluster.local` command

### How can we reproduce it (as minimally and precisely as possible)?

install mongodb to hostcluster
deploy vcluster with this config:

 ```
 mapServices:
  fromHost:
 - from: default/example-mongodb-svc
    to: mynamespace/mongodb-headless
```
deploy any pod in vcluster, and try to access to the MongoDB: `mongodb-headless.mapServices.svc.cluster.local`

### Host cluster Kubernetes version

<details>

```console


$ kubectl version
Client Version: v1.28.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.2
```

</details>

### Host cluster Kubernetes distribution

<details>

```
k8s
```

</details>

### vlcuster version

<details>

```console
$ vcluster --version
vcluster version 0.17.1
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
k8s
```

</details>

### OS and Arch

<details>

```
OS: Ubuntu 23.10
Arch:
```
</details>

**Comment by FabianKramm** [comment]
@tamasborsstriva thanks for creating this issue! Is there any log output in the vcluster?

**Comment by tamasborsstriva** [comment]
@FabianKramm I haven't found any related logs
Do you have any idea where to look for?

**Comment by tamasborsstriva** [comment]
@FabianKramm were you able to reproduce the issue?
thank you

**Comment by SzilardS** [comment]
I also ran into this issue, could you please check?

**Comment by tamasborsstriva** [comment]
Hey @neogopher 
yes it solves the issue, you can close this ticket
thank you
