### ISSUE TITLE
RFE: Set default context name to the same as cluster name

### ISSUE THREAD

**Issue by magnusboman** [loft-sh/vcluster#142]
When a new vcluster is created, the default context in the kubeconfig file is `Default`. Would it be possible to rename it to the name of the cluster, or let the user decide on a name when the cluster is created? It is useful for tools like the powerline_k8sstatus that shows the context and namespace on your bash prompt.

**Comment by FabianKramm** [comment]
@magnusboman thanks for creating this issue! Sure, we can change it to the vcluster name

**Comment by matskiv** [comment]
Currently, the context will be named based on this code: `"vcluster_" + vClusterName + "_" + vClusterNamespace + "_" + currentContext`, this is required for some handy cli features (e.g. `vcluster disconnect`).
But you also can set the context name when creating vcluster, or when connecting to it, with the `--kube-config-context-name` flag.
