### ISSUE TITLE
The annotations `.Values.syncer.serviceAnnotations` are added to 2 services

### ISSUE THREAD

**Issue by frank-bee** [loft-sh/vcluster#1425]
### What happened?

These annotations are added to the 2 syncer services, the one of type "LoadBalancer" and the other one.
This causes problems if the annotation are e.g. one for the LoadBalancer ( e.g. in the case of AWS LB controller being used or External Secrets Controller).

See also https://loft-sh.slack.com/archives/C01N273CF4P/p1702896194745799?thread_ts=1702721637.157309&cid=C01N273CF4P

### What did you expect to happen?

The annotations should be added only to the service of type LoadBalancer.
Alternatively there should be 2 helm values. 

### How can we reproduce it (as minimally and precisely as possible)?

- add some annotations via the helm value

### Host cluster Kubernetes version

n.A.

### Host cluster Kubernetes distribution

n. A.

### vlcuster version

latest

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

eks

### OS and Arch

n.a.

**Comment by FabianKramm** [comment]
@frank-bee thanks for creating this issue! @ThomasK33 is implementing this for the next release!
