### ISSUE TITLE
Proxy all k8s metrics from host cluster to vcluster even with fake nodes

### ISSUE THREAD

**Issue by amir-latifi** [loft-sh/vcluster#1429]
### Is your feature request related to a problem?

Having k8s metrics in vclusters is necessary to manage and maintain vclusters properly. But enabling real nodes raises security and isolation issues when multiple vclusters with different owners are deployed on a single host cluster. So there is no way to have k8s metrics (except metrics-server metrics) inside vclusters when nodes are fake. 

### Which solution do you suggest?

Implement a feature like metrics server proxy feature which forwards cadvisor, kube-state-metrics, ... metrics to vcluster. In this case there would be no need to enable real nodes which disrupts isolation of vclusters which are deployed on a single host cluster.

**Comment by amir-latifi** [comment]
This issue is created based on a conversation in slack and a suggestion from @ThomasK33 for easier  tracking and more visibility.

**Comment by ThomasK33** [comment]
Hey @amir-latifi, I'll close this issue since we last heard from you a month ago.
Feel free to reopen it if Fabian's proposal doesn't work for you. 😄
