### ISSUE TITLE
To comply with nsa-cisa-kubernetes-hardening-guidance

### ISSUE THREAD

**Issue by calvinroyston** [loft-sh/vcluster#143]
[https://kubernetes.io/blog/2021/10/05/nsa-cisa-kubernetes-hardening-guidance/](https://kubernetes.io/blog/2021/10/05/nsa-cisa-kubernetes-hardening-guidance/)

**Comment by matskiv** [comment]
This is probably solved now with [the Isolated mode](https://www.vcluster.com/docs/operator/security).
I am happy to reopen if you point out what is still missing.
