### ISSUE TITLE
Feature request: Add support for wildcards or regexes in `--sync-labels`

### ISSUE THREAD

**Issue by Guent4** [loft-sh/vcluster#1456]
### Is your feature request related to a problem?

After reading through https://github.com/loft-sh/vcluster/issues/386, I incorrectly thought that `--sync-labels` supported regexes (the description of the flag is not explicit about support/not support in https://www.vcluster.com/docs/config-reference).  After some testing, it didn't seems like it's not supported.  After reviewing the linked PR in the issue, it seems like the logic for `--sync-labels` is a simple map lookup ([link](https://github.com/loft-sh/vcluster/pull/391/files#diff-386847f08de4efcedda561db320577a51b5ed12b91cc722b50e5b6ac42be4d7aR104-R105)) which confirms that regexes and wildcards aren't supported.

It would be really nice if regexes could be supported because then we can set `--sync-labels=my.company/.*` to sync all of company specific labels.  We (who manage the host + vCluster setup) have centralized Prometheus running in the host cluster and would like to allow users (other teams who use the vClusters) to specify `PodMonitor` resources inside their vCluster which gets synced out to the host cluster (this part works fine) and pick up the pods that get synced to the host cluster via LabelSelectors.  Unfortunately, without regex/wildcard support, we would need to explicitly define a set of labels that would be supported for this functionality.

### Which solution do you suggest?

Right now the logic is as follows:
```
		if vObjLabels != nil {
			for _, k := range n.syncedLabels {
				if value, ok := vObjLabels[k]; ok {
					newLabels[k] = value
				}
			}
		}
```
To add support for regexes, it could look something like this:
```
		if vObjLabels != nil {
			for _, k := range n.syncedLabels {
				for vLabelKey, vLabelValue := range vObjLabels {
					match, _ := regexp.MatchString(k, vLabelKey)
					if match {
						newLabels[k] = value
					}
				}
			}
		}
```
Unfortunately a performance hit due to the extra looping through the list of vLabels.

**Comment by FabianKramm** [comment]
Hey @Guent4! Thanks a lot for this issue, yes thats true I would be in favour of that!

**Comment by neogopher** [comment]
Hi @Guent4 !! 
Thanks for writing in. :slightly_smiling_face: 

We already support wildcards in the sync-labels field via [this](https://github.com/loft-sh/vcluster/pull/1112) PR, so you can just use something like `--sync-labels=my.company/*` (instead of `--sync-labels=my.company/.*`) . This will then sync all the labels for that company domain.

We hope this will assist with your use case. Do let me know if you face any issues.

**Comment by Guent4** [comment]
@neogopher ah, you are totally right, I totally missed the change your PR added.  It works perfectly, thank you!

**Comment by joebowbeer** [comment]
@neogopher Something that is not clear in the docs is that the _only_ wildcard supported is an explicit `/*` _suffix_:

```golang
if strings.HasSuffix(k, "/*") {
	r, _ := regexp.Compile(strings.ReplaceAll(k, "/*", "/.*"))
```

So `--sync-labels=test.sh/label*` does not work as it might be expected to.

While on the topic of doc improvement, it would be helpful to include an example showing how to provide multiple values to these array-valued extra args:

`--sync-labels=test.sh/label1,test.sh/label2`
