### ISSUE TITLE
RBAC  endpoints for "create" "delete" "patch" "update" forbidden

### ISSUE THREAD

**Issue by antoinetran** [loft-sh/vcluster#1465]
### What happened?

vcluster cannot be deployed: fatal error:
```
... is attempting to grant RBAC permissions not currently held:
{APIGroups:[""], Resources:["endpoints"], Verbs:["create" "delete" "patch" "update"]}
```
 

### What did you expect to happen?

The vcluster should not request endpoints (if possible) because it is disable for security reason.

### How can we reproduce it (as minimally and precisely as possible)?

Deploy or request a OpenShift Kubernetes cluster, and deploy Rancher UI.
Use Rancher UI to grant Owner role to an account.
Rancher does not provide Endpoints permission anymore (see https://kubernetes.io/docs/reference/access-authn-authz/rbac/#write-access-for-endpoints) because of this CVE (https://github.com/kubernetes/kubernetes/issues/103675) .

Then run the command vcluster deployment:
```
vcluster create my-vcluster -f values.yaml --namespace example --debug
```

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.26.4
```

</details>

### Host cluster Kubernetes distribution

<details>

```
Unknown, probably Kubernetes vanilla with kubespray ou kubeadm?
```

</details>

### vlcuster version

<details>

```console
$ vcluster --version
vcluster version 0.18.1

```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
k8s
```

</details>

### OS and Arch

<details>

```
OS: RedHat 8
Arch: x86_64
```
</details>

**Comment by ThomasK33** [comment]
Hey, @antoinetran, thanks for opening an issue.

Have you considered turning off the endpoints sync if it's not permitted in your environment?
By default, the endpoint sync is enabled, but it can be turned off with:

```yaml
sync:
  endpoints:
    enabled: false
```

**Comment by antoinetran** [comment]
> Hey, @antoinetran, thanks for opening an issue.
> 
> Have you considered turning off the endpoints sync if it's not permitted in your environment? By default, the endpoint sync is enabled, but it can be turned off with:
> 
> ```yaml
> sync:
>   endpoints:
>     enabled: false
> ```

No, but I will try! If we don't create endpoint inside our vcluster, then I guess we don't need this indeed.

**Comment by antoinetran** [comment]
Thanks, turning it off solved the issue! Sorry, I thought endpoint was mandatory for vcluster to work, but I didn't know it was optional. Closing it.
