### ISSUE TITLE
Scaling a vCluster StatefulSet replica from 1 to 3 should not break the `k3s kube-api certificate volume`. 

### ISSUE THREAD

**Issue by jbarfield** [loft-sh/vcluster#1466]
### What happened?

I went to scale an existing vCluster from 1 replica to 3 because an event occurred requiring that I cordon and drain a parent cluster node, however the parent cluster never completes draining the node. It is stuck in draining state infinitely. 

After some debugging I found that the behavior is expected because `k8s` will not a drain a node containing a stateful set of `replicas: 1`. 

To mitigate this issue I attempted to scale the vCluster statefulSet from 1 to 3 like so:

`vcluster create -n <NAMESPACE> --upgrade -f values.yaml -f <PATH>/cert-manager-plugin.yaml <vCLUSTER_NAME>`
```
# I only updated the following line in values.yml...which does appear to have properly scaled the replica sets to 3 pods in good status.
replicas: 3
```

### What did you expect to happen?

I expected the vCluster to scale from 1 to 3 stateful pods and for the kube-api-server to come back online correctly.

### How can we reproduce it (as minimally and precisely as possible)?

Deploy a vcluster using default values. Update/Add `replicas: 3` to the values.yaml. Then run: `vcluster create --upgrade -f values.yml cluster-name`

### Anything else we need to know?

Here are the logs from vcluster-pod-0:

https://pastebin.com/d6Rs44gb

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.5", GitCommit:"890a139214b4de1f01543d15003b5bda71aae9c7", GitTreeState:"clean", BuildDate:"2023-05-17T14:14:46Z", GoVersion:"go1.19.9", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.5", GitCommit:"890a139214b4de1f01543d15003b5bda71aae9c7", GitTreeState:"clean", BuildDate:"2023-05-17T14:08:49Z", GoVersion:"go1.19.9", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Host cluster Kubernetes distribution

<details>

```
# Write here
kubernetes 1.26.5 - kubespray
```

</details>

### vlcuster version

<details>

```console
$ vcluster --version
# paste output here
vcluster version 0.18.1
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
# Write here
k3s
```

</details>

### OS and Arch

<details>

```
OS:  Fedora38-Cloud
Arch: x86_64
```
</details>

**Comment by jbarfield** [comment]
This actually appears to occur on any cluster that starts with 3 replicas. Even 
from scratch.

**Comment by jbarfield** [comment]
Let me check this. I ended up fixing by passing in a variable `leader-elect=true` to k3s. At least I thought that fixed it but maybe it was something else.

**Comment by FabianKramm** [comment]
@jbarfield strange that that was not happening automatically

**Comment by FabianKramm** [comment]
I'll close this for now, but feel free to reopen if you feel we need to do something here
