### ISSUE TITLE
[Feature Request] Provide Integration Document with Istio Ingress Controller

### ISSUE THREAD

**Issue by yeahdongcn** [loft-sh/vcluster#1467]
### Is your feature request related to a problem?

Yes.

I'm using `Istio` as the ingress controller in my cluster, but I can't find any [document](https://www.vcluster.com/docs/using-vclusters/access#via-ingress) about how to work with `Istio`.

### Which solution do you suggest?

Provide Integration Document with Istio Ingress Controller

**Comment by yeahdongcn** [comment]
@Joey2021-dev @maratrixx

**Comment by alexandradragodan** [comment]
Hey, @yeahdongcn 
Thanks for reaching out! 

We have [this docs page ](https://www.vcluster.com/docs/networking/ingress_traffic)that describes the ingress traffic routing when it comes to synching vcluster resources. 

Could you please describe in more detail what are you trying to achieve with istio and vcluster?

**Comment by yeahdongcn** [comment]
> Hey, @yeahdongcn Thanks for reaching out!
> 
> We have [this docs page ](https://www.vcluster.com/docs/networking/ingress_traffic)that describes the ingress traffic routing when it comes to synching vcluster resources.
> 
> Could you please describe in more detail what are you trying to achieve with istio and vcluster?

I'd like to access vCluster via Ingress and https://www.vcluster.com/docs/using-vclusters/access#via-ingress lists several ingress controllers like [Kubernetes Nginx](https://kubernetes.github.io/ingress-nginx/user-guide/tls/?_gl=1*ry62o*_ga*MjE0NjM2NTYzNS4xNjk5NDk2MTU1*_ga_4RQQZ3WGE9*MTcwNjc1NTIyMS40OS4xLjE3MDY3NTU0MTMuNjAuMC4xOTY0MjgzMTM3*_gcl_au*MzM4MjA0NTcwLjE2OTk0OTYxNTU.#ssl-passthrough) [Traefik Proxy](https://doc.traefik.io/traefik/routing/routers/?_gl=1*ry62o*_ga*MjE0NjM2NTYzNS4xNjk5NDk2MTU1*_ga_4RQQZ3WGE9*MTcwNjc1NTIyMS40OS4xLjE3MDY3NTU0MTMuNjAuMC4xOTY0MjgzMTM3*_gcl_au*MzM4MjA0NTcwLjE2OTk0OTYxNTU.#passthrough) and [Emissary](https://www.getambassador.io/docs/emissary/latest/topics/using/tcpmappings?_gl=1*ry62o*_ga*MjE0NjM2NTYzNS4xNjk5NDk2MTU1*_ga_4RQQZ3WGE9*MTcwNjc1NTIyMS40OS4xLjE3MDY3NTU0MTMuNjAuMC4xOTY0MjgzMTM3*_gcl_au*MzM4MjA0NTcwLjE2OTk0OTYxNTU.#tls-termination). Could you please extend the document on how to work with istio?

**Comment by yeahdongcn** [comment]
I don't know why this issue is marked as `not planned`. @alexandradragodan Could you explain?
