### ISSUE TITLE
vCluster does not work with Istio CNI plugin

### ISSUE THREAD

**Issue by lk-1984** [loft-sh/vcluster#1483]
### What happened?

Installed Istio inside vCluster with Istio CNI plugin enabled. Tried to deploy into the vCluster, but pods cannot start due "FailedCreatePodSandBox". If I disable the Istio CNI plugin, then everything works. The problem is that our product requires Istio CNI plugin.

### What did you expect to happen?

All pods to work with CNI enabled.

### How can we reproduce it (as minimally and precisely as possible)?

Install Istio (1.19.0) with CNI plugin.

### Host cluster Kubernetes version

<details>

```
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.6+k3s1", GitCommit:"bd04941a294793ec92e8703d5e5da14107902e88", GitTreeState:"clean", BuildDate:"2023-09-20T23:05:58Z", GoVersion:"go1.20.8", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.25) and server (1.27) exceeds the supported minor version skew of +/-1
```

</details>

### Host cluster Kubernetes distribution

<details>

```
AKS
```

</details>

### vlcuster version

<details>

```console
$ vcluster --version
0.18.1
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
k3s
```

</details>

### OS and Arch

<details>

```
OS: Why? OS of what?!
Arch:
```
</details>

**Comment by jakerbeck** [comment]
Same issue on RKE2 running v1.26.  As a quick solution I installed the Istio CNI outside the vcluster (on the host cluster) and that unblocked me.  It would be ideal to have the ability to install Istio CNI inside the vcluster but it looks like the Istio CNI Pods are confused about the syncer's names for the pods.

After I installed the CNI on the host cluster I can use the other Istio components (istiod/gateway/etc.) normally inside the vclusters.

**Comment by facchettos** [comment]
yeah I don't think that it can work, since the pods and the namespaces are modified on the host cluster. I would go the same route as @jakerbeck. Installing CNI or CSI component inside vcluster seems like a not so good idea since those intrinsically need some infos from the actual host cluster. 

> OS: Why? OS of what?!

This is for issues regarding the cli or other components, where it is important to know about those attributes
