### ISSUE TITLE
create PersistentVolume for PersistentVolumeClaim in case of cluster is not having dynamic volume provisioning support

### ISSUE THREAD

**Issue by developer-guy** [loft-sh/vcluster#150]
Hello, the `vCluster CLI` creates a PVC but not creates PV instead it waits for creating PV via dynamic volume provisioning (IMHO) but if the cluster is only supporting static provisioning, the `vCluster` Pods stay in the `Pending` state.

It would be nice to create PV also to avoid having this kind of problems 😋

**Comment by developer-guy** [comment]
related with #145

**Comment by eminaktas** [comment]
Hello, @developer-guy, and I worked on this issue. We have a couple of alternatives to automate the creation of PV. 

### Solution: Install OpenEBS as [dynamic local PV provisioner](https://github.com/openebs/dynamic-localpv-provisioner)

OpenEBS Dynamic Local PV provisioner can dynamically provision Kubernetes Local Volumes using different kinds of storage available on the Kubernetes nodes.

- Add OpenEBS as a conditional sub chart:
  - https://newbedev.com/helm-conditionally-install-subchart
- Add a flag to vcluster CLI to enable deploying OpenEBS Helm chart for example: `--enable-dynamic-pv`
- Make OpenEBS host path as default storage class 
  - `kubectl patch storageclass openebs-hostpath -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'`

### Alternatives: 
- [Sig Storage Local Persistence Volume Static Provisioner](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner)
- [Rancher Local Path Provisioner](https://github.com/rancher/local-path-provisioner)

![screen_shot_2021-10-17_at_14 22 24](https://user-images.githubusercontent.com/54074230/137627418-7ea4e9b1-42c6-4775-b1bc-a13229bf2662.png)

**Comment by matskiv** [comment]
From the comments, it sounds like this issue is resolved, so I'll close it. But drop a comment if I got it wrong :)
