### ISSUE TITLE
Syncer emptyDir `data` volume never getting created with vCluster 0.19.0-alpha.4

### ISSUE THREAD

**Issue by Guent4** [loft-sh/vcluster#1503]
### What happened?

Same bug as https://github.com/loft-sh/vcluster/issues/1491 but for the block that defines whether to create a `data` `emptyDir` volume for syncer sts.

Regardless of whether you set `.Values.syncer.storage.persistence` to `true` or to `false`, the `emptyDir` volume will never get created.

### What did you expect to happen?

If I set `.Values.syncer.storage.persistence` to `false`, I should see
```
        - name: data
          emptyDir: {}
```
in the definition of the syncer sts.

### How can we reproduce it (as minimally and precisely as possible)?

```
> helm version
version.BuildInfo{Version:"v3.12.3", GitCommit:"3a31588ad33fe3b89af5a2a54ee1d25bfe6eaa5e", GitTreeState:"clean", GoVersion:"go1.20.7"}
>
>
> helm template test loft-sh/vcluster --set syncer.storage.persistence=true --version 0.19.0-alpha.4 | yq '.spec.template.spec.volumes'
null
---
null
---
null
---
null
---
null
---
null
---
null
---
null
---
- name: helm-cache
  emptyDir: {}
- name: binaries
  emptyDir: {}
- name: tmp
  emptyDir: {}
- name: config
  emptyDir: {}
- name: coredns
  configMap:
    name: test-coredns
- name: custom-config-volume
  configMap:
    name: coredns-custom
    optional: true
> helm template test loft-sh/vcluster --set syncer.storage.persistence=false --version 0.19.0-alpha.4 | yq '.spec.template.spec.volumes'
null
---
null
---
null
---
null
---
null
---
null
---
null
---
null
---
- name: helm-cache
  emptyDir: {}
- name: binaries
  emptyDir: {}
- name: tmp
  emptyDir: {}
- name: config
  emptyDir: {}
- name: coredns
  configMap:
    name: test-coredns
- name: custom-config-volume
  configMap:
    name: coredns-custom
    optional: true
```
Theoretically, the bottom one should have an extra `emptyDir` volume named `data`

### Anything else we need to know?

The block in question is: https://github.com/loft-sh/vcluster/blob/92c8bdfc03c588de07e8d591784074a9e92dc986/charts/k3s/templates/syncer.yaml#L137-L140

The
```
{{- if not ( include "vcluster.storage.persistence" . ) }}
```
should be replaced with
```
{{- if not (eq ( include "vcluster.storage.persistence" . ) "true" ) }}
```

### Host cluster Kubernetes version

Irrelevant, able to reproduce with `helm template` locally

### Host cluster Kubernetes distribution

Irrelevant, able to reproduce with `helm template` locally

### vlcuster version

0.19.0-alpha.4

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

k3s

### OS and Arch

<details>

```
OS: Ubuntu 20.04.4 LTS
Arch: amd64
```
</details>

**Comment by neogopher** [comment]
Hi @Guent4 ,
Thanks for creating the issue. :slightly_smiling_face: 

Since you have already identified the fix, would you like to contribute via a PR for the same.

**Comment by Guent4** [comment]
Yep, would love to!  Was a bit late last night so I didn't get to it.  I'll work on getting a PR submitted this morning (PST).
