### ISSUE TITLE
use Helm Go SDK instead of using binary

### ISSUE THREAD

**Issue by developer-guy** [loft-sh/vcluster#154]
Hello, it would be nice to use Helm Go SDK to avoid using binary itself. It makes the `vCluster` easier to use in CI/CD environments.

* [https://helm.sh/docs/topics/advanced/#go-sdk](https://helm.sh/docs/topics/advanced/#go-sdk)
* [https://pkg.go.dev/helm.sh/helm/v3](https://pkg.go.dev/helm.sh/helm/v3)
* [https://stackoverflow.com/questions/45692719/samples-on-kubernetes-helm-golang-client](https://stackoverflow.com/questions/45692719/samples-on-kubernetes-helm-golang-client)
* [https://www.reddit.com/r/golang/comments/mtvm96/install_helm_chart_using_go_programmatically/](https://www.reddit.com/r/golang/comments/mtvm96/install_helm_chart_using_go_programmatically/)

cc: @dentrax @erkanzileli @eminaktas

**Comment by matskiv** [comment]
We have found blocking problems with dependencies when trying to use helm Go library, so instead, we made an enhancement in this area - vcluster CLI will download helm binary automatically if it can't find it (#730). This got released in v0.12.0. Is that sufficient for your use case @developer-guy?

**Comment by felipecrs** [comment]
Can this be reconsidered now that Helm 4 is out and the Go SDK is marked as Stable?

https://helm.sh/docs/overview/#stable-sdk-api
