### ISSUE TITLE
docs: sync-labels wildcard is an explicit '/*' suffix

### ISSUE THREAD

**Issue by joebowbeer** [loft-sh/vcluster#1559]
Something that is not clear in the docs is that the _only_ wildcard supported is an explicit `/*` _suffix_:

```golang
if strings.HasSuffix(k, "/*") {
	r, _ := regexp.Compile(strings.ReplaceAll(k, "/*", "/.*"))
```

So `--sync-labels=test.sh/label*` does not work as it might be expected to.

While on the topic of doc improvement, it would be helpful to include an example showing how to provide multiple values to these array-valued extra args:

`--sync-labels=test.sh/label1,test.sh/label2`

_Originally posted by @joebowbeer in https://github.com/loft-sh/vcluster/issues/1456#issuecomment-1964072346_

Also see #1112

**Comment by neogopher** [comment]
Hi @joebowbeer :wave: ,
Thanks for writing in!!

The wildcard support helps you match labels at the domain level i.e. all argo labels with 'argocd.appproj.io/\*' or all loft labels with 'loft.sh/*'. 
At the same time, I understand you want this to match at a more granular level. Let me bring this up internally.

**Comment by joebowbeer** [comment]
This is a request for a documentation enhancement, not a feature enhancement.

By the way, as I read the k8s spec, labels don't intrinsically have a domain level, they are just strings; the domain syntax is a convention.

**Comment by mysiki** [comment]
Hey, as mention 'labels don't intrinsically have a domain level', did you think it's possible to support direct string instead of domain level ?
