### ISSUE TITLE
Helm-Chart does not allow setting resources for initContainer in StatefulSet

### ISSUE THREAD

**Issue by cinimins** [loft-sh/vcluster#1562]
### Is your feature request related to a problem?

Kubernetes clusters can enforce that all containers and initContainers must specify resource requests and/or resource limits. With the most recent vcluster helm charts, this is not possible:

https://github.com/loft-sh/vcluster/blob/da4a60269d9e8b44ada0820bfc1e7deba93a2b0f/charts/k0s/templates/syncer.yaml#L119-L133

### Which solution do you suggest?

Allow setting the resources for the vcluster initContainer in the values.yaml.

### Which alternative solutions exist?

Set default values for the vcluster initContainer

**Comment by cinimins** [comment]
I think it was simply just forgotten, since it is included in the k3s chart, but not in the k0s chart. I opened a PR to add it.

**Comment by facchettos** [comment]
Hey, thank you so much for the PR, would you mind adding it to k8s and eke too please ? 🙏 
Otherwise LGTM, good find ! :)
