### ISSUE TITLE
Syncer: JSON logging

### ISSUE THREAD

**Issue by cinimins** [loft-sh/vcluster#1570]
### Is your feature request related to a problem?

I thought I could have the syncer do the logging in JSON format to better evaluate the logs.

The vcluster root command documents the option `--log-output string`, but apparently this option does not exist (or work) in the vcluster container when running `vcluster start`. I get this INFO message:

```
2024-02-28 17:14:08     INFO    vcluster/main.go:44     unknown flag: --log-output      {"component": "vcluster"}
```

Did I misunderstand the documentation or is JSON logging in `vcluster start` not supported?

### Which solution do you suggest?

I think it would be nice to be able to switch to JSON logs to better evaluate the logs in solutions such as Splunk.

**Comment by ThomasK33** [comment]
Hey @cinimins, thanks for opening this issue.

To set the log encoding and log level on the vCluster control plane, you can use `LOFT_LOG_ENCODING` and `LOFT_LOG_LEVEL`. 

The `--log-output` flag is only available in the vCluster CLI (vclusterctl) and not in the vCluster control plane binary within the container.

**Comment by heiko-braun** [comment]
@cinimins I think it's not yet documented. Would you be interested contributing a short paragraph? This might be a good place for it:

https://github.com/loft-sh/vcluster/blob/main/docs/pages/help%26tutorials/troubleshooting.mdx
