### ISSUE TITLE
How to Configure vcluster to Use Internal Docker Registry Certificates?

### ISSUE THREAD

**Issue by fjammes** [loft-sh/vcluster#1576]
Hello,

I'm setting up a vcluster instance and I want it to use images from an internal Docker registry available at docker-registry.docker-registry:5000. On regular Kubernetes nodes, I usually configure this by placing the registry certificates in /etc/docker/certs.d/docker-registry.docker-registry:5000/ca.crt. However, I'm not sure how to configure vcluster to utilize these certificates. Can someone provide guidance on how to configure vcluster to use internal Docker registry certificates?

**Comment by facchettos** [comment]
What is the issue that you are facing? vCluster uses the underlying cluster to create pods, so if you host cluster is configured to use that, it should work.

**Comment by fjammes** [comment]
Thank you for your response.

The issue I'm facing revolves around the kubelet on the host needing to reach a Kubernetes internal image registry. Unfortunately, kubelet cannot directly use Kubernetes clusterIP services for this purpose. As a workaround, we've had to register the internal image registry within the company DNS and make it reachable through an ingress, which adds complexity to the setup.

Considering this challenge, I'm wondering if vCluster could provide a mechanism to simplify this process or avoid the need for such intricate configurations. Any insights or suggestions on this matter would be greatly appreciated.

Looking forward to hearing your thoughts.

**Comment by facchettos** [comment]
not really, since vcluster still uses the kubelet to fetch the images.
