### ISSUE TITLE
invalid allowPrivilegeEscalation field in vcluster and coredns podSecurityContext specs

### ISSUE THREAD

**Issue by joebowbeer** [loft-sh/vcluster#1582]
### What happened?

The following is reported after helm chart 0.18.1

> strict decoding error: unknown field "spec.template.spec.securityContext.allowPrivilegeEscalation"

### What did you expect to happen?

Nothing

### How can we reproduce it (as minimally and precisely as possible)?

Code search:

This field only exists in the [containerSecurityContext](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#securitycontext-v1-core)

Yet, _**all the values files**_ except k3s contain this invalid field in their [podSecurityContext](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#podsecuritycontext-v1-core)

https://github.com/loft-sh/vcluster/blob/main/charts/eks/values.yaml

And _**all coredns templates**_ contain it as well:

https://github.com/loft-sh/vcluster/blob/main/charts/k3s/templates/coredns.yaml#L145

### Anything else we need to know?

https://loft-sh.slack.com/archives/C01N273CF4P/p1709648261620029

### Host cluster Kubernetes version

<detail>N/A</detail>

### Host cluster Kubernetes distribution

<detail>N/A</detail>

### vlcuster version

<detail>N/A</detail>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<detail>N/A</detail>

### OS and Arch

<detail>N/A</detail>

**Comment by johannesfrey** [comment]
Hey @joebowbeer

Thanks for raising this issue. Regarding the coredns templates: they seem to be correct, as it's under the container's securityContext.

**Comment by joebowbeer** [comment]
@johannesfrey thanks for fix and correction: coredns templates are OK.
