### ISSUE TITLE
Custom Syncers

### ISSUE THREAD

**Issue by rmb938** [loft-sh/vcluster#159]
It would be nice to have some documentation or an example on how to go about making a custom syncer.

A use-case would be for CRDs like cert-manager. The host cluster would have the issuer and credentials to issue certificates while the vcluster doesn't. In the vcluster we would create a certificate resource and a custom syncer that syncs it to and from the host cluster.

**Comment by olljanat** [comment]
FYI. Now vcluster have support for plugins https://www.vcluster.com/docs/plugins/overview and here is even case example for CRD sync https://github.com/loft-sh/vcluster-sdk/tree/main/examples/crd-sync

Also based on discussion on https://github.com/loft-sh/vcluster/issues/443#issuecomment-1110694323 it probably would be possible to get those code and hosted here as same repo with vcluster it selves.

**Comment by matskiv** [comment]
We have a doc with a plugin development tutorial here - https://www.vcluster.com/docs/plugins/tutorial
Also, we have an initial version of a plugin that can sync resources based on yaml configuration, so no coding is required. Here is documentation for that - https://www.vcluster.com/docs/plugins/generic-crd-sync and we also have [example configuration for cert-manager](https://github.com/loft-sh/vcluster-generic-crd-sync-plugin/blob/main/examples/cert-manager/plugin-without-ingress.yaml) and a few more [in the plugin repo](https://github.com/loft-sh/vcluster-generic-crd-sync-plugin).

I think these existing solutions satisfy what was originally requested in this issue, so I'll close it. But we would be happy to receive feedback on how we could further improve in this area.
