### ISSUE TITLE
Broken links to charts

### ISSUE THREAD

**Issue by heiko-braun** [loft-sh/vcluster#1599]
### What happened?

With the consolidation of chart values in `main`, documentation links from https://www.vcluster.com/docs/deploying-vclusters/supported-distros are broken:

https://github.com/loft-sh/vcluster/tree/**main**/charts/k3s

### What did you expect to happen?

Getting the actual 1.19.x charts.

### How can we reproduce it (as minimally and precisely as possible)?

Follow the links named `Check the _github repository_ for all available chart options` from https://www.vcluster.com/docs/deploying-vclusters/supported-distros

**Comment by cezar-guimaraes** [comment]
Hi! Just a heads up that the links are still broken in the [website](https://www.vcluster.com/docs/deploying-vclusters/supported-distros). I was about to open an issue when I found this one.

For anyone in the same situation, charts can currently be found here https://github.com/loft-sh/vcluster/tree/v0.19/charts
