### ISSUE TITLE
Guidance and performance information on using database backends (mysql, postgres)

### ISSUE THREAD

**Issue by joaocc** [loft-sh/vcluster#1623]
### Is your feature request related to a problem?

Not a problem, but rather a lack of guidance on performance characteristics or scalability on running vcluster using database backend (mysql, postgres) as per https://www.vcluster.com/docs/deploying-vclusters/persistence#datastore-options.

### Which solution do you suggest?

Provide some guidance on what to pay attention to when planning to use database as persistence layer (mysql, postgres), for the control plane (vs etcd).
At the moment there doesn't seem to be anything in the site, github or slack.

### Which alternative solutions exist?

Not much

**Comment by alexandradragodan** [comment]
Hey, @joaocc 
Thanks for the suggestion. 

Have you taken a look [here](https://www.vcluster.com/docs/advanced-topics/load-testing/results)?

Let me know if that's helpful in tackling your endeavour

**Comment by heiko-braun** [comment]
External database storage is on the roadmap and will be included in future versions. For now, only k3s seems to cover what you are looking for: https://www.vcluster.com/docs/deploying-vclusters/persistence
