### ISSUE TITLE
PVC specs not all synced into vcluster

### ISSUE THREAD

**Issue by cpockrandt** [loft-sh/vcluster#1633]
### What happened?

I have a vcluster (v0.19.4) with k0s set up with the default configuration (i.e., no syning of storage classes from vcluster no host cluster, etc.). In my vcluster namespace, I created a PVC and specified a storage class that allows extending the disk later on.

Then I noticed, that I cannot actually extend the PVC from within the vcluster: `error: persistentvolumeclaims "os-mngr-os-mngr-0" could not be patched: persistentvolumeclaims "os-mngr-os-mngr-0" is forbidden: only dynamically provisioned pvc can be resized and the storageclass that provisions the pvc must support resize`,

But extending it from the host cluster works (in the example below, I extendid it from 8Gi to 150Gi using `kubectl edit`).

Afterwards, I noticed that  `spec.storageClassName` in the vcluster is missing from the PVC in the vcluster, which probably explains why I got the error message in the first place.

<details>

<summary>PVC in vcluster</summary>

```yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: csi.trident.netapp.io
  creationTimestamp: "2024-03-28T10:59:04Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/instance: arkime
    app.kubernetes.io/name: opensearch
  name: os-mngr-os-mngr-2
  namespace: arkime-test
  resourceVersion: "651084"
  uid: 0340f120-89f3-4b9a-9770-c3cbe7d236d4
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem
  volumeName: pvc-96e23170-bd36-4b19-9bb8-5b07b68c8d1c
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 150Gi
  phase: Bound
```

</details>

<details>

<summary>PVC in host cluster</summary>

```yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    vcluster.loft.sh/object-name: os-mngr-os-mngr-2
    vcluster.loft.sh/object-namespace: arkime-test
    vcluster.loft.sh/object-uid: 0340f120-89f3-4b9a-9770-c3cbe7d236d4
    volume.beta.kubernetes.io/storage-provisioner: csi.trident.netapp.io
    volume.kubernetes.io/storage-provisioner: csi.trident.netapp.io
  creationTimestamp: "2024-03-28T10:59:04Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    vcluster.loft.sh/label-vc-x-71dafa318e: opensearch
    vcluster.loft.sh/label-vc-x-9039c53507: arkime
    vcluster.loft.sh/managed-by: vc
    vcluster.loft.sh/namespace: arkime-test
  name: os-mngr-os-mngr-2-x-arkime-test-x-vc
  namespace: itue-dev
  ownerReferences:
  - apiVersion: v1
    controller: false
    kind: Service
    name: vc
    uid: 52942b29-6e88-4bc6-b13c-f0db3b95529f
  resourceVersion: "448408999"
  uid: 96e23170-bd36-4b19-9bb8-5b07b68c8d1c
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 150Gi
  storageClassName: ontap-gold
  volumeMode: Filesystem
  volumeName: pvc-96e23170-bd36-4b19-9bb8-5b07b68c8d1c
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 150Gi
  phase: Bound
```

</details>

It might be relevant, that I do not have access in the host cluster to list the storage classes.

### What did you expect to happen?

I expect the PVC in the vcluster to have the same specs as in the host cluster, allowing me to resize the PVC.

### How can we reproduce it (as minimally and precisely as possible)?

Create a PVC in the vcluster with a storageclass that allows expanding the volume and perform `kubectl edit` aftwards.

### Host cluster Kubernetes version

v1.25.16+vmware.1

### vlcuster version

vcluster 0.19.4 installed via official Helm chart.

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

k0s

### OS and Arch

unknown

**Comment by rohantmp** [comment]
You can enable storageclasses syncing and create one in the vcluster with that references an existing provisioner on your host or  enable hoststorageclasses syncing to view the storageclasses from your host cluster to your vlcluster.

The syncers are described here: https://www.vcluster.com/docs/syncer/core_resources.

You can enable these syncers as described here: https://www.vcluster.com/docs/syncer/config

**Comment by rohantmp** [comment]
Please feel free to reopen if the existing feature I described does not resolve the issue.
