### ISSUE TITLE
vcluster connect hangs in airgapped environment when firewall is silently dropping Internet traffic

### ISSUE THREAD

**Issue by trondvindenes-hvikt** [loft-sh/vcluster#1682]
### What happened?

When connecting to a vcluster where the CLI is executed in an airgapped environment, the connect command will hang for approximately 30 seconds while attempting to check for newer versions.

I've turned of telemetry by using vcluster telemetry disable.

Every 1.0s: sudo netstat -anop | grep -i SYN_SENT
tcp        0      1 10.bbb.ccc.ddd:56312     140.82.121.6:443        SYN_SENT    1104193/vcluster     on (3.36/3/0)

[username@workstation 0.19.5]$ time vcluster -n namespace connect vcluster
14:03:12 info Using vcluster vcluster load balancer endpoint: 10.ddd.eee.fff
14:03:12 done Switched active kube context to vcluster_vcluster_namespace_clustername
- Use `vcluster disconnect` to return to your previous kube context
- Use `kubectl get namespaces` to access the vcluster

real    0m30.229s
user    0m0.139s
sys     0m0.024s

### What did you expect to happen?

That the command completes within a couple of seconds, which is what happens if I enable proxy using environment variables. But proxy or Internet connection isn't always allowed.

[username@workstation 0.19.5]$ . enable_proxy #shell script for setting environment variables
[username@workstation 0.19.5]$ time vcluster -n namespace connect vcluster
14:19:26 info Using vcluster vcluster load balancer endpoint: 10.ddd.eee.fff
14:19:26 done Switched active kube context to vcluster_vcluster_namespace_clustername
- Use `vcluster disconnect` to return to your previous kube context
- Use `kubectl get namespaces` to access the vcluster

real    0m1.178s
user    0m0.194s
sys     0m0.034s

### How can we reproduce it (as minimally and precisely as possible)?

Attempt to connect to a vcluster when the vcluster command is executed from an airgapped workstation. External firewall must probably be set to drop traffic, and not reject it.

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.27.8
Kustomize Version: v5.0.1
Server Version: v1.27.8+vmware.1
```

</details>

### Host cluster Kubernetes distribution

<details>

```
Tanzu Kubernetes Grid Integrated
```

</details>

### vlcuster version

<details>

```console
$ vcluster --version
vcluster version 0.19.5
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
k8s
```

</details>

### OS and Arch

<details>

```
OS: Red Hat Enterprise Linux 9
Arch: x86_64
```
</details>

**Comment by ThomasK33** [comment]
Hey @trondvindenes-hvikt, as you pointed out, the connect and create commands will check for newer CLI releases on GitHub.

You can omit this by setting the `VCLUSTER_SKIP_VERSION_CHECK=true` environment variable.
