### ISSUE TITLE
Dependent Environment Variables are not getting Expanded on using vcluster

### ISSUE THREAD

**Issue by ramanNarasimhan77** [loft-sh/vcluster#170]
Hello,

As per Kubernetes documentation, it is possible to define interdependent environment variables

https://kubernetes.io/docs/tasks/inject-data-application/define-interdependent-environment-variables/ 

Based on this, we have a helm chart wherein the service port is exposed as a Generic Env using something like below:

`
MY_SERVICE_PORT: $(MY_CHART_MY_SERVICE_PORT)
`

This works fine when I installation via helm directly on the cluster.

However when I use vcluster, the Variable expansion/substitution is not happening and the value of `MY_SERVICE_PORT` is string `$(MY_CHART_MY_SERVICE_PORT)`

## Using vCluster : Not Working MY_SERVICE_PORT is not set properly
`
$ env | grep PROXY_API_SERVICE_PORT
MY_SERVICE_PORT=$(MY_CHART_MY_SERVICE_PORT)
MY_CHART_MY_SERVICE_PORT=8001
`

## Direct Installation on cluster: MY_SERVICE_PORT is set properly
`
$ env | grep PROXY_API_SERVICE_PORT
MY_SERVICE_PORT=8001
MY_CHART_MY_SERVICE_PORT=8001
`

**Comment by rajeshnair** [comment]
@FabianKramm , thanks for the quick resolution of the issue.
Can you release the fix in a new tag for us to pick it up?

**Comment by ramanNarasimhan77** [comment]
@FabianKramm  thank you for quick resolution. The helm chart which I was trying to install is proprietary and I was planning to create one and share with you today for testing but by then you have already provided guidance to @matskiv for issuing a fix 

I have built the syncer image from master and tested the fix & it works great.  Thank you once again for issuing a quick fix
