### ISSUE TITLE
kubeconfig arg in vcluster cli

### ISSUE THREAD

**Issue by mysiki** [loft-sh/vcluster#1724]
### Is your feature request related to a problem?

Using vcluster cli with kubeconfig file 

### Which solution do you suggest?

Adding option --kubeconfig in vcluster cli arguments

**Comment by FabianKramm** [comment]
@mysiki thanks for creating this issue! You can just use the env var `KUBECONFIG`, why would you want an extra flag for this?

**Comment by mysiki** [comment]
ohhhh !! I missing this information. Thx !
