### ISSUE TITLE
Hostname for statefulset pods FQDN is incorrect in vcluster >= 0.4.1

### ISSUE THREAD

**Issue by moustafab** [loft-sh/vcluster#174]
When deploying a statefulset on k8s `hostname -f` executed inside of a pod should return:
`pod-name-<ordinal>.<serviceName>` where serviceName is defined in Statefulset `spec.serviceName`

Actual behavior:
`hostname -f` returns
`pod-name-<ordinal>`

I believe the regression was added [here](https://github.com/loft-sh/vcluster/pull/135/files#diff-2b6b8762ac2665b29231b876d5d4a0263ffa01674f57c7e072a010c8522e5684R321-R328) when trying to solve for Job name behavior outlined in #131 .

**Comment by LukasGentele** [comment]
@moustafab would you like to contribute a fix for this?

**Comment by moustafab** [comment]
@LukasGentele PR submitted. turns out it was a different part of the same PR that caused the regression.

**Comment by FabianKramm** [comment]
@moustafab thanks a lot, you are correct seems like this slipped through our testing
