### ISSUE TITLE
Deployed etcd storage class name parameter does not match between template and values.yaml

### ISSUE THREAD

**Issue by virtualdxs** [loft-sh/vcluster#1756]
### What happened?

The helm chart's `values.controlPlane.backingStore.etcd.deploy.statefulSet.persistence.volumeClaim.storageClass` is ignored and the default storageClass is used. This seems to be due to https://github.com/loft-sh/vcluster/blob/v0.20.0-beta.2/chart/templates/etcd-statefulset.yaml#L47 referencing `className` rather than `storageClass`.

### What did you expect to happen?

Specifying a storageClass for etcd would work

### How can we reproduce it (as minimally and precisely as possible)?

Deploy with Helm using the following values.yaml:

    controlPlane:
      backingStore:
        etcd:
          deploy:
            enabled: true
            statefulSet:
              persistence:
                volumeClaim:
                  className: rook-cephfs

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.4+k3s2
```

</details>

### Host cluster Kubernetes distribution

<details>

```
k3s
```

</details>

### vlcuster version

<details>
Not using vcluster cli; helm version is `0.20.0-beta.2`
</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

k8s I think; I did not specify and this is on v0.20

</details>

### OS and Arch

<details>

```
OS: Rocky Linux 9
Arch: x86_64
```
</details>

**Comment by joaocc** [comment]
We also have the same issue... in EKS with k3s and etcd it always uses gp2

**Comment by neogopher** [comment]
Hi @virtualdxs :wave: ,
Thanks for creating this issue and @joaocc also for confirming. 

I am looking into this issue and fix is on the way.
