### ISSUE TITLE
vcluster referencing images with vulnerabilities (library/alpine:3.13.1, coredns/coredns:1.10.0)

### ISSUE THREAD

**Issue by joaocc** [loft-sh/vcluster#1764]
### What happened?

Trivy operator reports the use of images with vulnerabilities.
In this case library/alpine:3.13.1 and coredns/coredns:1.11.0

### What did you expect to happen?

Depending on the need to specify an older version, one of these would be better:

* library/alpine:3.13
* library/alpine:3.19
* library/alpine:stable

CoreDNS doesn't provide a Major+Minor version, so in this case a simple upgrade might do the trick:

* [ENG-3849](https://linear.app/loft/issue/ENG-3849/upgrade-to-coredns-1110)

### How can we reproduce it (as minimally and precisely as possible)?

run trivy-operator on any vcluster deployment

### Anything else we need to know?

*No response*

### Host cluster Kubernetes version

N/A

### Host cluster Kubernetes distribution

N/A

### vlcuster version

**v0.20.x**

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

N/A

### OS and Arch

N/A

**Comment by heiko-braun** [comment]
Quick update: The latest images have a fresh alpine base which removes the vulnerabilities. With CoreDNS it's a bit more complicated. It seems the CoreDNS community struggles to release an update version: https://github.com/coredns/coredns/issues/6661
