### ISSUE TITLE
syncLabels option exists in documentation for vcluster 0.20.0 but is missing in helm chart

### ISSUE THREAD

**Issue by antongri** [loft-sh/vcluster#1773]
### What happened?

Based on documentation - https://www.vcluster.com/docs/vcluster/vcluster-yaml#experimental-syncSettings-syncLabels there should be `experimental:syncSettings:syncLabels`  while it does not exist in latest chart https://github.com/loft-sh/vcluster/blob/v0.20.0-beta.5/chart/values.yaml

### What did you expect to happen?

helm chart should have `experimental:syncSettings:syncLabels` option

### How can we reproduce it (as minimally and precisely as possible)?

Check docs at https://www.vcluster.com/docs/vcluster/vcluster-yaml/?x0=2#experimental-syncSettings-syncLabels
Check helm chart values file here https://github.com/loft-sh/vcluster/blob/v0.20.0-beta.5/chart/values.yaml

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
# paste output here
kubectl version
Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.3-eks-adc7111
```

</details>

### Host cluster Kubernetes distribution

<details>

```
EKS v1.29.3
```

</details>

### vlcuster version

<details>

```console
$ vcluster --version
# paste output here
vcluster version 0.20.0-beta.5
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
k3s
```

</details>

### OS and Arch

<details>

```
OS: MacOS
Arch: arm64
```
</details>

**Comment by FabianKramm** [comment]
Hey @antongri ! The option exists, it just has no default value in the `values.yaml`, so you can still use that! I added default values in #1783 to make that more clear.
