### ISSUE TITLE
host and vcluster version upgrades 

### ISSUE THREAD

**Issue by devexter** [loft-sh/vcluster#1870]
### Is your feature request related to a problem?

We have experienced some service downtime when we upgrade AWS EKS clusters.
We are looking at blue/green cluster upgrades as a possible solution, I am looking to see if vCluster could provide a possible solution to this.
Does the vCluster k8s version need to be deployed on the same host k8s version, or does each vCluster k8s version support a range of host k8s versions?

### Which solution do you suggest?

Deploy App clusters as vClusters, do blue/green vCluster upgrades

Upgrade host EKS cluster independently from App vCluster upgrades.

### Which alternative solutions exist?

Stick with EKS blue/green cluster upgrades.

### Additional context

While I think vCluster can make blue/green cluster upgrades faster, if we have to also upgrade the underlying host cluster we have the same issue of potential downtime.

**Comment by heiko-braun** [comment]
Hi @devexter

> Does the vCluster k8s version need to be deployed on the same host k8s version, or does each vCluster k8s version support a range of host k8s versions?

No, usually the k8s are backwards compatible and you can combine different versions on the host and virtual cluster:
https://www.vcluster.com/docs/vcluster/deploy/basics
