### ISSUE TITLE
[bug] image pull secrets on vc synced to host leaving secret name reference in pod spec on host unchanged

### ISSUE THREAD

**Issue by tedli** [loft-sh/vcluster#1912]
### What happened?

1. create a `dockerconfigjson` secret on `vc`;
2. create a pod which image pull secret reference to the secret created above;
3. the synced pod on host cluster also reference to the same secret name which not exist on host cluster;
4. in fact, the secret also synced to host cluster, but with a name in `name-x-namespace-x-vcname` pattern.

### What did you expect to happen?

pod on host use the synced `...-x-...` named secret.

### How can we reproduce it (as minimally and precisely as possible)?

1. create a vc instance;
2. create a dockerconfigjson secret;
3. create a pod using this secret with a private image.

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.0
```

</details>

### vcluster version

<details>

```console
$ vcluster --version
# paste output here
vcluster version 0.19.6
```

</details>

### VCluster Config

<details>

```
# My vcluster.yaml / values.yaml here
```

</details>

**Comment by tedli** [comment]
I found the translate code

```golang
// translate image pull secrets
	for i := range pPod.Spec.ImagePullSecrets {
		pPod.Spec.ImagePullSecrets[i].Name = translate.Default.PhysicalName(pPod.Spec.ImagePullSecrets[i].Name, vPod.Namespace)
	}
```

maybe i miss configed somewhere.

**Comment by FabianKramm** [comment]
@tedli thanks for creating this issue! Its actually expected to create the image pull secret within the vCluster. If you want to assign image pull secrets from the outside to the vCluster workloads, you can configure that in the `vcluster.yaml` / `values.yaml` with:
```
serviceAccount:
  imagePullSecrets:
  - name: my-host-secret
```

**Comment by tedli** [comment]
Hi @FabianKramm ,
Thanks for reply.
It turns out vcluster works as expect. I can't reproduce it again.
