### ISSUE TITLE
Ability to connect to service accounts

### ISSUE THREAD

**Issue by mhaddon** [loft-sh/vcluster#197]
If you create a service account inside of a VCluster you should be able to authenticate to the cluster using the service accounts token.

Unfortunately this does not seem to work, the first problem you get is the service account on the host that is running VCluster stating that it does not have `system:auth-delegator` permissions, and if you give it those permissions it does not seem to be able to validate the token.

It seems like a VCluster only validates itself with SA tokens available on the host.

It would be nice to have a solution to this as it will mean that people can use the vcluster tooling without the cli.

**Comment by mhaddon** [comment]
Ah, i see it might be possible if your ingress goes to port 6443 instead as Kubernetes is listening on that port.

**Comment by FabianKramm** [comment]
@mhaddon it works for me, also this would be super awkward if it wouldn't work as all pods running within the vcluster authenticate through service account tokens with vcluster
