### ISSUE TITLE
List vclusters?

### ISSUE THREAD

**Issue by richburroughs** [loft-sh/vcluster#2]
Hi,

I'm not sure how hard this would be to implement but when I was playing around with vcluster I found myself at one point wishing there was a "vcluster list" subcommand or something similar, so I could see which vclusters existed in my host cluster. I think the scenario was that I had created a vcluster but lost connection to it, and went to connect again later but I didn't remember what I had named it.

**Comment by FabianKramm** [comment]
@richburroughs thanks for opening this issue! Yes I agree, listing the vclusters would be a nice addition, which we should add to the CLI

**Comment by FabianKramm** [comment]
@richburroughs this got implemented with v0.2.0
