### ISSUE TITLE
`vcluster upgrade` potentially downgrades when on beta version

### ISSUE THREAD

**Issue by jannfis** [loft-sh/vcluster#2072]
### What happened?

I was running `v0.20.0-beta.15` and wanting to upgrade to freshly released `v0.20.0`. So I ran `vcluster upgrade`, which eventually downgraded me to `v0.19.7`.

### What did you expect to happen?

I figured that 0.19.7 is still marked stable on the GitHub releases, and 0.20.0 marked as pre-release. So I would have expected the `upgrade` sub-command to skip download/install and to display a message along the lines of "latest stable release is 0.19.7, which is lower than the version you are currently running"

### How can we reproduce it (as minimally and precisely as possible)?

* Install a current beta (pre-release) version
* Run `vcluster upgrade` without any arguments
* See being downgraded to the latest stable release

### Anything else we need to know?

*No response*

### Host cluster Kubernetes version

```console
$ kubectl version
# paste output here
```

</details>

### vcluster version

<details>

```console
$ vcluster --version
vcluster version 0.20.0-beta.15
```

### VCluster Config

```
# My vcluster.yaml / values.yaml here
```

gm

**Comment by jannfis** [comment]
FWIW, now as `v0.20.0` was marked stable, behavior is easily reproducible by:

```
$ vcluster upgrade --version v0.21.0-alpha.4
19:58:10 info Downloading version v0.21.0-alpha.4...
19:58:11 done Successfully updated vcluster to version v0.21.0-alpha.4
$ vcluster upgrade 
19:58:13 info Downloading newest version...
19:58:14 done Successfully updated to version 0.20.0
19:58:14 info Release note: 
```

**Comment by deniseschannon** [comment]
By default, we will always only upgrade to the latest stable version of vcluster. <br><br>We could do a better job of confirming if you want to "downgrade" when you run `vcluster upgrade` without any arguments.

**Comment by jannfis** [comment]
Thanks for your response, @deniseschannon. 

For my part, I would be fine if the `vcluster upgrade` doesn't do anything in this situation (i.e. similar as if there would be no upgrade available). It would imho be more within expectations of an _upgrade_ command.

**Comment by rohantmp** [comment]
fixed in #2072

and improved by #2136

**Comment by reneleonhardt** [comment]
> fixed in #2072
> 
> and improved by #2136
You probably meant the first PR #2131, not this issue 2072 😉

I can't find an example or description if the [reproduce example](#issuecomment-2292101568) is working now 🤔
```shell
# vCluster is installed with any other version (older or newer stable, older or newer unstable)
# Change installed version to requested version (may be an upgrade or downgrade to stable or unstable)
vcluster upgrade --version v0.21.0-alpha.4
# vCluster is running with the requested version
```
Or is still only one direction allowed (downgrading forbidden)?
* upgrade v0.20.0 to v0.21.0-alpha.4
* upgrade v0.21.0-alpha.3 to v0.21.0-alpha.4

**Comment by rohantmp** [comment]
Downgrading was always allowed, and no validation is done when the `--version` flag is used

**Comment by rohantmp** [comment]
Does this address your question?

**Comment by reneleonhardt** [comment]
@jannfis can you upgrade now from pre 0.20.0 to 0.20.0?
@rohantmp can you add build artifacts to allow users to test binaries from PRs if the proposed fix works for them?
