### ISSUE TITLE
[DOC] Need to update the doc on ResourceQuota of vcluster.yaml of v0.20

### ISSUE THREAD

**Issue by gnomeria** [loft-sh/vcluster#2079]
### What happened?

Currently when I tried to use or update the `vcluster.yaml` with resource.quota values based on the [doc](https://www.vcluster.com/docs/vcluster/configure/vcluster-yaml/policies/resource-quota), it will return below error

> error
```
14:07:31 info Upgrade vcluster vcluster-1...
14:07:31 info execute command: helm upgrade vcluster-1 /tmp/vcluster-0.20.0.tgz-3002982672 --create-namespace --kubeconfig /tmp/1293780800 --namespace team-a --install --repository-config='' --values /tmp/3494082263 --values vcluster.yaml
14:07:32 fatal error executing helm upgrade vcluster-1 /tmp/vcluster-0.20.0.tgz-3002982672 --create-namespace --kubeconfig /tmp/1293780800 --namespace team-a --install --repository-config='' --values /tmp/3494082263 --values vcluster.yaml: Error: UPGRADE FAILED: failed to create resource: ResourceQuota "vc-vcluster-1" is invalid: spec.scopeSelector.matchExpressions: Invalid value: core.ScopeSelector{MatchExpressions:[]core.ScopedResourceSelectorRequirement{core.ScopedResourceSelectorRequirement{ScopeName:"PriorityClass", Operator:"In", Values:[]string{"medium"}}}}: unsupported scope applied to resource
```
> vcluster.yaml
```yaml
policies:
  resourceQuota:
    enabled: true
    quota:
      hard:
        cpu: "3"
        memory: 3Gi
        pods: "10"
```
Based on the chart, it should've been without the `hard` level in the yaml:
```
policies:
  resourceQuota:
    enabled: true
    quota:
      cpu: "3"
      memory: 3Gi
      pods: "10"
```

### What did you expect to happen?

Below is the expectation after I adjusted the `vcluster.yaml` to be `policies.resourceQuota.quota`

```
14:07:46 info Upgrade vcluster vcluster-1...
14:07:46 info execute command: helm upgrade vcluster-1 /tmp/vcluster-0.20.0.tgz-3288374014 --create-namespace --kubeconfig /tmp/1123224806 --namespace team-a --install --repository-config='' --values /tmp/1234967584 --values vcluster.yaml
14:07:47 done Successfully created virtual cluster vcluster-1 in namespace team-a
14:07:48 info Waiting for vcluster to come up...
14:08:01 done vCluster is up and running
```

### How can we reproduce it (as minimally and precisely as possible)?

Create a new cluster or upgrade the `vcluster.yaml` from CLI with the content from the doc with `vcluster create vcluster-1 --namespace team-a -f vcluster.yaml`

```yaml
policies:
  resourceQuota:
    enabled: true
    quota:
      hard:
        cpu: "10"
        memory: 20Gi
        pods: "10"
 ```

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.3
```

</details>

### vcluster version

<details>

```console
$ vcluster --version
vcluster version 0.20.0
```

</details>

### VCluster Config

<details>

```
policies:
  resourceQuota:
    enabled: true
    quota:
      hard:
        cpu: "3"
        memory: 3Gi
        pods: "20"
```

</details>

**Comment by gnomeria** [comment]
Also I'm not quite sure where to change the doc since the tag v0.20 docs hasn't been updated for a year and it's still pointing to 0.19 in the `docusaurus.config.js`
https://github.com/loft-sh/vcluster/blob/v0.20/docs/pages/security/quotas-limits.mdx

**Comment by deniseschannon** [comment]
All the vcluster docs have moved to a new GH repo: [https://github.com/loft-sh/vcluster-docs](https://github.com/loft-sh/vcluster-docs). I'll need to think about how to indicate that as this isn't the first time we've had this issue. <br><br>I have made a PR: [https://github.com/loft-sh/vcluster-docs/pull/253/](https://github.com/loft-sh/vcluster-docs/pull/253/) but think that the example is actually slightly different than what you've posted.
