### ISSUE TITLE
How to export a kube config for a vcluster with 0.20.0?

### ISSUE THREAD

**Issue by felipecrs** [loft-sh/vcluster#2085]
With the previous versions, I could use:

```
vcluster connect --kube-config=vcluster-kubeconfig.yaml --update-current=false
```

How to do the same now that both `--kube-config` and `--update-current` is gone?

**Comment by felipecrs** [comment]
I was able to get the kube config with `--print`.

Now, how do I prevent it from changing my current kubeconfig?

**Comment by felipecrs** [comment]
The only workaround I found was ugly:

```bash
kubeconfig_backup=$(cat "${KUBECONFIG}")

vcluster connect --print | tee vcluster-kubeconfig.yaml

echo "${kubeconfig_backup}" | tee "${KUBECONFIG}"
```

**Comment by FabianKramm** [comment]
@felipecrs thanks for creating this issue! Are you sure vCluster is updating the current KubeConfig? When using print it shouldn't update the current kube config anymore, thats why the flag is not needed. Just do:
```
vcluster connect ... --print > my-kubeconfig.yaml
```

**Comment by felipecrs** [comment]
You are totally right, my bad. Thanks a lot.
