### ISSUE TITLE
default distribution is k8s, not k3s

### ISSUE THREAD

**Issue by dimbleby** [loft-sh/vcluster#2095]
### What happened?

The docs claim that the default distribution used is k3s.  But it isn't, it is k8s.

### What did you expect to happen?

I expected the docs and the behaviour to agree

### How can we reproduce it (as minimally and precisely as possible)?

`vcluster create test-cluster`

### Anything else we need to know?

docs https://github.com/loft-sh/vcluster/blob/29efe2556088d63008a297de10cc480718c947d3/docs/pages/deploying-vclusters/supported-distros.mdx#L6

default https://github.com/loft-sh/vcluster/blob/29efe2556088d63008a297de10cc480718c947d3/chart/templates/_distro.tpl#L29

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### vcluster version

<details>

```console
$ vcluster --version
# paste output here
```

</details>

### VCluster Config

<details>

```
# My vcluster.yaml / values.yaml here
```

</details>

**Comment by FabianKramm** [comment]
@dimbleby thanks for creating this issue! The docs that are part of the repo are the old docs, if you go to [vcluster.com/docs](https://vcluster.com/docs) you'll end up at the new docs, which are located in the [github.com/loft-sh/vcluster-docs](https://github.com/loft-sh/vcluster-docs) repository and it looks correct there.

**Comment by dimbleby** [comment]
I see, thanks

for what it's worth I have spent the last five minutes looking and failed to find where that newer discussion of distributions is published.  Probably it's there somewhere?

and obviously it's confusing for this repository to be carrying the baggage of stale docs

but if the k8s default is indeed intended: well that answers my question, thank you.  Feel free to close this out: or, if you prefer, to keep it to track cleaning up.
