### ISSUE TITLE
Add the ability to specify service account and cluster role in exportKubeConfig

### ISSUE THREAD

**Issue by ben-z** [loft-sh/vcluster#2141]
### Is your feature request related to a problem?

I'm working in an environment that does not support ingress ssl-passthrough, and I'm trying to keep everything in Terraform using the Helm chart. However, there does not appear to be a way to export a kubeconfig equivalent to:
```bash
vcluster connect <name> --server=<server> --service-account admin --cluster-role cluster-admin --print
```

The current `exportKubeConfig` seems to be equivalent to the above command without `--service-account` and `--cluster-role`.

### Which solution do you suggest?

Can we add options to `exportKubeConfig` so that we can specify the service account and cluster role?

### Which alternative solutions exist?

Using the CLI instead of Terraform+Helm. Though this is more difficult to automate and use in infrastructure-as-code.

**Comment by FabianKramm** [comment]
@ben-z thanks for creating this issue! I think this is a great idea, will start working on this.
