### ISSUE TITLE
sync.toHost.pods.enforceTolerations.0: Invalid type. Expected: string, given: object

### ISSUE THREAD

**Issue by wutz** [loft-sh/vcluster#2199]
Create a new vcluster by https://vcluster.com/docs/vcluster/configure/vcluster-yaml/sync/to-host/core/pods#automatically-apply-tolerations-to-all-pods-synced-by-vcluster

but got 

```bash
Error: values don't meet the specifications of the schema(s) in the following chart(s):
vcluster:
- sync.toHost.pods.enforceTolerations.0: Invalid type. Expected: string, given: object
```

It should be a problem with the type definition.

https://github.com/loft-sh/vcluster/blob/58005894621ecb17166c38f5f8f913678e9408cc/chart/values.schema.json#L2743-L2749

**Comment by wutz** [comment]
The current workaround method is to pass the parameter --skip-schema-validation (Helm version 3.16.0 or higher).

**Comment by wutz** [comment]
According to the code description https://github.com/loft-sh/vcluster/blob/v0.20.1/pkg/util/toleration/toleration.go#L11, the document description should be incorrect.

**Comment by lucasfcnunes** [comment]
I was having this problem. This unfortunately is not in the docs.

My case is for any effect so:
```
sync:
  toHost:
    pods:
      enabled: true
      enforceTolerations:
        - "example-key=example-value"
```

**Comment by lucasfcnunes** [comment]
@wutz I created a PR to make it explicit https://github.com/loft-sh/vcluster-docs/pull/293, please take a look.

I not sure if the case when the operation is `Exists` (any value) works as `another-key:PreferNoSchedule`. Do you think it works?

## References

- https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#taint
![image](https://github.com/user-attachments/assets/a2a5fca6-7c1c-41b5-873a-9666a6213a8a)

**Comment by wutz** [comment]
It will work; I have tested the configuration `nvidia.com/gpu:NoSchedule` in the environment and it works fine.
