### ISSUE TITLE
sign vCluster binaries/images with cosign 

### ISSUE THREAD

**Issue by developer-guy** [loft-sh/vcluster#220]
Let's sign vCluster binaries with cosign, and make them verifiable for the end-users by providing clear text on the releases page about how they can do it. AFAIK, vCluster uses GitHub Actions to make a new release, so, it is easy to integrate the signing process into the workflow because there is already GitHub action for installing cosign. 

But, the question is should we consider using keyless mode or using public/private key pairs while signing binaries/images?

* https://chainguard.dev/posts/2021-12-01-zero-friction-keyless-signing
* https://github.com/sigstore/cosign-installer
cc: @Dentrax 

To complete the issue, the followings need to be done:

- [x] ~~sign container images~~
- [x] ~~sign binaries, maybe sha256 file only~~

**Comment by FabianKramm** [comment]
@developer-guy thanks for creating this issue! Sure, we can add this if its non invasive for our pipeline or the end user of the vcluster image

**Comment by developer-guy** [comment]
would you mind assigning to @Dentrax? We can handle this with @Dentrax together.

**Comment by FabianKramm** [comment]
@developer-guy I think he needs to comment on this issue first before I can assign him

**Comment by richburroughs** [comment]
@developer-guy @Dentrax This is a super cool idea, and thanks for stepping up to do it :)

**Comment by richburroughs** [comment]
@developer-guy @Dentrax Are you all still interested in working on this? :)

**Comment by developer-guy** [comment]
Ah yes of course ✌️ thank you for bringing it to my attention, I'm going to complete it soon😇

**Comment by developer-guy** [comment]
kindly ping @richburroughs 🙋🏻‍♂️

**Comment by richburroughs** [comment]
Hi cool :) I'm not the person who will approve or merge this but thank you!
