### ISSUE TITLE
Findings from v0.5.0-beta.0

### ISSUE THREAD

**Issue by olljanat** [loft-sh/vcluster#253]
I'm actively testing `v0.5.0-beta.0` now so it probably easiest to collect all new findings under one issue and others comment them here too.
1. Image versions on `vcluster` and helm charts are not in sync. New k8s cluster deployment uses K8s `v1.22.4` and etcd `3.5.1-0` but helm chart https://github.com/loft-sh/vcluster/blob/main/charts/k8s/values.yaml uses K8s `v1.21.5` and etcd `3.4.13-0`. That why my upgrade attempt from `v0.5.0-alpha.7` to  `v0.5.0-beta.0` failed as etcd does not support downgrade.

**Comment by FabianKramm** [comment]
@olljanat thanks for the issue! You created the vcluster via the CLI and upgraded it via helm correct? You'll need to use the `--reuse-values` option with helm or use `vcluster create --upgrade` instead to preserve the automatically provided values from `vcluster create`.

**Comment by olljanat** [comment]
Ah, I got confused that `vcluster upgrade` update only CLI and totally missed `vcluster create --upgrade` option so yes I did upgrade with helm. However chart upgrade worked fine too after including image versions to it manually.
