### ISSUE TITLE
Change HostRewrite Image

### ISSUE THREAD

**Issue by zachaller** [loft-sh/vcluster#26]
With docker hubs pull rate limits having a hard coded image tag becomes an issue on larger deployments where we constantly can not pull from docker hub such as [https://github.com/loft-sh/vcluster/blob/main/pkg/controllers/resources/pods/translate.go#L31](https://github.com/loft-sh/vcluster/blob/main/pkg/controllers/resources/pods/translate.go#L31) having this be a configuruable field so that we can properly proxy the image I think makes sense.

**Comment by FabianKramm** [comment]
@zachaller thanks for creating this issue! Thats actually possible right now already as you can use the following helm values:
```yaml
syncer:
  extraArgs: ["--override-hosts-container-image", "myregistry.com/namespace/alpine:3.13.1"]
```

Besides that vcluster supports rewriting any image via the flag `--translate-image`:
```yaml
syncer:
  extraArgs: ["--translate-image", "nginx=myregistry.com/namespace/nginx"]
```

**Comment by matskiv** [comment]
The question has been answered with no follow up questions - closing.
