### ISSUE TITLE
Landing page doesn't instruct user to install Helm

### ISSUE THREAD

**Issue by saidmasoud** [loft-sh/vcluster#260]
After trying to run `vcluster` for the first time on a fresh cluster by following the instructions on the landing page ([https://www.vcluster.com](https://www.vcluster.com)), the CLI exits and instructs the user to install Helm. It would be ideal to add a note to your landing page recommending users to install Helm before finding out the "hard" way. It's also a nice and subtle way to notify your users that Helm is required, should that make a difference to them in determining whether to adopt vcluster or not.

```
$ vcluster create vcluster-test -n vcluster-test
[fatal]  seems like helm is not installed. Helm is required for the creation of a virtual cluster. Please visit https://helm.sh/docs/intro/install/ for install instructions
```

**Comment by FabianKramm** [comment]
@saidmasoud thanks for creating this issue! We try to keep the quickstart on the landing page very short and assume helm is already installed as well as a Kubernetes cluster is installed and reachable. We could add this note to the docs though as these should cover everything in more detail

**Comment by matskiv** [comment]
vcluster CLI can now download helm binary automatically if it doesn't find it - #730
