### ISSUE TITLE
vcluster controller should wait on api

### ISSUE THREAD

**Issue by FabianKramm** [loft-sh/vcluster#276]
Currently the vcluster controller starts without waiting for vcluster itself to be ready, which often leads to pods initially failing. It would be better to wait until the api server is reachable before actually starting to sync.

**Comment by neogopher** [comment]
Hi @FabianKramm ,

Does this behaviour occur in specific scenarios only or in general. I tried it at my end, but wasn't able to replicate this observation. Would like to give this a try.

**Comment by FabianKramm** [comment]
Hey @neogopher ! This is actually fixed already, hence I'll close this!
