### ISSUE TITLE
Support custom coredns config

### ISSUE THREAD

**Issue by chrisjohnson** [loft-sh/vcluster#286]
k3s recently added support for custom coredns config: https://github.com/k3s-io/k3s/pull/4397

I see 0.5.0 changes to use vcluster-provisioned coredns. Can we copy the same shim for injecting custom server definitions into vcluster's tool? We need this to resolve on-prem domains from our clusters

**Comment by chrisjohnson** [comment]
I started this PR https://github.com/loft-sh/vcluster/pull/287 but I honestly don't know what I'm doing as far as any sort of testing goes. Would anybody care to ride along with me and show me how to get this change over the line?

**Comment by matskiv** [comment]
@chrisjohnson Thank you for submitting the PR! It seems like it should work, we can merge it after some testing.
The default scenario, where there is no customization, should be covered by our e2e tests. We updated our GitHub actions triggers to run e2e tests on the PRs that change something within `manifests/`. Could you please rebase your PR to trigger those tests?

As for testing a scenario with the `coredns-custom` ConfigMap, you will need to get the updated manifest into the syncer image, for which there are at least these two ways:
a) Building the image locally and pushing it to a repo that can be accessed from the cluster where vcluster is deployed (basically `docker build -t REPO:TAG .` + `docker push REPO:TAG`), and then using the built image in the vcluster's syncer container.
b) Follow [our guide for local development](https://github.com/loft-sh/vcluster/blob/main/CONTRIBUTING.md#setup-vcluster-for-development) and changes to `manifests/` will be present in the dev container.
Once the updated coredns deployment is running, and `coredns-custom` ConfigMap, I would run some DNS queries to exercise custom rules. I usually drop a dnsutils pod into the vcluster (`kubectl apply -f https://k8s.io/examples/admin/dns/dnsutils.yaml` - it's [from here](https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/#create-a-simple-pod-to-use-as-a-test-environment)), and run nslookup via that pod (e.g. `kubectl exec -i -t dnsutils -- nslookup kubernetes.default`). Then, depending on your custom rules, you should be able to detect if it's being hit (based on the logs in coredns pod or server reply).

Please let us know if you were successful with the testing. :) 
I am also more than happy to help out with the testing or with the local dev setup, so I'll reply on your Slack thread, and we can chat there if needed.

**Comment by matskiv** [comment]
@chrisjohnson Can we close this issue if the scope of customization that you implemented in #287 is sufficient for your use case?
If not, and you would like to make more extensive customizations of the CoreDNS deployment and config we can discuss that here. :)

**Comment by chrisjohnson** [comment]
We are working to get a custom vcluster build deployed into our working environment to confirm this solves our use case and then yes I will close this issue out

**Comment by chrisjohnson** [comment]
All good, it works for us!
