### ISSUE TITLE
feat: vcluster --version

### ISSUE THREAD

**Issue by LukasGentele** [loft-sh/vcluster#3]
Would be good to be able to check the CLI version and potentially also useful to include a command or --server flag for the server side version of a vcluster

**Comment by FabianKramm** [comment]
Yes we can add a version flag, regarding the server version: this is quite difficult as you would need to somehow select which vcluster should be targeted. I guess this would be better displayed in the `list` command as proposed here #2

**Comment by Ab-hishek** [comment]
Can we not add a specific command such as: `vcluster [vcluster_name] --version`? Following the convention: `APPNAME VERB NOUN --ADJECTIVE`. or `APPNAME COMMAND ARG --FLAG`. Now, here since verb is not required, we can have the command structure as stated at the start.

**Comment by Joibel** [comment]
'vcluster --version' for the CLI version already exists. I'd say it was confusing to have the other syntax, and 'vcluster list' or 'vcluster info <clustername>' could do the job instead.

**Comment by matskiv** [comment]
We decided to not implement this for now. Please comment if you feel like we should reconsider.
