### ISSUE TITLE
where to set imagePullSecret for vcluster images

### ISSUE THREAD

**Issue by Wompipomp** [loft-sh/vcluster#333]
Hello,

this is more a question: Is there any possibility to use an imagePullSecret for the vcluster images e.g., when pulling the images from a private registry for air-gapped clusters or pulling from docker with an account due to the docker restrictions. I have seen the possibility to set a `defaultImageRegistry` but haven't found any option to set an imagePullSecret.

Thank you very much
Mark

**Comment by matskiv** [comment]
Hello @Wompipomp 

You can set the pull secret for vcluster ServiceAccount and it will be used to pull all images used in the vcluster StatefulSet.
You do this via values.yaml file that you pass to `vcluster create -f values.yaml` or `helm upgrade --values values.yaml`:
```
serviceAccount:
  imagePullSecrets:
    - name: secret-name-here
```

This works for the default k3s flavor, and k0s, but not k8s. 
And it doesn't cover the CoreDNS pod.
