### ISSUE TITLE
Nginx BasicAuth secret not synchronized

### ISSUE THREAD

**Issue by hxtmdev** [loft-sh/vcluster#351]
vcluster 0.5.3 does not appear to synchronize [nginx.ingress.kubernetes.io/auth-secret secrets](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#authentication).

This annotation is of course specific to the nginx ingress controller. Is this still wanted in core, or rather something for a plugin?

**Comment by FabianKramm** [comment]
@hxtmdev thanks for creating this issue! Yes this secret wouldn't get synchronized currently. I'm not sure if we should add this to the core as this seems vendor specific and there might be a lot of other annotations that are similar. Is installing the ingress controller inside the vcluster an option for you?

**Comment by hxtmdev** [comment]
I could try an ingress controller inside the vcluster and a forwarding ingress outside, or a custom plugin. My current workaround while I figure out the ideal solution is separately creating the secret outside the vcluster.

I suspect that attempting to generalize this into some sort of pattern solution would likely end up in a hacky mess.

If you think this would be too vendor-specific for the core just close this. If/when anyone writes a suitable plugin they can just comment it here.

**Comment by martinnirtl** [comment]
Hi @FabianKramm!
what about introducing a vcluster-specific annotation that explicitly tells the syncer to sync the respective secret?

**Comment by FabianKramm** [comment]
@hxtmdev @martinnirtl the ingress annotations should now get automatically rewritten with the new v0.8.0-alpha.3 vcluster release
