### ISSUE TITLE
k3s Helm template for statefulset: volumes indentation

### ISSUE THREAD

**Issue by julienlefur** [loft-sh/vcluster#359]
The correct indentation should be 6 here and not 8.  This is causing a problem when deploying a vcluster with k3s with extra volumes:

https://github.com/loft-sh/vcluster/blob/159f3ed76be6bb6f288683e3e705a000ae429e8a/charts/k3s/templates/statefulset.yaml#L61

**Comment by FabianKramm** [comment]
@julienlefur thanks for reporting this issue! Yes you are correct, this only occurs though if you set `persistence.enabled: false` in the values.yaml as well. We'll fix this

**Comment by FabianKramm** [comment]
@julienlefur closing as this should be fixed
