### ISSUE TITLE
vcluster list does not list virtual clusters not created by vcluster create

### ISSUE THREAD

**Issue by danielhelfand** [loft-sh/vcluster#364]
From the docs, deploying virtual clusters can be done as follows using kubectl:

```
kubectl create namespace host-namespace-1
helm template my-vcluster vcluster --repo https://charts.loft.sh --set serviceCIDR=10.96.0.0/12 -n host-namespace-1 | kubectl apply -f -
```

When doing a `vcluster list` after running the commands above, no virtual clusters are shown:

```
 NAME   NAMESPACE   CREATED   AGE
 No entries found
```

**Comment by FabianKramm** [comment]
@danielhelfand thanks for creating this issue! `vcluster list` searches for the helm secret that was created when installing vcluster through the CLI or helm, but you are correct vcluster's are not shown if they were deployed with kubectl. I guess we could go the same route as `vcluster connect` does and search for pods that have the vcluster labels set, however using `vcluster delete` with a non helm deployed vcluster is pretty hard to do as we do not have information about what actually belongs to the vcluster if the helm state is not there.

**Comment by danielhelfand** [comment]
For reference, my use case is using [Carvel](https://carvel.dev/) to deploy vclusters in a more declarative fashion with [kapp-controller](https://carvel.dev/kapp-controller/). So I would just use helm for templating but deploy with a tool called [kapp](https://carvel.dev/kapp/) through the API [here](https://carvel.dev/kapp-controller/docs/latest/packaging/). 

Since there is such a strong tie to helm though, maybe exploring ArgoCD or FluxCD would fit better with this model of more declarative  approach to provisioning vclusters. 

If you don't mind sharing, what kind of vcluster information is stored the helm state?
