### ISSUE TITLE
Docker hub image for 0.6.0 is missing (not an actual bug)

### ISSUE THREAD

**Issue by kotaner** [loft-sh/vcluster#376]
### What happened?

Latest image available : loftsh/vcluster:0.6.0-alpha.8.

Helm chart pointing to following image for syncer : 
```
     - name: syncer
        {{- if .Values.syncer.image }}
        image: "{{ .Values.defaultImageRegistry }}{{ .Values.syncer.image }}"
        {{- else }}
        image: "{{ .Values.defaultImageRegistry }}loftsh/vcluster:{{ .Chart.Version }}"
```

For 0.6.0 release it should look for loftsh/vcluster:0.6.0, but image is not built yet.

### What did you expect to happen?

Having this image built & stored on docker hub : loftsh/vcluster:0.6.0

### How can we reproduce it (as minimally and precisely as possible)?

docker pull loftsh/vcluster:0.6.0

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>
Not relevant

### Host cluster Kubernetes distribution

<details>

```
# Write here
```

</details>
Not relevant

### vlcuster version

Not relevant

<details>

```console
$ vcluster --version
# paste output here
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
# Write here
```

</details>

### OS and Arch

Not relevant

<details>
```
OS: 
Arch:
```
</details>

**Comment by FabianKramm** [comment]
@kotaner thanks for creating this issue! Not sure if understand this correctly, but the vcluster v0.6.0 is available in docker hub at https://hub.docker.com/layers/loftsh/vcluster/0.6.0/images/sha256-a81bf1b50d702cefc80f225ceb87c8fe93cc473c9de5fc182ab3b838381794cd?context=explore . You probably need to upgrade your vcluster cli to v0.6.0
