### ISSUE TITLE
Aliases for list/delete commands

### ISSUE THREAD

**Issue by danielhelfand** [loft-sh/vcluster#389]
### Is your feature request related to a problem?

This request is not a problem. More of a convenience suggestion.

It would be nice to have the list/delete commands with the vcluster CLI have shorthand aliases (i.e. ls, rm). So I can run vcluster ls and vcluster rm as opposed to vcluster list and vcluster delete.

### Which solution do you suggest?

Using Cobra Aliases like [here](https://github.com/danielhelfand/vcluster/commit/0674e5439460188b44e565b645cee08b0091adac).

### Which alternative solutions exist?

I could alias the commands myself, but I hope these are pretty command shorthands for each subcommand that they would be familiar to most.

### Additional context

Depending on whether this is something that should be supported in the CLI, it might be useful to define standards around what aliases would be allowed moving forward.

**Comment by FabianKramm** [comment]
@danielhelfand can you not define something like `alias vcd=vcluster delete` and `alias vcl=vcluster list` in your bash to make this even shorter if you use it a lot?
