### ISSUE TITLE
vcluster connect lost connection to pod

### ISSUE THREAD

**Issue by lklkxcxc** [loft-sh/vcluster#39]
vcluster connect after some time, the connection is automatically lost
```
[root@kube-master-01 vcluster]# vcluster connect vcluster-1 -n host-namespace-1
[done] √ Virtual cluster kube config written to: ./kubeconfig.yaml. You can access the cluster via `kubectl --kubeconfig ./kubeconfig.yaml get namespaces`
[info]   Starting port forwarding: kubectl port-forward --namespace host-namespace-1 vcluster-1-0 8443:8443
Forwarding from 127.0.0.1:8443 -> 8443
Forwarding from [::1]:8443 -> 8443
Handling connection for 8443
Handling connection for 8443
Handling connection for 8443
Handling connection for 8443
Handling connection for 8443
Handling connection for 8443
Handling connection for 8443
Handling connection for 8443
Handling connection for 8443
Handling connection for 8443
Handling connection for 8443
Handling connection for 8443
Handling connection for 8443
Handling connection for 8443
Handling connection for 8443
E0602 15:24:40.949886   31681 portforward.go:233] lost connection to pod
```

**Comment by FabianKramm** [comment]
@lklkxcxc thanks for opening this issue! This can have several reasons:
- The vcluster statefulset pod for some reason restarts or is deleted
- The host cluster is terminating the connection after inactivity
- Your internet connection locally is interrupted

In general `vcluster connect` is only a way to easily access a vcluster, but if you want a persistent way to access it, we strongly recommend exposing it through an ingress, LoadBalancer or NodePort service. You can find a guide how to do this in the [vcluster docs](https://www.vcluster.com/docs/operator/external-access)
