### ISSUE TITLE
couldn't retrieve virtual cluster version

### ISSUE THREAD

**Issue by Chakravarti-Baratam** [loft-sh/vcluster#396]
vcluster create my-vcluster -n my-vcluster

vcluster is not created.
Below logs are found in syncer.

default ServiceAccount is not available yet, will retry in 1 seconds
couldn't retrieve virtual cluster version (Get "[https://127.0.0.1:6444/version](https://127.0.0.1:6444/version)": dial tcp 127.0.0.1:6444: connect: connection refused), will retry in 1 seconds

any help is appreciated.

**Comment by FabianKramm** [comment]
@Chakravarti-Baratam thanks for creating this issue! This usually means the vcluster container in the pod couldn't start up correctly, what are the logs of the vcluster container? Any indication there why it cannot start up? You can also try out another distro that may work better in your environment with:
```
vcluster create ... --distro k0s
```

**Comment by Chakravarti-Baratam** [comment]
goroutine 4006 [chan receive, 1 minutes]:
k8s.io/apiserver/pkg/storage/etcd3.(*watchChan).startWatching(0xc00c0ae000, 0xc00c08e180)
	/go/src/gittime="2022-03-08T15:05:02.823860944Z" level=error msg="error while range on /registry/health : database is locked"

**Comment by Chakravarti-Baratam** [comment]
I added logs from vcluster container in previous comment.

**Comment by FabianKramm** [comment]
@Chakravarti-Baratam it seems like k3s cannot access the underlying data storage which is a typical problem if you are using not supported storage types. Does the same problem occur if you use k0s as a distribution?

**Comment by Chakravarti-Baratam** [comment]
If we use k0s or k8s, this problem is not occurring. 
Can you let me know the supported storage types for k3s?

**Comment by FabianKramm** [comment]
@Chakravarti-Baratam thanks for the info! We are not exactly sure why certain storage types don't work with k3s, you'll probably ask in their repo for more technical details on that.
