### ISSUE TITLE
vCluster elements stuck in terminate state

### ISSUE THREAD

**Issue by harish0619** [loft-sh/vcluster#40]
After firing the vcluster delete command, i observe the pods are in terminating state.

\*\*root@PoCVM-F5:\~# kubectl get all -n host-namespace-1
NAME                                                      READY   STATUS        RESTARTS   AGE
pod/coredns-854c77959c-79tqj-x-kube-system-x-vcluster-1   0/1     Terminating   1          6d3h
pod/vcluster-1-0                                          0/2     Terminating   2          6d3h

root@PoCVM-F5:\~# kubectl get all -n host-namespace-2
NAME                                                      READY   STATUS        RESTARTS   AGE
pod/coredns-854c77959c-rn8q8-x-kube-system-x-vcluster-1   0/1     Terminating   0          3h12m
pod/vcluster-1-0                                          0/2     Terminating   0          3h12m
root@PoCVM-F5:\~#\*\*

Although the pvc show a different status in different ns

**root@PoCVM-F5:\~# kubectl get pvc -n host-namespace-1
NAME                STATUS        VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-vcluster-1-0   Terminating   pvc-36006bd9-e74b-41e7-a09f-f17f2d10c9e6   5Gi        RWO            standard       6d3h
root@PoCVM-F5:\~#
root@PoCVM-F5:\~#
root@PoCVM-F5:\~#
root@PoCVM-F5:\~# kubectl get pvc -n host-namespace-2
NAME                STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-vcluster-1-0   Bound    pvc-2c26ad14-1727-45db-8928-ce6b9f984ac3   5Gi        RWO            standard       3h12m**

**Comment by FabianKramm** [comment]
@harish0619 thanks for creating this issue! Which vcluster cli version are you using (you can check via `vcluster --version`)?

**Comment by harish0619** [comment]
I can tell you the version which is 0.2.0. However, the output of delete command I might not be able to provide, since the terminal session was logged out. Since I was able to delete the cluster before without any problem, the output for the command was pretty much the same as it used to be before. Not sure if this helps.

**Comment by FabianKramm** [comment]
@harish0619 I see, vcluster is only deleting the PVCs from version `v0.3.0-beta.0` and upwards, so this seems like the problem

**Comment by harish0619** [comment]
@FabianKramm Ok, I will try to work with the beta version. Thanks for your response!

**Comment by matskiv** [comment]
This is quite an old issue with no reports of further problems, so I presume this was resolved. Please comment or open a new issue if you experience this problem.
