### ISSUE TITLE
Add a homebrew method of installation for vcluster

### ISSUE THREAD

**Issue by remyleone** [loft-sh/vcluster#402]
### Is your feature request related to a problem?

Yes I would like to install and maintain vcluster using only homebrew like all my other packages on macos

### Which solution do you suggest?

Having either a tap in your organization or send vcluster on the main homebrew repository

### Which alternative solutions exist?

Install manually. The problem is that I would like to receive updates using my package manager

**Comment by FabianKramm** [comment]
@remyleone thanks for creating this issue! Yes I agree we can add vcluster to homebrew for easier installation

**Comment by LukasGentele** [comment]
If anyone wants to contribute the homebrew formular for vcluster, have a look at how it has been done for devspace: https://github.com/Homebrew/homebrew-core/blob/master/Formula/devspace.rb

Should be pretty similar to devspace since we're using the same cli framework etc. for vcluster and devspace

**Comment by pratikjagrut** [comment]
PR to add vcluster formula https://github.com/Homebrew/homebrew-core/pull/99552

**Comment by pratikjagrut** [comment]
@remyleone You should be able to install the vcluster using brew now.
```
brew update
brew upgrade
brew install vcluster
```
