### ISSUE TITLE
StorageClass not sync to vcluster after enable storageclasses sync

### ISSUE THREAD

**Issue by moyuduo** [loft-sh/vcluster#405]
### What happened?

I'm follow the guide [here](https://www.vcluster.com/docs/architecture/storage) and use vcluster-v0.7.0-alpha.2 to create vcluster. but after vcluster up, i use command `kubectl get sc` just get `No resources found` and i am sure my host cluster has storageclass. 
Why host cluster storage not sync to vcluster?
detail:
```shell
cat enable-sc-pvc.yaml
sync:
  persistentvolumes:
    enabled: true
  storageclasses:
    enabled: true

vcluster-v0.7.0-alpha.2 create enable-pvc -n enable-pvc -f enable-sc-pvc.yaml

vcluster connect enable-pvc --namespace enable-pvc

[root@centos72 enable-pvc]# export KUBECONFIG=./kubeconfig.yaml 
[root@centos72 enable-pvc]# k get node
NAME          STATUS   ROLES    AGE   VERSION
worker-s002   Ready    <none>   46s   v1.21.9+k3s1
[root@centos72 enable-pvc]# k get sc
No resources found
```

### What did you expect to happen?

storeageclass are synced from host cluster to vcluster

### How can we reproduce it (as minimally and precisely as possible)?

is this a bug?

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Host cluster Kubernetes distribution

<details>

```
# Write here
```

</details>

### vlcuster version

<details>

```console
$ vcluster --version
# paste output here
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
# Write here
```

</details>

### OS and Arch

<details>

```
OS: 
Arch:
```
</details>

**Comment by FabianKramm** [comment]
@moyuduo thanks for creating this issue! That is actually working as intended as with storage classes sync vcluster expects you to create the storage classes inside the virtual cluster instead

**Comment by moyuduo** [comment]
@FabianKramm Ok, i remember in version 0.6.0 enable storage sync will sync all host storage class to vcluster, in new version 0.7.0  will only sync vcluster storageclass to host cluster and replace the old strategy?

**Comment by FabianKramm** [comment]
@moyuduo yes exactly we changed this behaviour as its closer to the original Kubernetes behaviour where you can define your own storage classes and default ones inside the virtual cluster without knowing about the host cluster resources.
