### ISSUE TITLE
resource quota are not strict

### ISSUE THREAD

**Issue by moyuduo** [loft-sh/vcluster#406]
### What happened?

I note vcluster-v0.7.0-alpha.2 has support vcluster resource limit, but just resourcequota just restrict requests not  restrict limits, i think this way is like no strict.
```shell
# Source: vcluster/templates/resourcequota.yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name:  vcluster005-quota
spec:
  hard:
    cpu: "10"
    memory: "20Gi"
    pods: "10"
---
# Source: vcluster/templates/limitrange.yaml
apiVersion: v1
kind: LimitRange
metadata:
  name: vcluster005-limit-range
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: "1"
    defaultRequest:
      memory: 128Mi
      cpu: "100m"
    type: Container
```
Even if restrict limits in resource quota, the limitrange will soon reach limits define in resourcequota and there is no strict to storage.
Is there a better way to do resource limit in vcluster?

### What did you expect to happen?

X

### How can we reproduce it (as minimally and precisely as possible)?

X

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Host cluster Kubernetes distribution

<details>

```
# Write here
```

</details>

### vlcuster version

<details>

```console
$ vcluster --version
# paste output here
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
# Write here
```

</details>

### OS and Arch

<details>

```
OS: 
Arch:
```
</details>

**Comment by FabianKramm** [comment]
@moyuduo thanks for the issue! Yes you are correct, we'll add this by default, however you could define those yourself with a `values.yaml`:
```
isolation:
  enabled: true

  resourceQuota:
    quota:
      limits.cpu: 10
      ...
```
then create the vcluster with `vcluster create ... -f values.yaml`

**Comment by FabianKramm** [comment]
@moyuduo should be fixed with vcluster v0.7.0-beta.1

**Comment by moyuduo** [comment]
@FabianKramm In version 0.7.0-alpha.2 will auto deploy resource limit to limit the namespace vcluster deploy to.
```shell
isolation:
  enabled: false

  podSecurityStandard: baseline

  resourceQuota:
    enabled: true
    quota:
      cpu: 10
      memory: 20Gi
      pods: 10
    scopeSelector:
      matchExpressions:
    scopes:
  
  limitRange:
    enabled: true
    default:
      memory: 512Mi
      cpu: "1"
    defaultRequest:
      memory: 128Mi
      cpu: 100m
```
When using a resource quota to limit namespace, all pod deploy must declare resouces in yaml, though we can use limitrange to do so, but just like limitrange declare above, the resource.limits.cpu is very large, and our work pod like `pod/vcluster001-0 pod/coredns-79dddc678b-8qllk-x-kube-system-x-vcluster001` consume more than 2 limtis cpu, if we declare resourcequota max cpu is 4, like limitrange declare above user deploy pod than no declare resouce and will auto filled resources.limit.cpu=1, so that it's very easy to reach max cpu declare in resourcequota. though i know i can adjust limit range when create vcluster, but i think if i use defaultRequest.cpu close to default.cpu it's unfriendly to user pod if they not declare resource in yaml, it's very difficulty to declare limitrange. it's not a good way to do so.

**Comment by FabianKramm** [comment]
@moyuduo not sure if I understand you correctly, but whats the solution that you propose here? I admit LimitRanges are not ideal, but if you have a specific requirement for a pod, you can either set the resources manually or they'll be set from the limit range automatically.
