### ISSUE TITLE
wrong version of Kubernetes deployed when k8s distro set

### ISSUE THREAD

**Issue by danamzulescu-codefresh-csdpdemo** [loft-sh/vcluster#414]
### What happened?

The command I used:

vcluster create --kubernetes-version v1.21.8 vcluster-1 -n host-namespace-1 --distro k8s

The version I got:

Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

### What did you expect to happen?

Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.**8**", 

### How can we reproduce it (as minimally and precisely as possible)?

command I used above

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Host cluster Kubernetes distribution

<details>

```
# Write here
```

</details>

### vlcuster version

<details>

```console
$ vcluster --version
# paste output here
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
# Write here
```

</details>

### OS and Arch

<details>

```
OS: 
Arch:
```
</details>

**Comment by FabianKramm** [comment]
@danamzulescu-codefresh-csdpdemo thanks for creating this issue! Currently we don't support setting the fix version of Kubernetes via the `--kubernetes-version` flag as it would be too much effort for us to maintain for all distros. If you want to use a specific image version, you can define this via a `values.yaml` and apply it via `vcluster create ... -f values.yaml`:
```yaml
etcd:
  image: ...

controller:
  image: ...

api:
  image: ...
```

Just select the correct image version you want and then start up the vcluster.

**Comment by richburroughs** [comment]
@danamzulescu-codefresh-csdpdemo Ah yeah, when we talked I didn't catch that in the CLI's help but it does mention not supporting patch versions.

`     --kubernetes-version string   The kubernetes version to use (e.g. v1.20). Patch versions are not supported`

@FabianKramm Just so I understand, if you say v1.25 it will grab the latest one?

**Comment by FabianKramm** [comment]
@richburroughs it will grab the one we have defined, which is not necessarily the latest one, but the latest one we have tested and confirmed working for vcluster

**Comment by LukasGentele** [comment]
I think we should definitely print a warning if the patch part is provided. Potentially even a fatal since someone is using something that is not supported. This would immediately clarify things.

**Comment by richburroughs** [comment]
Agreed that it could use some clarity. I missed that message in the help myself at first.
