### ISSUE TITLE
ability to set isolation namespace

### ISSUE THREAD

**Issue by mhaddon** [loft-sh/vcluster#425]
### Is your feature request related to a problem?

if you configure a target-namespace for the k3s resources, you would expect isolation mode to restrict resources in that target-namespace. Instead it isolates the namespace which runs the k3s master node.

### Which solution do you suggest?

either it automatically uses the "target-namespace" or you can specify the namespace in the isolation block.

**Comment by FabianKramm** [comment]
@mhaddon thanks for creating this issue! Yes you are correct, currently this is not really supported but we could easily add this through chart options for the isolated mode
