### ISSUE TITLE
Syncer does not sync change of a ClusterIP service type to LoadBalancer

### ISSUE THREAD

**Issue by amir-latifi** [loft-sh/vcluster#431]
### What happened?

After creating a ClusterIP service, i tried to change its type to LoadBalancer; but the change did not sync and the service in parent cluster remained in ClusterIP type.

### What did you expect to happen?

Type of corresponding service in host cluster should have changed to LoadBalancer

### How can we reproduce it (as minimally and precisely as possible)?

Create a ClusterIP service and edit its type using `kubectl edit service`

### Anything else we need to know?

This the related part of syncer logs:

```
I0412 12:15:18.784601       1 logr.go:249] service: <service-name>: update virtual service default/<service-name>, because spec is out of sync

```

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Host cluster Kubernetes distribution

<details>

```
# Write here
```

</details>

### vlcuster version

<details>

```console
$ vcluster --version
vcluster version 0.7.1
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
# Write here
```

</details>

### OS and Arch

<details>

```
OS: Ubuntu 20.04
Arch:
```
</details>

**Comment by FabianKramm** [comment]
@amir-latifi thanks for creating this issue! Yes you are correct, we could reproduce that problem, we'll fix this ASAP!
