### ISSUE TITLE
default/kubernetes endpoints has incorrect IP when using k8s or eks flavor

### ISSUE THREAD

**Issue by matskiv** [loft-sh/vcluster#433]
### What happened?

The default/kubernetes endpoints resource is constantly updated with wrong value by one of the k8s controllers when k8s or eks flavor is used. Other flavors k3s/k0s don't have this problem, which is because syncer and kube-api are in one pod, and share the same IP address.

```
$ kubectl get endpoints -n default -w
NAME         ENDPOINTS                           
kubernetes   172.17.0.21:8443,172.17.0.26:8443
kubernetes   172.17.0.15:8443,172.17.0.16:8443,172.17.0.20:8443
kubernetes   172.17.0.21:8443,172.17.0.26:8443      
kubernetes   172.17.0.15:8443,172.17.0.16:8443,172.17.0.20:8443
```

### What did you expect to happen?

The endpoints defined in the default/kubernetes endpoints resource should always point to the syncer pods.

### How can we reproduce it (as minimally and precisely as possible)?

Install vcluster with k8s flavor and run `vcluster connect vcluster -- kubectl get endpoints -n default -w`

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:16:20Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:32:02Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
</details>


### Host cluster Kubernetes distribution

<details>

```
minikube
```

</details>


### vlcuster version

<details>

```console
I was using code from https://github.com/loft-sh/vcluster/pull/428 when reproducing this, but I am pretty sure previous version would have the same issue.
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
k8s and eks
```

</details>

### OS and Arch

<details>

```
OS: Linux, Fedora 35
Arch: x86
```
</details>

**Comment by nrchakradhar** [comment]
Hello,
vcluster is AWESOME. Thanks for providing this feature for OCP. I think the "restricted-hosts.mdx" documentation should be updated. I can raise a PR for this. Let me know if its fine.

**Comment by FabianKramm** [comment]
@nrchakradhar sure, you can create a PR for this if you like
