### ISSUE TITLE
imagePullSecret or mounting secret volume should be available when using different distros to access private registries

### ISSUE THREAD

**Issue by dannyt-cx** [loft-sh/vcluster#439]
### Is your feature request related to a problem?

Hi Everyone,

This is the situation I'm facing.
I've loaded all the vcluster images in to my Artifactory using the supplied scripts in the releases.
Next I've supplied in the field:
`defaultImageRegistry: myrepo.jfrog.io/docker`

the issue being: when running the vcluster create command like this:
`vcluster create danny-1 --namespace danny-1 -f values.yaml -f vcluster_args.yaml  --distro k8s --expose --debug`

It throws an error that it cannot pull the image - and it does so in the pre-install-hook-job.
https://github.com/loft-sh/vcluster/blob/main/charts/k8s/templates/pre-install-hook-job.yaml

since this job pulls the vcluster:0.7.1 image, it tries to do so using the supplied Registry and fails.
because Artifactory expects a login with credentials.
I've tried to pass volumes and extraArgs but it will not help

`vcluster:
  extraArgs:
    - imagePullSecrets: regcred
  volumes:
  - name: jfrog
    secret:
      secretName: regred
syncer:
  extraArgs:
    - imagePullSecrets: regcred`

simply because its not supported in the pre-install-hook-job.yaml.

this is currently the feature i find missing and would help a lot in AirGapped environments as well.

### Which solution do you suggest?

Allow to pass ImagePullSecrets or mount volumes to the Job from the values.yaml file.

**Comment by FabianKramm** [comment]
@dannyt-cx thanks for reporting this issue! We will release a fix for this soon!

**Comment by pratikjagrut** [comment]
@dannyt-cx the pr for this feature request is merged. You can try to set imagePullSecrets in `.Values.serviceAccount.imagePullSecrets` and it should work now.

**Comment by dannyt-cx** [comment]
great thanks, when can this chart be published to vcluster-chart repo?
the current chart that is pulled doenst contain these changes
