### ISSUE TITLE
Ingress pods and deployment pods are coming up with the same IPs in a vCluster

### ISSUE THREAD

**Issue by harish0619** [loft-sh/vcluster#44]
I am trying to create an ingress controller, ingress and related objects in a vCluster. Ingress controller and the related SA, namespace, etc.. are all deployed successfully. It resides in its own namespace "ingress-nginx"

\*\*dev-user@ubuntu:\~/vcluster$ kubectl get all -n ingress-nginx --kubeconfig kubeconfig.yaml
NAME                                            READY   STATUS      RESTARTS   AGE
pod/ingress-nginx-admission-create-w65dn        0/1     Completed   0          7m34s
pod/ingress-nginx-admission-patch-x7rqg         0/1     Completed   0          7m34s
pod/ingress-nginx-controller-7fcdd96bcf-m2sgn   1/1     Running     0          7m44s

NAME                                         TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
service/ingress-nginx-controller-admission   ClusterIP   10.109.123.12    <none>        443/TCP                      7m44s
service/ingress-nginx-controller             NodePort    10.109.100.180   <none>        80:31651/TCP,443:30824/TCP   7m44s

NAME                                       READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/ingress-nginx-controller   1/1     1            1           7m44s

NAME                                                  DESIRED   CURRENT   READY   AGE
replicaset.apps/ingress-nginx-controller-7fcdd96bcf   1         1         1       7m44s

NAME                                       COMPLETIONS   DURATION   AGE
job.batch/ingress-nginx-admission-create   1/1           2s         7m44s
job.batch/ingress-nginx-admission-patch    1/1           3s         7m44s\*\*

I deployed workload in default namespace and found the pods of this workload and the job pods created as part of ingress deployment have the same IPs.

\*\*dev-user@ubuntu:\~/vcluster$ kubectl get pods -o wide --kubeconfig kubeconfig.yaml
NAME                                          READY   STATUS    RESTARTS   AGE    IP            NODE       NOMINATED NODE   READINESS GATES
hello-world-service-single-6c58c555f8-dhv4l   1/1     Running   0          117s   172.17.0.12   minikube   <none>           <none>
hello-world-service-single-6c58c555f8-2wwkd   1/1     Running   0          117s   172.17.0.13   minikube   <none>           <none>

dev-user@ubuntu:\~/vcluster$ kubectl get pods -o wide -n ingress-nginx --kubeconfig kubeconfig.yaml
NAME                                        READY   STATUS      RESTARTS   AGE     IP            NODE       NOMINATED NODE   READINESS GATES
ingress-nginx-admission-create-w65dn        0/1     Completed   0          3m22s   172.17.0.11   minikube   <none>           <none>
ingress-nginx-admission-patch-x7rqg         0/1     Completed   0          3m22s   172.17.0.12   minikube   <none>           <none>
ingress-nginx-controller-7fcdd96bcf-m2sgn   1/1     Running     0          3m32s   172.17.0.11   minikube   <none>           <none>\*\*

The service which i create to expose my deployment is giving no response on doing a curl.

\*\*dev-user@ubuntu:\~/vcluster$ curl -vvvv [http://10.97.207.45](http://10.97.207.45)

* Rebuilt URL to: [http://10.97.207.45/](http://10.97.207.45/)
* Trying 10.97.207.45...
* TCP_NODELAY set\*\*

Any idea why these IPs are overlapping ( between ingress job pods and workload pods? )

**Comment by matskiv** [comment]
There has not been a response on this issue in a long time so I will close it. We can reopen if more information is provided.
