### ISSUE TITLE
Ability to initialize vcluster with manifests

### ISSUE THREAD

**Issue by ishankhare07** [loft-sh/vcluster#443]
### Is your feature request related to a problem?

Currently there's no way for a user to define manifests to initialize a new `vcluster`.

We would also like to have the ability to reflect any changes made to these manifests on detection of which we re-apply the manifests.

### Which solution do you suggest?

The following enhancement proposal is suggested.

#### Goals
1. Ability to deploy resources on startup.
2. Ability to reload / re-apply any changes made to these resources.

#### Non-Goals
1. Initial iteration does not target on specifying helm charts as an argument.
2. Initial iteration does not target consuming upstream URL's to k8s manifests as an input argument.

### Additional context

A typical use case can be a User wanting to create a new `vcluster` with some deployments like
* `nginx-ingress` as an ingress controller
* `knative` as a base layer for FaaS style development.

Since currently this is not directly supported in vcluster, User are supposed to follow roughly the following path:
1. Create a shell script that initially creates the `vcluster` itself.
2. On successful creation get the cluster (vcluster) credentials.
3. Using the obtained vcluster `kubeconfig` apply additional resource either through
    * `kubectl apply -f ...`
    * `helm install ...`
    * or Other custom tools like `istioctl`, `linkerd` etc
    
This enhancement proposes to standardize this flow to a more managable and declarative alternative with the following ideas:
1. Allow an optional `init` section in the supplies `values.yaml` file given as input to the `vcluster` cli.
2. The `init.manifests` section takes as an input a _multiline string_ which is simply the `yaml` manifest of what needs to be created/applied right after successful `vcluster` creation.
3. This section is then created as a `configmap`/`secret` in the host cluster and mounted at a designated mountpoint inside the `vcluster` – say `/etc/opt/init-manifests`
4. These manifests are then applied in much similar way as currently being done in the case of [Core DNS Manifests](https://github.com/loft-sh/vcluster/blob/main/cmd/vcluster/cmd/start.go#L354)
5. As an additional step, we also watch/pool this mountpoint and watch for any changes to the manifests, in which case, we trigger a reapply of these manifests.

As an additional step, we would like to have `helm`-style template blocks `{{ ... }}` in the `.Values.init.manifests` section that allows these resources to take advantage of inputs like `Release.Name`, `Release.Namespace` etc.

**Comment by olljanat** [comment]
This sounds good idea but it very near of example use case for plugins https://github.com/loft-sh/vcluster-sdk/tree/main/examples/bootstrap-with-deployment.

However it also does not make any sense that everyone is maintaining their own plugins so maybe we should introduce something like "vcluster-community-plugins" repo.

**Comment by FabianKramm** [comment]
@olljanat thats true, there are definitely several use cases that can be covered via plugins and shouldn't go into vcluster core but are somewhat reusable and interesting to use for others. We could also think about putting those into the main vcluster repo.

**Comment by olljanat** [comment]
@FabianKramm OK so how we should proceed with this one then? Maybe by defining folder structure that where to store those plugins in main vcluster repo?

PS. I just tried to ping you on LinkedIn too about another topic which you might want to see.

**Comment by FabianKramm** [comment]
@olljanat I still think for this it makes sense to have it in the core as I think a CLI integration would be really nice for this as well such as 
```
vcluster create ... --manifests my-manifests.yaml
```
Which would create the vcluster with the given manifests after starting.

Regarding the official plugin folder, we could do something like `plugins/` on the top level and then have a separate folder for each plugin that we support and want to maintain in the top level structure. @LukasGentele whats your opinion about this? We should also gather ideas what plugins might be needed in general and then implement a plugin for that to get the folder filled initially.

**Comment by LukasGentele** [comment]
@FabianKramm love the idea of the `plugins/` folder directly inside the main vcluster repo. We should accept PRs for that and work on some on our own. We can flag the ones we officially maintain in the README or so just like Docker Hub does it with their "official" images and the other ones can be in the same folder. We may need to set acceptance criteria at some point to make sure people hit certain quality standards for contributing plugins but I think we can start without that at first.

For the ones we should start with ourselves, we should have a look at CNCF's latest reports on CNCF projects' velocity and popularity to see which CRDs etc. to focus on first: https://www.cncf.io/blog/2021/12/15/end-of-year-update-on-cncf-and-open-source-velocity-in-2021/
