### ISSUE TITLE
vCluster imagePullSecrets not working

### ISSUE THREAD

**Issue by dannyt-cx** [loft-sh/vcluster#467]
### What happened?

Hi again!
i've come running as soon as i saw an official release and i found a problem with it :(
the ImagePullSecrets was added here - 
https://github.com/loft-sh/vcluster/blob/main/charts/k8s/templates/pre-install-hook-serviceaccount.yaml

This affects only the pre-install job - and that works.

Next comes up the Api-server/etcd/controller and there it stops :(

This is because they have no SA account which is linked to a dockerregistry secret - like the preinstall job.

![image](https://user-images.githubusercontent.com/79098664/167419618-c091734c-785c-4496-b6a1-f99cd4f685f0.png)

Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  13m                   default-scheduler  Successfully assigned danny-1/danny-1-api-9c9d44bc9-28jc5 to ultra-cloud-node
  Normal   Pulling    11m (x4 over 13m)     kubelet            Pulling image "danny.jfrog.io/docker/k8s.gcr.io/kube-apiserver:v1.20.12"
  Warning  Failed     11m (x4 over 13m)     kubelet            Failed to pull image "danny.jfrog.io/docker/k8s.gcr.io/kube-apiserver:v1.20.12": rpc error: code = Unknown desc = Error response from daemon: Head "https://danny.jfrog.io/v2/docker/k8s.gcr.io/kube-apiserver/manifests/v1.20.12": unknown: Authentication is required
  Warning  Failed     11m (x4 over 13m)     kubelet            Error: ErrImagePull
  Warning  Failed     8m23s (x20 over 13m)  kubelet            Error: ImagePullBackOff
  Normal   BackOff    3m22s (x43 over 13m)  kubelet            Back-off pulling image "danny.jfrog.io/docker/k8s.gcr.io/kube-apiserver:v1.20.12"

### What did you expect to happen?

The imagePullSecrets would be inside a serviceAccount available to the entire deployment.

### How can we reproduce it (as minimally and precisely as possible)?

I was testing outside of "default" namespace hence.

1. create namespace
2. create docker-registry secret inside namespace
3. kubectl get pods -n ${namespace} 

 you will see the pre-install job succeed.
but the rest will fail.
 

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
lient Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.11-eks-f17b81", GitCommit:"f17b810c9e5a82200d28b6210b458497ddfcf31b", GitTreeState:"clean", BuildDate:"2021-10-15T21:46:21Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Host cluster Kubernetes distribution

<details>

```
# eks v1.21
```

</details>

### vlcuster version

<details>

```console
$ vcluster --version
vcluster version 0.8.0
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
# k8s
```

</details>

### OS and Arch

<details>

```
OS: 
Arch:
```
</details>

**Comment by FabianKramm** [comment]
@dannyt-cx thanks for creating this issue! They actually should as they are linked to the service account here: https://github.com/loft-sh/vcluster/blob/main/charts/k8s/templates/serviceaccount.yaml , which adds the image pull secrets. Did you maybe add the image pull secrets after the pods were already created?

**Comment by dannyt-cx** [comment]
found whats wrong
in the deployment file for api-server/etcd/controller
there's no definition for `serviceAccountName: vc-{{ .Release.Name }}`

**Comment by FabianKramm** [comment]
You are correct @dannyt-cx, we need to add that, also to the controller and scheduler deployment!
