### ISSUE TITLE
What is the behavior of vcluster for deployment with hostPath?

### ISSUE THREAD

**Issue by Chakravarti-Baratam** [loft-sh/vcluster#477]
Hi, 
I am trying to understand the behaviour of vcluster with hostPath. For example, if I try to deploy splunk-connect (https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/manifests/splunk-kubernetes-logging/daemonset.yaml), what will happen with hostPath?
Thanks,

**Comment by FabianKramm** [comment]
@Chakravarti-Baratam thanks for creating this issue! We currently do not touch host paths at all, so they will just be forwarded as is to the host cluster. Depending on which host path is mounted though this can create problems, for example some logging solutions expect certain names of pods in the host path.
