### ISSUE TITLE
feat: context flag on vcluster

### ISSUE THREAD

**Issue by matdehaast** [loft-sh/vcluster#48]
It would be nice to have the ability to specify the kube-context to use when calling vcluster. Currently the default one is used so you have to ensure you are setup correctly before calling vcluster.

Example
```
vcluster --context my-cluster connect test --namespace test
```

would use the my-cluster context from `kubectl config get-contexts`

**Comment by FabianKramm** [comment]
@matdehaast thanks for creating this issue! Thats a good idea and we will add that to the `vcluster create/connect/delete` commands.

**Comment by FabianKramm** [comment]
@matdehaast this is working now with v0.3.0-beta.3
