### ISSUE TITLE
Vcluster List command should show as well paused clusters

### ISSUE THREAD

**Issue by gameiro** [loft-sh/vcluster#485]
### Is your feature request related to a problem?

When running the command `vcluster list`

It shows all the available vclusters in the host cluster and that is expected. 

But if we pause a particular vcluster `vcluster pause my-vcluster` and run again the command: `vcluster list`

The paused cluster is not visible in the list, making difficult for operators to know what is the vcluster that they need to resume again. 

### Which solution do you suggest?

It would be nice that when we list the vclusters the paused cluster would appear with some flag or json field that would reflect the exact status of the cluster.

For example adding a field like paused date and showing that in the `vcluster list` command.

**Comment by FabianKramm** [comment]
@gameiro thanks for creating this issue! We'll fix this for the next release!
