### ISSUE TITLE
Update helm chart with priorityClassName section

### ISSUE THREAD

**Issue by PetrovMikhail** [loft-sh/vcluster#487]
### Is your feature request related to a problem?

The problem appears when you need to define priorityClassName value to make an order of vcluster pods rolling out. Currently it can't be done via helm chart's values. It is necessary for instance, when you have k8s vcluster distribution and want to run etcd pods first. Otherwise other pods like syncer or api will be restarted several times until etcd pods are ready. Also it is convenient to set a priority of vcluster pods inside of the host cluster. For example to increase priority of vcluster pods compared to the optional infrastructure pods.

### Which solution do you suggest?

Apply priorityClassName parameter at least to syncer, api, controller deployments, etcd stateful set and pre-install job and make it configurable separately via helm values.

### Additional context

I think that priorityClassName is commonly used parameter among helm charts and I'm sure that it should simplify vcluster using in the future anyway.

I may create a pull request also, if it's OK for you please tell me.
_No response_

**Comment by FabianKramm** [comment]
@PetrovMikhail thanks for creating this issue! Yes we can do that!
