### ISSUE TITLE
Extend coredns helm template

### ISSUE THREAD

**Issue by PetrovMikhail** [loft-sh/vcluster#488]
### Is your feature request related to a problem?

The problem appears when you need to roll out default coredns deployment using image from private registry, for instance because of strict company requirements. In this case you need to define imagePullSecret section for coredns deployment, but it can not be done via Helm values. Recently imagePullSecret section was added to API, controller deployments, etcd stateful using service account settings. It would be perfect if it is also available for coredns deployment.

Also it would be great to make resources section of coredns deployment configurable via Helm values. With default values it can lead to conflict with MaxLimitRequestRatio limit range installed inside a vcluster.

### Which solution do you suggest?

Update Helm coredns template with imagePullSecret parameter, make coredns deployment resources section configurable via Helm values.

### Additional context

I may create a pull request also, if it's OK for you please tell me.

_No response_

**Comment by FabianKramm** [comment]
@PetrovMikhail thanks for creating this issue! I guess the image pull secret parameter with be difficult as we would need to copy the image pull secret into the virtual cluster here. You can actually add required image pull secrets for vcluster workloads via the `serviceAccount.imagePullSecrets` option. This will also add the image pull secret to the core dns deployment. Besides that we can definitely make the whole resources section configurable though.

**Comment by PetrovMikhail** [comment]
Hi @FabianKramm , thank you for your answer! I know about a possibility of setting imagePullSecrets via `serviceAccount.imagePullSecrets` option, thanks for the hint. Unfortunately I guess that `coredns` deployment uses own service account, which hasn't this setting, see [serviceAccount.imagePullSecrets](https://github.com/loft-sh/vcluster/blob/main/charts/k8s/templates/coredns.yaml#L122). So, maybe it makes sense to add imagePullSecret option to `coredns` service account too.

**Comment by FabianKramm** [comment]
@PetrovMikhail since the coredns pod is created inside the vcluster, the service account will be rewritten to the workload service account available in the chart, so this should work I believe with the regular `serviceAccount.imagePullSecrets` option and v0.8.1

**Comment by PetrovMikhail** [comment]
Ok, good to know, thank you @FabianKramm!
