### ISSUE TITLE
vcluster goes awry when you delete the service

### ISSUE THREAD

**Issue by alexandrem** [loft-sh/vcluster#493]
### What happened?

If you delete the main vcluster service in the host namespace, the syncer seems to go awry and delete all cluster resources. The pods get deleted, while the services seem to be recreated constantly.

This obviously disrupts the cluster.

Recreating the host vcluster service will not fix the issue automatically. This will start duplicating the cluster resources on the downstream cluster. You have to restart the vcluster pod to fix this, after recreating the service.

While deletion of the downstream vcluster service is an exceptional scenario, it is still prone to happen by mistake by an operator. Moreover, I believe it could occur under other circumstances, such as overlay networking disruption, or a bad network policy being applied to the namespace during the lifetime of a vcluster.

### What did you expect to happen?

As a vcluster owner, I expected to have some downtime and unavailability to speak to the Kubernetes API since it no longer exists.

However, the whole cluster resources become unavailable, and they should remain scheduled and running at all time, like a traditional Kubernetes control plane.

The workloads may also become entirely broken sometime, even after restoring the downstream vcluster service and statefulset. Sometimes I may have to recreate my workloads to fix everything.

### How can we reproduce it (as minimally and precisely as possible)?

Assuming the cluster is created:

```console
vclusterctl create vcluster -n vcluster-x -f values.yaml --connect --upgrade
```

where `values.yaml` is simply to override the service CIDR, which in my case is:
```yaml
serviceCIDR: 240.0.16.0/21
```

Then, in another terminal
```console
kubectl delete svc vcluster -n vcluster-x 
```

The coredns pods in the upstream cluster will be disrupted and put in "pending" scheduling mode.

If you have any workloads, they will be disrupted.

To simulate some demo application, assuming you have Pixie (https://pixielabs.ai/), run the following in the vcluster:
```console
px demo deploy px-online-boutique -y
```

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.11-gke.1100", GitCommit:"20da4c21b3a6b1a56ff6ad5ecb7dee013aaf1b83", GitTreeState:"clean", BuildDate:"2022-04-01T09:40:07Z", GoVersion:"go1.16.15b7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Host cluster Kubernetes distribution

<details>

```
GKE
```

</details>

### vlcuster version

<details>

```console
$ vcluster --version
0.8.1
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
v1.21.4+k3s1
```

</details>

### OS and Arch

<details>

```
OS: linux
Arch: x86-64
```
</details>

**Comment by FabianKramm** [comment]
@alexandrem thanks for creating this issue! Since vcluster uses this service as API endpoint for all workloads inside the virtual cluster, deleting it definitely will cause problems and render the cluster unusable. However, I agree, it definitely should recover after recreation as well as not deleting anything while in this broken state.

**Comment by ishankhare07** [comment]
@alexandrem Thanks for creating this issue. Here are some things I found related to this:

Currently all synced `pods` in the host cluster have an `ownerReference` set on them, owned by `svc/vcluster`. The moment you delete the `svc/vcluster`, k8s starts its garbage collection logic on all these host cluster pods by adding the `metadata.deletionTimestamp` on them.

This then triggers the syncer, which marks the fake pods in the vcluster as being deleted. But its NOT the syncer that triggers the deletion but the combination of k8s Garbage collection mechanism and the way we set the owner references.

What I suggest you can try at this point is to use the flag `--set-owner` defined in our [configuration reference](https://www.vcluster.com/docs/config-reference#syncer-flags) and see if this fixes your issue?

**Comment by alexandrem** [comment]
I confirm that this is fixed with `--set-owner=false` as syncer extraArgs. Everything is much more resilient now.

Thanks!
