### ISSUE TITLE
Epic: Add support for logging solutions inside vcluster

### ISSUE THREAD

**Issue by FabianKramm** [loft-sh/vcluster#510]
## Use Case

Currently its not possible to use common logging solutions such as FluentD or ELK stack inside vcluster, because all of them mount the node host path directly. While an acceptable solution is to provide a single logging solution in the host cluster, there are also use cases where you would want to install the solution directly inside the virtual cluster.

## Implementation

We can rewrite the host path with the correct pod uids trough symlinks in a sidecar container. We need to continously monitor changes to that folder and reflect it in the fake host path folder.

**Comment by ddl-risong-na** [comment]
This is something crucial for us. Do you have an ETA on when this will be implemented?

As always: great product!

**Comment by FabianKramm** [comment]
@ddl-risong-na not yet, we are still in the concept phase here.

**Comment by jaredallard** [comment]
It's worth noting we solved this problem (for restic (velero)) with https://github.com/getoutreach/vcluster-fs-syncer. Of course it's not perfect but worth pointing out :D

**Comment by FabianKramm** [comment]
@ddl-risong-na yes that is expected. One way to work around this is to use a node selector inside the vcluster that only syncs nodes that fullfill the selector to the virtual cluster (see the [docs](https://www.vcluster.com/docs/architecture/nodes#node-syncing-modes) for more info). If you really want to sync all nodes to the vcluster, you need to make sure that DaemonSets mostly run on the host cluster as this is a lot more efficient as you already have discovered.

Regarding the vcluster pod failing, that is probably a different issue, but you are correct it usually should withstand quite a lot of load. We did some improvements for this in the latest version v0.9.1, so if you are not using that yet would be interesting to know if that also goes into an OOM state. If yes, this is definitely worth creating a new issue for, as vcluster should be able to scale to several hundreds if not thousands per cluster.

**Comment by vumdao** [comment]
I installed Elasticsearch on the host and what I got from search is following and it shows nothing related to kubernetes labels/namespace

![image](https://user-images.githubusercontent.com/37215642/177575542-33edb0cb-6841-40f1-9c02-9627f605b5b6.png)

What is a workaround for this?

**Comment by sandeep540** [comment]
@FabianKramm are you looking at vcluster plug-in to solve this? Can I take a stab at it? If you can give more details it would be great

**Comment by vumdao** [comment]
Hi, any update?any documents to enable logging in vcluster or from host?
