### ISSUE TITLE
vcluster create with both connect false and extra-values does not apply the extra values

### ISSUE THREAD

**Issue by jamestalton** [loft-sh/vcluster#545]
### What happened?

When running
> vcluster create my-cluster --connect false --extra-values values.yaml

A connection is not made and the extra values end up being run on the host cluster instead of the vcluster.

### What did you expect to happen?

Expected that the values would be applied to the vcluster and not the host cluster.

### How can we reproduce it (as minimally and precisely as possible)?

> vcluster create my-cluster --connect false --extra-values values.yaml

### Host cluster Kubernetes version

OpenShift 4.11

### Host cluster Kubernetes distribution

OpenShift 4.11

### vlcuster version

<details>

```console
$ vcluster --version
vcluster version 0.10.0
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

k3s

### OS and Arch

OSX AMD64

**Comment by FabianKramm** [comment]
Hey @jamestalton ! Thanks for creating this issue! I'm not sure if I understand you correctly, but what do you mean with applied on the host cluster? The values should be applied to the vcluster, is there any error message you see? Make also sure to run with the flag `--upgrade` if you want to upgrade an existing vcluster.

**Comment by jamestalton** [comment]
After more investigation I found that the problem is in the way I called vcluster.

> vcluster create  my-vcluster -f my-vcluster.yaml --connect false

should be 

> vcluster create  my-vcluster -f my-vcluster.yaml --connect=false

Thanks for the fast response. The vcluster project is awesome.
