### ISSUE TITLE
Ephemeral Containers does not works with vcluster

### ISSUE THREAD

**Issue by olljanat** [loft-sh/vcluster#585]
### What happened?

Kubernetes 1.23 graduated [ephemeral containers](https://kubernetes.io/docs/concepts/workloads/pods/ephemeral-containers/) to beta and it is enabled by default.

However I far I see `kubectl debug ...` is not able to connect to pods in vcluster but instead of it hangs forever after writing message `Defaulting debug container name to debugger-...` to log.

If I try same on host cluster side it works just fine.

### What did you expect to happen?

That I can use  `kubectl debug ...` same way on vcluster side too.

### How can we reproduce it (as minimally and precisely as possible)?

https://kubernetes.io/docs/tasks/debug/debug-application/debug-running-pod/#ephemeral-container-example

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:22:29Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6+rke2r1", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-20T19:41:09Z", GoVersion:"go1.17.9b7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Host cluster Kubernetes distribution

<details>

```
RKE2
```

</details>

### vlcuster version

<details>

```console
$ helm list
vcluster-k8s-0.10.2
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
k8s
```

</details>

### OS and Arch

<details>

```
OS: Ubuntu 20.04
Arch: amd64
```
</details>

**Comment by FabianKramm** [comment]
@olljanat thanks for reporting this issue! Yes we are currently not propagating changes to ephemeral containers to the host cluster. We'll fix that in the next release
