### ISSUE TITLE
Display versioned documentation on the website

### ISSUE THREAD

**Issue by matskiv** [loft-sh/vcluster#596]
### Is your feature request related to a problem?

Documentation on the vcluster.com website sometimes refers to features that are not released in a stable release yet.
Also, when facing a problem with the previous version, or just when using the previous version, newer documentation can be inapplicable.

### Which solution do you suggest?

A dropdown to select the vcluster version on the docs page.

### Which alternative solutions exist?

Reading docs from source code tag.
Starting docs portal from source locally.
https://web.archive.org/web/*/https://www.vcluster.com/docs/what-are-virtual-clusters

Nether option is convenient.

**Comment by LukasGentele** [comment]
Should not be done before v1 or actually V2 tbh. Too many versions don't scale well and are just confusing.

**Comment by FabianKramm** [comment]
Yes, I'll close this for now
