### ISSUE TITLE
Does Software license keep Apache-2.0 License ?

### ISSUE THREAD

**Issue by harryliu123** [loft-sh/vcluster#6]
Thanks for making the loft core project open source
I would like to ask what is this project will keep  license  Apache-2.0 License ?
thx.

**Comment by FabianKramm** [comment]
@harryliu123 Hello! Yes, this project will stay Apache-2.0 License.

**Comment by harryliu123** [comment]
@FabianKramm, Thanks for your answer
We try to use the verification environment, But we are worried about whether the license will be changed it.
i close this issus
