### ISSUE TITLE
Syncer Service account not found

### ISSUE THREAD

**Issue by Noamstrauss** [loft-sh/vcluster#611]
### What happened?

I am trying to assume a role in aws with annotations in the service account, so i added this syncer config
```
syncer:
  extraArgs: ["--service-account=boot-vault"]
```
but then i get this error in each pod:
`Error syncing to physical cluster: pods "cert-manager-7d5dc9bf65-7frh7-x-cert-manager-x-vault" is forbidden: error looking up service account vcluster-vault-qaubp/boot-vault: serviceaccount "boot-vault" not found (SyncError)`
the same error in the syncer contianer:
`1 recorder.go:103] events: Warning object v1.ObjectReference{Kind:"Pod", Namespace:"cert-manager", Name:"cert-manager-7d5dc9bf65-7frh7", UID:"21ecf24a-f000-4fd9-8e36-aad5aab965be", APIVersion:"v1", ResourceVersion:"508", FieldPath:""} reason SyncError message Error syncing to physical cluster: pods "cert-manager-7d5dc9bf65-7frh7-x-cert-manager-x-vault" is forbidden: error looking up service account vcluster-vault-qaubp/boot-vault: serviceaccount "boot-vault" not found `

this service account exists in the physical cluster under a namespace.

### What did you expect to happen?

To be able to assume a role in the vcluster using service account annotations.

### How can we reproduce it (as minimally and precisely as possible)?

Create a vcluster with the config 
```
syncer:
  extraArgs: ["--service-account=boot-vault"]
```

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.9+k3s1", GitCommit:"8b0b50a5e88214f69e4ef35ebfd60c6adac9735f", GitTreeState:"clean", BuildDate:"2022-04-28T22:46:07Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}```

</details>


### Host cluster Kubernetes distribution

<details>

```

```

</details>


### vlcuster version

<details>

```console
vcluster version 0.10.2
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
k3s
```

</details>

### OS and Arch

<details>

```
OS: Mac 12.2.1
Arch:
```
</details>

**Comment by matskiv** [comment]
I was able to reproduce the error when service account does not exist. After that, I created the service account but the pod was not synced to the host simply immediately. I restarted the syncer process (syncer container in vcluster, or just whole vcluster pod would work too), and then it all worked as expected.
Perhaps there is a timing issue? Have you created the ServiceAccount after creating a pod in vcluster?

**Comment by Noamstrauss** [comment]
@matskiv yes i have created this service account in the vcluster & in the physical cluster.
**vcluster:** 
`Name:                boot-vault
Namespace:           default
Labels:              <none>
Annotations:         eks.amazonaws.com/role-arn: arn:aws:iam::<account-number>:role/vault
Image pull secrets:  <none>
Mountable secrets:   boot-vault-token-75dqd
Tokens:              boot-vault-token-75dqd
Events:              <none>
`
**Physical cluster:**
`
Name:                boot-vault
Namespace:           default
Labels:              <none>
Annotations:         eks.amazonaws.com/role-arn: arn:aws:iam::<account-number>:role/vault
Image pull secrets:  <none>
Mountable secrets:   boot-vault-token-t2t4l
Tokens:              boot-vault-token-t2t4l
Events:              <none>
`

**Comment by matskiv** [comment]
@Noamstrauss This service account needs to be created in the host cluster only. But it needs to be created in the namespace where you vcluster is running (`vcluster-vault-g5382` right?), but your information posted above shows that it is created in the default namespace.

**Comment by Noamstrauss** [comment]
@matskiv yes , ok i just created this service account in this namespace. but there is no service account in the vcluster `vault`

**Comment by matskiv** [comment]
The `--service-account` flag does not do any ServiceAccount creation in the vcluster. It only set the ServiceAccount which will be used to run the "synced" pods in the host cluster. But the pods inside vcluster will be using service account defined in the pod spec inside of the vcluster. And the pods will have the kubernetes service account token from the vcluster.

If you use the `--service-account=boot-vault` flag, and set the `eks.amazonaws.com/role-arn: ...` annotation on the `boot-vault` SA in the host cluster, then ALL the pods started in the vcluster will have the  AWS_WEB_IDENTITY_TOKEN_FILE and AWS_ROLE_ARN environment variables available inside of the containers.
If this is not desirable, consider using the option to sync service accounts from vcluster to the host. Then each SA that is used by some pod will be synced to the host cluster, together with the annotations. But beware that the name will be "translated"(you probably noticed the pattern with which pods in the host are named) to avoid conflicts. For enabling SA sync use this helm value:
```
sync:
  serviceaccounts:
    enabled: true
```

**Comment by vishnu-chegondi** [comment]
Hi @matskiv , I am using service account sync to sync service accounts from virtual cluster to host. I see tokens are getting attached to host pod yaml. But when I see virtual cluster pod I see no token is getting mounted.

I have also seen the vcluster docs the below lines at the page 
https://www.vcluster.com/docs/what-are-virtual-clusters.
`
Service account tokens, environment variables, DNS and other configurations are exchanged to point to the virtual cluster instead of the host cluster.
`
So, whenever we make a request it will not include token generated by host cluster to support OIDC. Correct me if I am wrong.

**Comment by matskiv** [comment]
@vishnu-chegondi
> But when I see virtual cluster pod I see no token is getting mounted. 

What do you mean by this? If you get a pod with `kubectl get pod` in vcluster context, and you don't see the extra mounts for the token, then it is correct behavior. If you exec into a pod and there is no `/var/run/secrets/kubernetes.io/serviceaccount/token` file, then it sounds like an issue.

> So, whenever we make a request it will not include token generated by host cluster to support OIDC.

If you mean the ServiceAccount token from the host cluster then yes, that one is not mounted into virtual pods. But tokens injected via other means (env vars, volume mounts) would probably be available inside the pod, but not visible in `kubectl get pod virtualpod` (in vcluster context).

@vishnu-chegondi If you wish to continue this conversation please create a new issue or start a thread in our community Slack (https://slack.loft.sh/). I don't think your question is relevant in context of this issue.
