### ISSUE TITLE
Issue Syncing Readiness Conditions

### ISSUE THREAD

**Issue by donmstewart** [loft-sh/vcluster#619]
### What happened?

We have pods with custom readiness gates/conditions.

The pod in the vcluster updates the gates correctly but then reverts immediately and the gates are no longer present.

### What did you expect to happen?

The radiness gates/conditions are set on the vcluster pods and they sync down to the hostcluster pod and remain in place.

### How can we reproduce it (as minimally and precisely as possible)?

Add readiness to a pod in the vcluster and they will be removed.

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:14:10Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"3396beebcd97ed3b01f57127fba1b8565b311acb", GitTreeState:"clean", BuildDate:"2022-06-04T17:58:54Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.24) and server (1.21) exceeds the supported minor version skew of +/-1
```

</details>

### Host cluster Kubernetes distribution

<details>

```
Microsoft Azure AKS
```

</details>

### vlcuster version

<details>

```console
$ vcluster --version
vcluster version 0.10.1
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
k3s
```

</details>

### OS and Arch

<details>

```
OS:  linux
Arch: AMD64
```
</details>

**Comment by FabianKramm** [comment]
@donmstewart thanks for creating this issue! Yes, this seems like a problem currently. We can add a special case for those conditions in the pod syncer.

**Comment by donmstewart** [comment]
Thank you.
