### ISSUE TITLE
Provide reasonable resource requests and limits

### ISSUE THREAD

**Issue by MShekow** [loft-sh/vcluster#62]
Often there are resource quotas assigned to the namespace into which you install vcluster. These are sometimes set to be quite strict, and there is also a mandatory LimitRange.

vcluster's Helm chart lacks a `resources` section. It is not clear how much performance the two containers (syncer and vcluster) need, for a typical scenario. For instance, I found that a memory limit of 256 results in an OOM kill, with `Run: k3s kubectl` being the last entry in the container log.

**Comment by FabianKramm** [comment]
@MShekow thanks for creating this issue! Yes you are correct, we can provide some default values for the resources section based on a default use case

**Comment by matskiv** [comment]
This was implemented in #99 but we forgot to close the issue, so closing it now :)
