### ISSUE TITLE
vcluster api version upgrade feature required.

### ISSUE THREAD

**Issue by calvinroyston** [loft-sh/vcluster#625]
What ?

Option to update vcluster api version in an existing vcluster.

Why?

vcluster has option of choosing k3s/k0s/k8s api during cluster creation but an option to upgrade the api version can be useful which also takes care of updating fake nodes' kubelet endpoint version.

Thoughts:

Updating the below field is updating the control plane but not worker node kubelet version( fake nodes )

vcluster:
image: rancher/k3s:v1.22.11-k3s1

Question: Does the fake node version simulate worker nodes to be in that version ? or its always on superCluster kubelet version?

**Comment by matskiv** [comment]
> Question: Does the fake node version simulate worker nodes to be in that version ? or its always on superCluster kubelet version?

It doesn't simulate that version. The actual node kubelet version depends on the host cluster version.

**Comment by calvinroyston** [comment]
running "kubectl get nodes" on the vcluster shows node  version numbers same as the K3s api version. Is this a bug ?

**Comment by matskiv** [comment]
> running "kubectl get nodes" on the vcluster shows node version numbers same as the K3s api version. Is this a bug ?

I don't think that's a bug. I can see an argument for having that version match host cluster version, but also I can see an argument for current behavior. But I would guess it doesn't make any practical impact either way. Or is there some application that behaves differently based on kubelet version?

**Comment by calvinroyston** [comment]
No I haven't found any application which behaves differently but was curious to know why it shows k3s api versions in place of kubelet versions. I noticed this when i tried upgrading the control plane with different k3s version but the nodes stayed on displaying old k3s api version. 

Is there a key in values.yaml which can change this behavior so that we can always see host cluster kubelet version?

**Comment by matskiv** [comment]
> ... curious to know why it shows k3s api versions in place of kubelet versions. ...

I suspect some controller in k3s is setting this value in the status. When using k8s or k0s distro of vcluster you might see some different results too.

> Is there a key in values.yaml which can change this behavior so that we can always see host cluster kubelet version?

No, there is no feature like that.
