### ISSUE TITLE
pv is not binding to pod

### ISSUE THREAD

**Issue by der-ali** [loft-sh/vcluster#632]
### What happened?

I want to test a csi-driver on the vcluster. 
I did the following:
- created a vcluster with persistentvolumes and storageclasses enabled.
- deployed the csi-driver and created the storage class
- created a satefulset wich uses the storage class
- pv bound successfully to the pvc 

### What did you expect to happen?

The pod gets created and the pv is bount to the pod, 
but the pod is pending and getting the following error:
```
Unable to attach or mount volumes: unmounted volumes=[www], unattached volumes=[kube-api-access-fsl4p vcluster-rewrite-hosts www]: timed out waiting for the condition
```

### How can we reproduce it (as minimally and precisely as possible)?

As described above

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Host cluster Kubernetes distribution

<details>

```
k8s v1.21
```
</details>

### vlcuster version

<details>

```
vcluster version 0.10.2
```
</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
k8s
```

</details>

### OS and Arch

<details>

```
OS: ubuntu 20.04
```
</details>

**Comment by mabhi** [comment]
Hello @der-ali, 
wanted to contribute on this issue and based on its open state, I was planning to analyse and work on it. Do let me know, if this issue can be taken up if unassigned.

**Comment by der-ali** [comment]
Hi @mabhi, i took a look at it today and it turned out it was an issue on my side. The csi driver was misconfigured, but  i wasn't getting an event in this regard.

**Comment by mabhi** [comment]
Hello Oleg,
Sure would like to contribute. I am also scanning issues, but it would be really helpful if you can sort some of the issues which I can start analysing. Do let me know, I can assign it to myself and start working. I checked the link just as I speak but it is empty now.
As suggested I have joined the slack channel, keeping eye.
