### ISSUE TITLE
Update k3s, k0s & k8s versions

### ISSUE THREAD

**Issue by FabianKramm** [loft-sh/vcluster#637]
We should update the k0s, k3s & k8s versions for v1.21, v1.22, v1.23 & v1.24 [here](https://github.com/loft-sh/vcluster/tree/main/pkg/helm/values)

**Comment by rahulii** [comment]
Hey @FabianKramm , do you mean add a new map entry for the offical images? for eg: https://github.com/loft-sh/vcluster/blob/main/pkg/helm/values/k0s.go#L10 here for 1.21 and 1.24 ?

**Comment by FabianKramm** [comment]
@rahulii yes exactly as well as bumping the existing images to their latest versions.
