### ISSUE TITLE
Error from server (Forbidden): namespaces is forbidden: User "system:serviceaccount:vcluster:default" cannot list resource "namespaces" in API group "" at the cluster scope

### ISSUE THREAD

**Issue by guettli** [loft-sh/vcluster#652]
### What happened?

I am following the docs from CONTRIBUTING.md

Listing the namespaces, as suggested in CONTRIBUTING fails.

```
vcluster on  main [!] via 🐹 v1.18.2 
❯ devspace run dev
.... starts fine
```

```
vcluster-0:vcluster-dev$ kubectl get ns
Error from server (Forbidden): namespaces is forbidden: User "system:serviceaccount:vcluster:default" cannot list resource "namespaces" in API group "" at the cluster scope
```

### What did you expect to happen?

According to CONTRIBUTING.md getting the namespaces should work.

From the docs:
```
root@vcluster-0:/vcluster# kubectl get ns

NAME              STATUS   AGE
default           Active   2m18s
kube-system       Active   2m18s
kube-public       Active   2m18s
kube-node-lease   Active   2m18s
```

### How can we reproduce it (as minimally and precisely as possible)?

I am unsure if it if only on my machine, but maybe following the instructions reproduces this on other machines, too.

### Host cluster Kubernetes version

<details>

```console
$ kubectl version

Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-14T02:31:37Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4

Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}


```

</details>

### Host cluster Kubernetes distribution

❯ minikube version
minikube version: v1.25.2

### vlcuster version

from git.

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

default

### OS and Arch

<details>

```
❯ cat /etc/os-release 
PRETTY_NAME="Ubuntu 21.10"
NAME="Ubuntu"
VERSION_ID="21.10"
VERSION="21.10 (Impish Indri)"
VERSION_CODENAME=impish
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=impish
```
</details>

**Comment by FabianKramm** [comment]
@guettli thanks for reporting this issue! Yes seems like the contributing readme is out of date, instead of running kubectl inside the virtual cluster container, we rather recommend to use `vcluster connect` locally instead.

**Comment by guettli** [comment]
@FabianKramm thank you for updating CONTRIBUTING.md. I will try the new guide.
