### ISSUE TITLE
Bash/Zsh completions

### ISSUE THREAD

**Issue by richburroughs** [loft-sh/vcluster#673]
### Is your feature request related to a problem?

Not a problem, it's more a usability improvement.

### Which solution do you suggest?

It would be great to have Bash/Zsh tab completions for things in vcluster. I was thinking specifically about the virtual cluster names, it would be nice to be able to hit tab on those to complete them. It might be useful for more objects besides that though.

### Which alternative solutions exist?

None that I'm aware of.

### Additional context

*No response*

**Comment by Ygshvr** [comment]
Hi @matskiv , could you please assign this to me?
