### ISSUE TITLE
Output from "vcluster disconnect"

### ISSUE THREAD

**Issue by richburroughs** [loft-sh/vcluster#677]
### Is your feature request related to a problem?

Suggested improvement. I found it odd that there's no output when you run "vcluster disconnent". I think all of the other subcommands I've used give some kind of output when they're run.

### Which solution do you suggest?

Something indicating the disconnect succeeded, maybe also the vcluster name?

### Additional context

This was just my feeling using the tool :)

**Comment by sandeep540** [comment]
Hi @richburroughs and @FabianKramm , Can you please assign it to me ?
