### ISSUE TITLE
Init container may detect CIDR range incorrectly

### ISSUE THREAD

**Issue by matskiv** [loft-sh/vcluster#704]
### What happened?

This was originally reported in our Slack here:
https://loft-sh.slack.com/archives/C01N273CF4P/p1657916523372759

An init container for detecting CIDR range of the Service network is writing an incorrect value into the output ConfigMap.
This feature was initially added in PR https://github.com/loft-sh/vcluster/pull/497
However `vcluster get service-cidr` CLI command is detecting the CIDR range correctly.

### What did you expect to happen?

The `vc-cidr-{{ vcluster name }}` ConfigMap should contain correct value for the `cidr` key.

### How can we reproduce it (as minimally and precisely as possible)?

All the info I have is in [the Slack thread](https://loft-sh.slack.com/archives/C01N273CF4P/p1657916523372759).

### Anything else we need to know?

Perhaps the logic used in the init container here: https://github.com/loft-sh/vcluster/blob/605eb93a5c7dc02be6b9a18ea46644f38f95f054/pkg/util/servicecidr/servicecidr.go#L36
should import this functionality from [the CLI code](https://github.com/loft-sh/vcluster/blob/605eb93a5c7dc02be6b9a18ea46644f38f95f054/cmd/vclusterctl/cmd/get/service_cidr.go). Seems like there is some difference between the two.

### Host cluster Kubernetes version

<details>

```console
No info
```

</details>

### Host cluster Kubernetes distribution

<details>

```
EKS, maybe other too
```

</details>

### vlcuster version

<details>
```
0.10.2, 0.11.0, 0.11.1
```
</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
Out of 3 reports, 1 was eks, the others are unspecified.
```

</details>

### OS and Arch

<details>

```
N/A
```
</details>

**Comment by mabhi** [comment]
Hi @matskiv, Can you assign this issue to me, so i can start analysing it more, please.
