### ISSUE TITLE
Create globalAnnotations for eks, k8s and k0s

### ISSUE THREAD

**Issue by FabianKramm** [loft-sh/vcluster#714]
Thanks to @denniskorbginski and his PR #697 we can support `globalAnnotations` for all objects created by vcluster k3s. Would be nice if we add the same option to our other charts, so that the values stay consistent across the different charts.

**Comment by Ab-hishek** [comment]
Hi @FabianKramm . I would like to work on this one.

**Comment by matskiv** [comment]
@Ab-hishek Are you still working on this issue? If you got blocked and need help, please don't hesitate to reach out to us in vcluster channel in [our Slack](https://slack.loft.sh/).

**Comment by Ab-hishek** [comment]
I will work on it. Sure @matskiv, will reach out in case I get stuck.

**Comment by matskiv** [comment]
@Ab-hishek Where are you with regards to this issue? We will implement it if you are busy with other things. :slightly_smiling_face:

**Comment by Ab-hishek** [comment]
I'll try to raise a PR by tomorrow :)

**Comment by Kartik-Garg** [comment]
@matskiv Hey can I get this issue assigned to me please?
I have already raised a PR regarding this (:
