### ISSUE TITLE
Be able to configure to turn off Init Containers, vcluster-rewrite-hosts

### ISSUE THREAD

**Issue by GyunCho** [loft-sh/vcluster#717]
### Is your feature request related to a problem?

No

### Which solution do you suggest?

Be able to set something like initContainer.enabled: false in the EKS Helm Chart, 
so that vcluster will not inject InitContainer, vcluster-rewrite-hosts with an image library/alpine:3.13.1,
which is not necessary for my case.

**Comment by FabianKramm** [comment]
@GyunCho thanks for creating this issue! Just want to understand the reasoning behind this, are those init containers causing problems?

**Comment by matskiv** [comment]
@GyunCho btw, if you don't like that particular image(or tag) for some reason, you can use this flag to re-map it to a different one:
https://github.com/loft-sh/vcluster/blob/b60c2c165197cdb2cee8919e5965d5a0161f689f/cmd/vcluster/cmd/start.go#L115
The image needs to have `sh` and `sed` !

**Comment by GyunCho** [comment]
@FabianKramm 
It's not causing any problems, but I wanted to also configure securityContext and image for it, but it didn't seem possible, or straightforward. I figured out it's not mandatory, so I just wanted to disable it to make things simpler.

@mahendrabagul  That works like a charm! Since this one line or two lines do the work that I originally wanted to achieve, this issue can be closed. Thanks alot! 

I'd just like this to be taken care of: https://github.com/loft-sh/vcluster/issues/718#issuecomment-1241982345
