### ISSUE TITLE
Support Pod Disruption Budgets (PDBs)

### ISSUE THREAD

**Issue by matskiv** [loft-sh/vcluster#72]
Pod disruption budgets[1] are very important for high availability kubernetes services.
They can be created inside a vcluster, but if I understand vcluster architecture correctly,
they would need to be synced into host cluster to be effective.

[1] https://kubernetes.io/docs/concepts/workloads/pods/disruptions/#pod-disruption-budgets

**Comment by FabianKramm** [comment]
@matskiv thanks a lot for creating this issue! Yes you are correct, pod disruption budgets need to be synced to the host cluster to work effectively, we definitely should implement this
