### ISSUE TITLE
core-dns failing in civo cluster

### ISSUE THREAD

**Issue by ratnadeep007** [loft-sh/vcluster#73]
**Issue**
Unable to create vcluster in Civo kubernetes cluster which internally uses k3s. Able to connect to api-server but unable to deploy anything as coredns is failing for vcluster

**Steps**
1. Created namespace; `kubectl create namespace vcluster-1`
2. Used vcluster cli: `vcluster create vcluster-1 -n vcluster-1`
3. Connect to cluster: `vcluster connect vcluster-1 -n vcluster-1`
4. Tried deploying nginx, it stays in pending state inside vcluster but running state on host.
5. `coredns` container is in `Pending` state for vcluster and `ContainerCreating` state for host

**Logs**
Events from describe command of core-dns
- `Unable to attach or mount volumes: unmounted volumes=[config-volume], unattached volumes=[config-volume coredns-token-mbwt2]: timed out waiting for the condition`
- `MountVolume.SetUp failed for volume "config-volume" : configmap references non-existent config key: NodeHosts`

**Self fix or debug**
Tried changing default storageclass in cluster from `civo-volume` from provisioner `csi.civo.com` to `local-path` from provisioner `rancher.io/local-path` but same result.

Cluster Type: Managed Cluster based on k3s by Civo.com

**Comment by FabianKramm** [comment]
@ratnadeep007 thanks for creating this issue! Thats odd, this usually only happens if you try to run vcluster in a cluster without any nodes. What happens if you deploy vcluster with a values.yaml that looks like this:
```yaml
storage:
  persistence: false
rbac:
  clusterRole:
    create: true
syncer:
  extraArgs:
  - --sync-all-nodes
  - --fake-nodes=false
  - --fake-kubelets=false
```

and then create the vcluster with `vcluster create vcluster-1 -n vcluster-1 -f values.yaml`, does that work?

**Comment by ratnadeep007** [comment]
@FabianKramm Thanks, it worked.
