### ISSUE TITLE
Sync the .status.loadBalancer field of the mapped Services.

### ISSUE THREAD

**Issue by matskiv** [loft-sh/vcluster#732]
### Is your feature request related to a problem?

Services created by vcluster based on the [configured service mapping](https://www.vcluster.com/docs/architecture/networking#mapping-services-between-vcluster-and-host-cluster) are lacking status, which means that it is not possible to read for example the IP of the assigned load balancer.

### Which solution do you suggest?

Sync the `.status.loadBalancer` field of [the mapped Services](https://www.vcluster.com/docs/architecture/networking#mapping-services-between-vcluster-and-host-cluster).

### Which alternative solutions exist?

No viable solution. A workaround is to read the `.status.loadBalancer` from the source Service, but that requires additional knowledge, access, and manual effort from the user.

### Additional context

This is the controller that executes synchronization of the mapped Services:
[https://github.com/loft-sh/vcluster/blob/main/pkg/controllers/servicesync/servicesync.go](https://github.com/loft-sh/vcluster/blob/main/pkg/controllers/servicesync/servicesync.go)

**Comment by rahulii** [comment]
https://github.com/loft-sh/vcluster/blob/main/pkg/controllers/register.go#L324
hey @matskiv as per this func it says `please use please use namespace1/service1=service2 ` service mapping 
but as per the docs https://www.vcluster.com/docs/architecture/networking#map-host-cluster-service-to-vcluster-service the format is bit different ?
Am I missing something here ?
cc: @FabianKramm

**Comment by matskiv** [comment]
@rahulii The docs describe how to write the mapping in the helm values, it is then transformed into a different format to pass it as a CLI flag - https://github.com/loft-sh/vcluster/blob/09b0fd82c1ab8e820a6ed1fa342cb2dd443419e2/charts/k3s/templates/_helpers.tpl#L113-L129

**Comment by rahulii** [comment]
@matskiv I have the fix ready but since this requires loadbalancer service I would need cloud clusters to test , right ? or any other way ?

**Comment by matskiv** [comment]
@rahulii You could test it with minikube too. Use `minikube tunnel` command. Docs: https://minikube.sigs.k8s.io/docs/handbook/accessing/#using-minikube-tunnel
