### ISSUE TITLE
A pod might become unschedulable when using a PV with nodeAffinity

### ISSUE THREAD

**Issue by matskiv** [loft-sh/vcluster#754]
### What happened?

A dynamically provisioned PV that has nodeAffinity set (e.g. because the host cluster spans multiple AZs) might become unusable by the pod that requested it, making the pod unschedulable.
This happens because of our workaround in vcluster, which sets the `volume.kubernetes.io/selected-node` annotation incorrectly. A node from the wrong AZ gets selected, which prevents scheduling. Responsible code is here - https://github.com/loft-sh/vcluster/blob/1d77744033469912abe52a5f46fa5ea074ed37d4/pkg/controllers/resources/persistentvolumeclaims/translate.go#L112-L149

Seems like the workaround code above does not take into account nodeAffinity of the PV, perhaps that would be sufficient to fix the issue. But ideally, the node selection should be done by the scheduler([here](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/plugins/volumebinding/binder.go#L410) I belive), so we should investigate what prevents scheduler from doing this correctly, and as a result, forces us to maintain this workaround.

### What did you expect to happen?

A PV of a StorageClass with `volumeBindingMode: WaitForFirstConsumer` should get dynamically provisioned based on a PVC, and then mounted to a successfully scheduled Pod even in a cluster with topology constraints (e.g. multiple AZs).

### How can we reproduce it (as minimally and precisely as possible)?

Ideally, a cluster with nodes spanning across multiple AZs should be used to reproduce this. But it might be possible with a local multi-node cluster with hostpath provisioned too.
A StorageClass with `volumeBindingMode: WaitForFirstConsumer` should be created. It should be used in a PVC that is used by some Pod.

### Anything else we need to know?

This was reported on EKS host, and the reporter stated that the issue happens when CSI Addon (aws-ebs-csi-driver [v1.10.0-eksbuild]) is enabled.

### Host cluster Kubernetes distribution
Reported on EKS, but applies to all distributions I believe.

### vlcuster version
0.12.0

**Comment by rohantmp** [comment]
Here is the progress of my attempt to reproduce:

So the current flow is:

1. virt: PVC and Deployment created, 
2. virt: Pod created pending
3. host: Pod not synced, no Node assigned
4. virt:  PVC assigned to random node that matches storageclass allowed topologies
5. host : pv-controller(I don't know if external-provisioner subs in for CSI here) sees the selected-node annotation and provisions PV with nodeAffinity
6. virt: PV appears (syncing from host to virt)
7. virt: Pod is assigned a node
8. host: Pod Synced.

Now in EKS, the PV is created with nodeAffinity set to keep the PV in the same region and zone as the originally selected node:
```
kind: PersistentVolume
[...]
spec:
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          - eu-central-1a
        - key: topology.kubernetes.io/region
          operator: In
          values:
          - eu-central-1
```
 
The event seen ` message: '0/4 nodes are available: 4 node(s) had volume node affinity conflict.'` indicates that the node the pod is scheduled onto does not meet those constraints. The PV will be created in the zone/region of assigned in the workaround.

The pod is assigned after the provisioning of the PV, so I am investigating the possibility that there is some way that the Pod can be somehow assigned to a Node outside of the zone/region of the selected-node/PV.

**Comment by rohantmp** [comment]
Attempting the steps above, the hypothesis proved to be false:
All nodes were tainted in `eu-central-1a`,  the PV was bound in `eu-central-1a`, the pod remained pending with the scheduler event:
```
 Warning  FailedScheduling  54s    default-scheduler  0/3 nodes are available: 1 node(s) had taint {temp: }, that the pod didn't tolerate, 2 node(s) had volume node affinity conflict.
````

**Comment by rohantmp** [comment]
One bit of context that came up: the user was using spot instances, it could be possible that no instances from the required zone were part of that cluster at the time.  I'll ask them to provide `kubectl get node --show-labels` as well as `kubectl get pv --show-labels` next time they reproduce.

**Comment by matskiv** [comment]
@rohantmp The affected cluster had 2 nodes in AZ 1a and 2 nodes in 1b. PV got provisioned in 1b. Both Nodes in zone 1b were reporting good status when the scheduler was trying to schedule the pod.
I'll send you the output of those^ two commands via PM.
