### ISSUE TITLE
Conditionally enable IngressClasses syncing separately from Ingresses

### ISSUE THREAD

**Issue by bagel-dawg** [loft-sh/vcluster#755]
### Is your feature request related to a problem?

In an environment that uses Ingress resources, you may want to enable ingress syncing. Doing this on v0.12.0 results in the vcluster pods producing the following logout put before retstarting:

```
E0922 15:04:36.385006       1 reflector.go:140] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:262: Failed to watch *v1.IngressClass: failed to list *v1.IngressClass: ingressclasses.networking.k8s.io is forbidden: User "system:serviceaccount:customer1:vc-vcluster" cannot list resource "ingressclasses" in API group "networking.k8s.io" at the cluster scope
```

This is because the serviceaccount doesn't have a ClusterRole allowing it to interact with IngressClasses, which is a cluster-scoped resource.

In our ideal solution, vcluster is entirely contained in it's namespace and doesn't need a clusterrole for IngressClasses that won't be used.

This idea was proposed but was then changed to it's current state in #676.

### Which solution do you suggest?

Ingress and IngressClasses should be conditionally enabled separately to maintain least-privileges.

### Which alternative solutions exist?

Creating and binding a clusterrole to the vcluster service account will workaround the issue, but it unnecessarily increases exposure for those who don't use IngressClasses.

### Additional context

vcluster still seems to be usable in this state, but the vcluster pods are regularly restarted.

**Comment by matskiv** [comment]
Sort of unrelated, but I'll ask anyway, just to make sure we don't have a bug here. How are you enabling Ingress sync? Are you doing it via the `--sync=ingresses` cli flag for the syncer container?
If you do it by setting this helm value - `.sync.ingresses.enabled = true`, then the ClusterRole should get created with the get/watch/list permissions for the ingressclasses.

**Comment by bagel-dawg** [comment]
I've used the helm chart to render my desired values, but I'm doing the
deployment with Kustomize. The vcluster pod does indeed have
`--sync=ingresses` on the CLI.

I didn't consider that may be I am hitting a bug as well as permission
issues. Ill try and confirm.

**Comment by bagel-dawg** [comment]
Yeah, If i set a ClusterRole and a ClusterRoleBinding for the vcluster pod,
it stops throwing that error.
