### ISSUE TITLE
v1.16.15-k3s1 will crash caused by the EndpointSlice object not found in v1.16.15

### ISSUE THREAD

**Issue by jemygraw** [loft-sh/vcluster#756]
### What happened?

vcluster: 0.10.1
k3s: v1.16.15-k3s1

When I deploy v1.16.15-k3s1 as the virtual cluster, I will always find the `syncer` container crashed caused by the following error:

```
E0923 01:55:29.950601 1 controller.go:210] controller pod controllerGroup controllerKind Pod: Could not wait for Cache to sync failed to wait for kubernetes_default_endpoint caches to sync: timed out waiting for cache to be synced

E0923 03:11:11.103153 1 logr.go:265] controller-runtime: source: if kind is a CRD, it should be installed before calling Start no matches for kind "EndpointSlice" in version "discovery.k8s.io/v1beta1" kind schema.GroupKind{Group:"discovery.k8s.io", Kind:"EndpointSlice"}
```

After I search the reason in the code, I found that the register logic will first check whether api version `discovery.k8s.io/v1` found, if not, it will fallback to `discovery.k8s.io/v1beta1` in https://github.com/loft-sh/vcluster/blob/main/pkg/controllers/k8sdefaultendpoint/register.go#L23 .

But the problem is that even the api version `discovery.k8s.io/v1beta1` not found in kubernetes 1.16.15, in which the actual api version is `discovery.k8s.io/v1alpha1` .

### What did you expect to happen?

Really hope the problem can be solved.

### How can we reproduce it (as minimally and precisely as possible)?

Just deploy the vcluster-0.10.1 to any host kubernetes.

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Host cluster Kubernetes distribution

<details>

```
Standard Kubernetes
```

</details>

### vlcuster version

<details>

```console
$ vcluster --version
# 0.10.1
```

Helm Chart 0.10.1

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
# k3s: v1.16.15-k3s1

```

</details>

### OS and Arch

<details>

```
OS:  Linux
Arch: Amd64
```
</details>

**Comment by matskiv** [comment]
@jemygraw Kubernetes 1.16 is a very old version, and Kubernetes maintenance support for this version ended more than 2 years ago. I don't think we will be fixing this, since it is not a problem in newer versions (1.18+ AFAIK).

**Comment by jemygraw** [comment]
> @jemygraw Kubernetes 1.16 is a very old version, and Kubernetes maintenance support for this version ended more than 2 years ago. I don't think we will be fixing this, since it is not a problem in newer versions (1.18+ AFAIK).

ok, thanks for you reply. 
after some research work, i found that 0.7.0 support kubernetes 1.16 and we can close this issue now.
