### ISSUE TITLE
How to manage many vcluster?

### ISSUE THREAD

**Issue by bitpeng** [loft-sh/vcluster#759]
Help. I create several vclusters based on host cluster（and more vclusters may be created in the future），How to manage those vclusters on a convenience way? Is it to support virtual cluster management through `KOK` and so on？Thanks

**Comment by matskiv** [comment]
Hello @bitpeng 
Some users manage vclusters via ArgoCD, and there are multiple blog posts about that on the internet AFAIK. Another option is to use vcluster CAPI provider - https://github.com/loft-sh/cluster-api-provider-vcluster but it is limited to one host cluster.
The option with the most features and best support is our commercial offering - Loft ( https://loft.sh/ ).

P.S: I am unfamiliar with the `KOK` project, so I can't comment on that.
