### ISSUE TITLE
Docs: create a page describing vcluster-generic-crd-sync-plugin

### ISSUE THREAD

**Issue by matskiv** [loft-sh/vcluster#763]
### Is your feature request related to a problem?

The vcluster-generic-crd-sync-plugin project needs some kind of documentation page to present it to users and explain configuration options. A page on the vcluster docs website seems fitting.

### Which solution do you suggest?

Add a new page in the Plugins section with a general description of the generic crd plugin and then the explanation of the configuration syntax.

**Comment by neogopher** [comment]
Hi @matskiv . Can you please assign this to me.

**Comment by matskiv** [comment]
Resolved by #782
