### ISSUE TITLE
vcluster crashes when `sync.ingresses` is enabled - failed to list IngressClass (is forbidden)

### ISSUE THREAD

**Issue by felipecrs** [loft-sh/vcluster#765]
### What happened?

The moment I enable ingresses sync, my connection with the vcluster becomes unstable. It stops working for a while, then it comes back.

### What did you expect to happen?

To work.

### How can we reproduce it (as minimally and precisely as possible)?

I don't know, maybe there is something unique in my host cluster which triggers this issue?

### Anything else we need to know?

```console
vcluster-0 syncer E0927 21:49:37.612467       1 reflector.go:140] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:262: Failed to watch *v1.IngressClass: failed to list *v1.IngressClass: ingressclasses.networking.k8s.io is forbidden: User "system:serviceaccount:felipe-vcluster:vc-vcluster" cannot list resource "ingressclasses" in API group "networking.k8s.io" at the cluster scope
```

I notice this error in the vcluster pod logs.

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:25:45Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.14", GitCommit:"0f77da5bd4809927e15d1658fb4aa8f13ad890a5", GitTreeState:"clean", BuildDate:"2022-06-15T14:11:36Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.25) and server (1.21) exceeds the supported minor version skew of +/-1

```

</details>

### Host cluster Kubernetes distribution

Vanilla

### vlcuster version

0.12.0

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

k3s

### OS and Arch

Ubuntu 18.04

**Comment by felipecrs** [comment]
```console
❯ kubectl get ingressclasses.networking.k8s.io
NAME    CONTROLLER             PARAMETERS   AGE
nginx   k8s.io/ingress-nginx   <none>       112d
```

On behalf of myself it works just fine.

**Comment by felipecrs** [comment]
Using a `cluster-admin` serviceAccout seems to fix the issue, but I wonder if there is a more elegant solution.

**Comment by matskiv** [comment]
The problem that causes this has been kindly pointed out in this comment - https://github.com/loft-sh/vcluster/pull/676#pullrequestreview-1123283087

**Comment by felipecrs** [comment]
I'm working on a PR for this.
