### ISSUE TITLE
Bundle charts with the CLI

### ISSUE THREAD

**Issue by felipecrs** [loft-sh/vcluster#770]
### Is your feature request related to a problem?

See next answer.

### Which solution do you suggest?

Since the size of all the charts is minimal, the CLI could come with them bundled, at least with the matching version, i.e. vcluster cli 0.12.0 comes with the version 0.12.0 of the charts.

This would avoid one connection to external servers during the deployment of vclusters, and therefore reduce the fragility of it (i.e. would work even if the charts server is offline).

**Comment by FabianKramm** [comment]
@felipecrs thanks for the issue! That sounds like a good idea and should also speed up the creation of a vcluster as the chart doesn't need to get pulled!
