### ISSUE TITLE
`vcluster delete --ignore-not-found` just like `kubectl`

### ISSUE THREAD

**Issue by felipecrs** [loft-sh/vcluster#771]
### Is your feature request related to a problem?

I'm using vcluster in CI, and I add `vcluster delete` as a cleanup step of my pipeline. Sometimes the pipeline fails before the vcluster gets created, and therefore `vcluster delete` fails with `couldn't find vcluster`.

### Which solution do you suggest?

A new flag like `vcluster delete --ignore-not-found`, similar to `kubectl delete --ignore-not-found`. It would prevent returning a non-zero status code in case the vcluster does not exist already. Also, it would still attempt to delete other resources if told to, like `--delete-namespace` and the PVC, but also would not fail if the PVC or Namespace is not found.

### Which alternative solutions exist?

A wrapper for `vcluster delete`:

```
#!/bin/bash

set -eux

code=0

# Ignore when vcluster isn't found
if ! output=$(vcluster delete vcluster --namespace my-vcluster 2>&1) &&
    [[ "${output}" != *"couldn't find vcluster"* ]]; then
    code=1
fi
echo "${output}"

kubectl delete namespace my-vcluster --ignore-not-found || code=1

exit "${code}"
```

### Additional context

*No response*

**Comment by FabianKramm** [comment]
@felipecrs thanks for creating this issue! Sounds like a good idea, I guess we can implement that!

**Comment by rahulii** [comment]
hey @FabianKramm @felipecrs I would like to work on the issue.
Also, do we want to keep the scope of `ignore-not-found` to just vcluster or pvc and namespace as well , as described in the description?

**Comment by felipecrs** [comment]
In my opinion I think it should, so that:

```console
vcluster delete my-cluster --namespace my-namespace --delete-namespace --ignore-not-found
```

Can be reliably used, and repeated, to ensure there are no leftovers from vcluster.

**Comment by matskiv** [comment]
@rahulii sorry for late reply, I will assign this issue to you, but let me know if you are not interested anymore.

As for the scope, the `vcluster delete --ignore-not-found` should not fail with "not found" error regardless of the resource that it tries to delete.

**Comment by rahulii** [comment]
@matskiv I am on it.

**Comment by rahulii** [comment]
hey @matskiv how do I compile a new vcluster cli with my code changes?

**Comment by matskiv** [comment]
@rahulii Ideally like this - `go build -mod vendor cmd/vclusterctl/main.go`
or you can run new code in one command, without creating a temporary binary, like so - `go run -mod vendor cmd/vclusterctl/main.go -- help`

**Comment by Kartik-Garg** [comment]
Hey @rahulii, is it okay if I get this issue assigned to myself?
I have already created a PR regarding this, hope that's okay with you :D

**Comment by FabianKramm** [comment]
This is open to being worked on, feel free to assign this to you

**Comment by Vishalk91-4** [comment]
@FabianKramm, could you please assign this issue to me

**Comment by rohantmp** [comment]
Hi, @Vishalk91-4 are you still interested in working on this?

**Comment by Vishalk91-4** [comment]
@rohantmp, yes I'm working will submit the PR in a few hours
