### ISSUE TITLE
oidc - one can use kubelogin w/ a cluster configured with oidc ... possible to do so with vcluster?

### ISSUE THREAD

**Issue by lknite** [loft-sh/vcluster#775]
### Is your feature request related to a problem?

Just to try it I configured argocd to deploy the kubernetes dashboard to all my clusters, a root cluster and two vclusters.  kubernetes-dashboard can accept a bearer token, so I configured oauth2-proxy along with kubernetes-dashboard.

The short version is that the kubernetes dashboard just passes along the bearer token.  This works with the root cluster, where oidc has been configured, but didn't work on the two virtual clusters.

Is it possible to configure oidc w/ the virtual clusters in the way one would to use kubelogin?

### Which solution do you suggest?

I'm not sure if configuring oidc fits in with the intended use of virtual clusters, but if the idea was someone could spin up a cluster and configure access to it in the usual way with groups passed along in the bearer token then it seems like it would.

I configure role bindings using the groups which match up with active directory groups in my environment, these get passed along in the bearer token and lets the cluster grant the expected access.

### Which alternative solutions exist?

Maybe there is already a way.  I listen with open ears.

If not, it's ok.  I don't require this ability since I use gitops ... an all powerful process which deploys to the clusters what it finds in git.  But, I would use it if it were available, when I'm using kubectl to troubleshoot things.

**Comment by matskiv** [comment]
This should definitely be possible. I had a very brief look at the kubelogin docs, and it seems like some flags on the k8s server side need to be set for the API server. If you use the default k3s distro then these helm values should do the trick:
```
vcluster:
  extraArgs:
    - "--kube-apiserver-arg=oidc-issuer-url=ISSUER_URL"
    - "--kube-apiserver-arg=oidc-client-id=YOUR_CLIENT_ID"
```

P.S.: As for the existing solutions, SSO and user management for vclusters is solved out of the box in our commercial product - [Loft](https://loft.sh/).

**Comment by lknite** [comment]
Thank you.  Still working on it but closing the issue here as this is the known way to do this.
