### ISSUE TITLE
Rename legacy-storageclasses sync option

### ISSUE THREAD

**Issue by FabianKramm** [loft-sh/vcluster#783]
Edited by @matskiv

**What:**
The `legacy-storageclasses` syncer should be renamed to `host-storageclasses`.
The same applies to the values in helm charts.
Backward compatibility for both things needs to be ensured.
Documentation should be updated.

**Why:**
@matskiv : IMHO original naming was not well chosen. The connotations of "legacy" make it sound like its usage would be discouraged, and that it might get deprecated and removed eventually, but that is not the case. The new name also better reflects how this syncer is working - syncing StorageClasses from the host cluster.

**Comment by matskiv** [comment]
Haha, I guess you've seen my comment about this... :joy: 
How about "host-storageclasses" ?

**Comment by FabianKramm** [comment]
Yes that sounds good!
