### ISSUE TITLE
CLI doesn't clean up etcd pvc volume when using k8s or eks distros

### ISSUE THREAD

**Issue by mtougeron** [loft-sh/vcluster#799]
### What happened?

When you provision a vcluster using the k8s provider and then delete it, it doesn't clean up the PVC created for the etcd statefulset.

### What did you expect to happen?

The PVC created for etcd to be deleted when the vcluster was deleted.

### How can we reproduce it (as minimally and precisely as possible)?

```sh
$> kubectl create ns vcluster
namespace/vcluster created
```

```sh
$> vcluster create --extra-values values.yaml --distro k8s --update-current=false --connect=false -n vcluster touge-test         
info   Create vcluster touge-test...
info   execute command: helm upgrade touge-test https://charts.loft.sh/charts/vcluster-k8s-0.12.2.tgz --kubeconfig /var/folders/rn/hrzkvjz5325dvtxz2ztzyf480000gp/T/1429668044 --namespace vcluster --install --repository-config='' --values /var/folders/rn/hrzkvjz5325dvtxz2ztzyf480000gp/T/2769579071 --values values.yaml
done √ Successfully created virtual cluster touge-test in namespace vcluster. 
- Use 'vcluster connect touge-test --namespace vcluster' to access the virtual cluster
- Use `vcluster connect touge-test --namespace vcluster -- kubectl get ns` to run a command directly within the vcluster
```

```sh
$> vcluster list

 NAME         NAMESPACE   STATUS    CONNECTED   CREATED                         AGE  
 touge-test   vcluster    Running               2022-10-25 16:12:01 -0400 EDT   39s  
```

```sh
$> kubectl get pods -n vcluster
NAME                                                  READY   STATUS    RESTARTS   AGE
coredns-749456dcbf-g6lb8-x-kube-system-x-touge-test   1/1     Running   0          14s
touge-test-86b687cd8b-d87zj                           1/1     Running   1          72s
touge-test-api-85f9564796-978l4                       1/1     Running   1          72s
touge-test-controller-659944d7f9-6gl25                1/1     Running   0          72s
touge-test-etcd-0                                     1/1     Running   0          72s
```

```sh
$> kubectl get pvc -n vcluster
NAME                     STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-touge-test-etcd-0   Bound    pvc-db7fa0a4-7bc2-4bec-b396-a3855578d156   5Gi        RWO            gp2            82s
```

```sh
$> vcluster delete touge-test
info   Delete vcluster touge-test...
done √ Successfully deleted virtual cluster touge-test in namespace vcluster
```

```sh
$> kubectl get pods -n vcluster
No resources found in vcluster namespace.
```

```sh
$> kubectl get pvc -n vcluster
NAME                     STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-touge-test-etcd-0   Bound    pvc-db7fa0a4-7bc2-4bec-b396-a3855578d156   5Gi        RWO            gp2            4m16s
```

```sh
$> kubectl get pvc -n vcluster data-touge-test-etcd-0 -o yaml
```

<details>

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
  creationTimestamp: "2022-10-25T20:12:01Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: vcluster-etcd
    release: touge-test
  name: data-touge-test-etcd-0
  namespace: vcluster
  resourceVersion: "118766844"
  uid: db7fa0a4-7bc2-4bec-b396-a3855578d156
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2
  volumeMode: Filesystem
  volumeName: pvc-db7fa0a4-7bc2-4bec-b396-a3855578d156
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  phase: Bound
```
</details>

```sh
$> kubectl get pv pvc-db7fa0a4-7bc2-4bec-b396-a3855578d156 -o yaml                    
```

<details>

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: ebs.csi.aws.com
  creationTimestamp: "2022-10-25T20:12:05Z"
  finalizers:
  - kubernetes.io/pv-protection
  - external-attacher/ebs-csi-aws-com
  name: pvc-db7fa0a4-7bc2-4bec-b396-a3855578d156
  resourceVersion: "118766880"
  uid: c69cb4a3-03fd-46d6-82c4-1145ef84bfca
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-touge-test-etcd-0
    namespace: vcluster
    resourceVersion: "118766747"
    uid: db7fa0a4-7bc2-4bec-b396-a3855578d156
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeAttributes:
      storage.kubernetes.io/csiProvisionerIdentity: 1666691842185-8081-ebs.csi.aws.com
    volumeHandle: vol-0a166372bef3fcadf
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.ebs.csi.aws.com/zone
          operator: In
          values:
          - us-west-2c
  persistentVolumeReclaimPolicy: Delete
  storageClassName: gp2
  volumeMode: Filesystem
status:
  phase: Bound
```
</details>

### Anything else we need to know?

EBS CSI driver versions:

```
    image: k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v1.6.2
    image: k8s.gcr.io/sig-storage/csi-provisioner:v2.2.2
    image: k8s.gcr.io/sig-storage/csi-attacher:v3.1.0
    image: k8s.gcr.io/sig-storage/csi-snapshotter:v6.0.1
    image: k8s.gcr.io/sig-storage/csi-resizer:v1.1.0
    image: k8s.gcr.io/sig-storage/livenessprobe:v2.4.0
    image: k8s.gcr.io/sig-storage/csi-attacher:v3.1.0
    image: k8s.gcr.io/sig-storage/csi-provisioner:v2.2.2
    image: k8s.gcr.io/sig-storage/csi-resizer:v1.1.0
    image: k8s.gcr.io/sig-storage/csi-snapshotter:v6.0.1
    image: k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v1.6.2
    image: k8s.gcr.io/sig-storage/livenessprobe:v2.4.0
```

### Host cluster Kubernetes version

<details>

```console
$> kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.10", GitCommit:"eae22ba6238096f5dec1ceb62766e97783f0ba2f", GitTreeState:"clean", BuildDate:"2022-05-24T12:56:35Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:49:09Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Host cluster Kubernetes distribution

<details>

```
CAPI KubeAdm EC2 VM installation
```

</details>

### vlcuster version

<details>

```console
$> vcluster --version
vcluster version 0.12.2
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
k8s
```

</details>

### OS and Arch

<details>

```
OS: MacOS
Arch: amd64
```
</details>

**Comment by matskiv** [comment]
@mtougeron Thank you for reporting this. Yeah, this is definitely a bug in the CLI. It seems fairly straight-forward, so I'll add "good-first-issue" label, but if it is rather high priority for you - let me know :slightly_smiling_face: 

Info for somebody who will be fixing this, which might be future me :joy: 
In the code [here](https://github.com/loft-sh/vcluster/blob/7d52b577bf0c54a46685c3ded43d862c229ca1a6/cmd/vclusterctl/cmd/delete.go#L109-L111) we are expecting only PVC name in the format that gets produced by the k3s and k0s chart by the volumeClaimTemplates in StatefulSet, but in k8s and eks charts the StatefulSet with the volumeClaimTemplates has a different name, which causes PVC to be named differently too. IMHO we shouldn't just blindly try to remove PVCs with either name, it would be good to check that it actually belongs to the exact vcluster instance that is being deleted, perhaps based on labels.

**Comment by mtougeron** [comment]
> but if it is rather high priority for you - let me know

Nope, no rush at all. Ran across it the other day and figured I'd report it in case you were not aware. I run vcluster mostly as k3s anyway.

**Comment by rahulii** [comment]
> @mtougeron Thank you for reporting this. Yeah, this is definitely a bug in the CLI. It seems fairly straight-forward, so I'll add "good-first-issue" label, but if it is rather high priority for you - let me know slightly_smiling_face
> 
> Info for somebody who will be fixing this, which might be future me joy In the code [here](https://github.com/loft-sh/vcluster/blob/7d52b577bf0c54a46685c3ded43d862c229ca1a6/cmd/vclusterctl/cmd/delete.go#L109-L111) we are expecting only PVC name in the format that gets produced by the k3s and k0s chart by the volumeClaimTemplates in StatefulSet, but in k8s and eks charts the StatefulSet with the volumeClaimTemplates has a different name, which causes PVC to be named differently too. IMHO we shouldn't just blindly try to remove PVCs with either name, it would be good to check that it actually belongs to the exact vcluster instance that is being deleted, perhaps based on labels.

@matskiv as far as I understood, we should try to list the PVC using label as a filter and try to delete it , correct?
listOptions would contain matchLabels:
app: vcluster-etcd
elease: args[0] // vcluster-name

**Comment by matskiv** [comment]
@rahulii Listing by label would work, but doing it based on the known name format would be okay too. I was mainly trying to say that when we are deleting the PVC we should detect which distro is being removed and only delete a PVC that belongs to that distro. So if somebody creates a vcluster named "test" with k3s distro, then deletes it but with `--keep-pvc` option, and then creates a vcluster with the same `test` name but with k8s distro - the deletion of this vcluster shouldn't remove the PVC of the previous one (the k3s one). 
This is an edge case, so we could create a separate issue for it, together with some other edge cases that arise from the lack of `--distro` flag in `vcluster delete` command, maybe we solve those by detecting the distro before proceeding with the deletion.
Let's ignore this here for now, and only fix the issue as it was reported. I should not inflate the scope. Sorry for the confusion.

**Comment by rahulii** [comment]
@matskiv then what is the solution you are proposing?
I think this is what we are expecting 
```
pvcName := fmt.Sprintf("data-%s-0", args[0])
``` 
if the vcluster name is `touge-test` , PVC name - data-touge-test-0

But as per the issue reported, the pvc name is: data-touge-test-etcd-0 for k8s distro

**Comment by matskiv** [comment]
@rahulii I am proposing to just try to delete both `"data-%s-0"` and `"data-%s-etcd-0"`.
And other edge cases can be solved separately later.

**Comment by matskiv** [comment]
@rahulii Do you still want to implement this issue or can we unassign you?
