### ISSUE TITLE
Feature gated changes to PVC and storageclass behaviour in v1.25

### ISSUE THREAD

**Issue by rohantmp** [loft-sh/vcluster#827]
### Is your feature request related to a problem?

PVC.Spec.StorageClassName might be required to be upsynced.

New functional annotation to investigate for `StorageClass`: [https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/3333-reconcile-default-storage-class](https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/3333-reconcile-default-storage-class).

The changes are feature-gated behind `RetroactiveDefaultStorageClass`

### Which solution do you suggest?

I started on changes, but don't have bandwidth to verify and implement status syncing: [https://github.com/rohantmp/vcluster/blob/4484fc5c6f7d89481c6fb631169eb653ac960ccb/pkg/controllers/resources/persistentvolumeclaims/translate.go#L135-L140](https://github.com/rohantmp/vcluster/blob/4484fc5c6f7d89481c6fb631169eb653ac960ccb/pkg/controllers/resources/persistentvolumeclaims/translate.go#L135-L140)

If anyone picks this up, that could be a good starting point.

I will get to this when other tasks allow.

### Which alternative solutions exist?

*No response*

### Additional context

This is documented behavior, controllers might come to rely on it.

**Comment by matskiv** [comment]
The `updated.Spec.StorageClassName = pObj.Spec.StorageClassName` update won't work if the virtual API server uses older k8s version or doesn't have the feature flag enabled.

I think we need to map out different scenarios that relate to the default storage class. We need to take into account that we have 3 options for StorageClass sync, the virtual API might not have the feature flag enabled while the host might (or vice versa), etc. And when syncing StorageClasses from the virtual to the host there might be no default in the virtual, but some default in the host. And other potential scenarios.
I think right now this is still too complex to consider it a good first issue, so I'll remove the label.
