### ISSUE TITLE
Multiple host namespaces support

### ISSUE THREAD

**Issue by dene14** [loft-sh/vcluster#828]
### Is your feature request related to a problem?

Not a problem, potentially improvement...

### Which solution do you suggest?

Provide mapping between host and vcluster namespaces, maybe with some sort of name mapping

e.g. `host/{vclusterName}-{namespaceName}` => `vcluster/{namespaceName}`
If I understand correctly, in this mode no extensive rewriting for all resources and fields in the spec will be required and in case of vcluster setups with a lot of resources it won't be single namespace that holds million of resources.

It's also easier to manage resources from operations stands point - you don't need to go into vcluster API, most of the things can be clearly observed from host cluster.

Or I'm missing the point?

Thank you!

### Which alternative solutions exist?

*No response*

### Additional context

*No response*

**Comment by matskiv** [comment]
I think this is not compatible with the current vcluster architecture and goals.
This would require a quite big change to the code, and it would increase code complexity or duplication. The cluster-scoped permissions would be required to manage resources in multiple namespaces, and in such case, each vcluster would hold much more data in memory; OR it would have to create watches and caches per namespace, which would result in more API connections to the host cluster API server. It would make other things more difficult too - NetworkPolicy for vcluster Isolation, ResourceQuotas.

> It's also easier to manage resources from operations stands point - you don't need to go into vcluster API, most of the things can be clearly observed from host cluster.
IMHO this conflicts with the idea behind vcluster - you should treat it as a completely separate cluster. There should be no need to manage any vcluster workloads via host cluster API, this is only needed for troubleshooting.
