### ISSUE TITLE
Delete kubeconfig secret when vcluster is deleted.

### ISSUE THREAD

**Issue by GrahamDumpleton** [loft-sh/vcluster#83]
When the vcluster control plain is deleted the secret used for the kubeconfig file is not deleted. This means that if you start a new vcluster immediately after using the same secret name it is updating the existing secret from the prior instance and not creating a new secret.

This is a problem because if the secret is being mounted into an application (deployed after the vcluster) then Kubernetes may not update quickly enough the values of the secret as seen by that deployment and so the old values of the secret are used and the application could fail.

For the case of where the `--target-namespace` is not set and the secret is in the same namespace, should perhaps look at setting the owner references of the secret to be the stateful set if `--owning-statefulset` is provided (much like other resources created from the vcluster) so the secret is also cleaned up.

For the case of where `--target-namespace` is set, would need to be documented that is up to the user to delete the secret, although in that case it is likely the whole separate target namespace would be getting deleted anyway.

**Comment by FabianKramm** [comment]
@GrahamDumpleton thanks a lot for creating this issue! Yes you are correct we should set the owner reference of the kubeconfig secret to the statefulset if `--target-namespace` is not provided.

**Comment by matskiv** [comment]
This was implemented in #85 but we forgot to close the issue, so closing it now :)
