### ISSUE TITLE
Set server URL in kubeconfig secret to hostname that would be used to access vcluster.

### ISSUE THREAD

**Issue by GrahamDumpleton** [loft-sh/vcluster#84]
At present the ``--tls-san`` option can be used to supply an alternate hostname to the generated certificate to match hostname that would be used when accessing the vcluster.

If this option is used then perhaps the kubeconfig secret if generated could also use that hostname rather than default of localhost. This would make the kubeconfig secret when mounted into a different deployment usable immediately without actually needing to copy it and run ``kubectl config set-cluster --server`` to fix up the server name.

Because though the default actually includes a port of 8443, which would not be what vcluster is accessed by when using the Kubernetes service inside the cluster, then piggy backing on ``--tls-san`` may not be appropriate . In this case then maybe a separate option should instead be added specifically to set what the server should be that is set in the kubeconfig secret when generated although this is duplicating the hostname in two options.

Either way, would be nice that an option existed to be able to set what the server URL is in the kubeconfig secret when generated so that it works as is, rather than needing to be copied and modified before it can be used.

**Comment by FabianKramm** [comment]
@GrahamDumpleton thanks for creating the issue! Yeah I agree, we should add a separate option that allows you to specify another server url for the kubeconfig. Not sure if we should automatically use the `--tls-san` provided host for the kubeconfig, as multiple values can be specified there and this is somewhat implicit behaviour that might be unexpected / breaking for some use cases currently.

**Comment by poblin-orange** [comment]
Tested successfully with vcluster 0.3.3

**Comment by GrahamDumpleton** [comment]
@FabianKramm The solution to this was to add the ``--out-kube-config-server`` option which does update the server URL in the kubeconfig to what is required, however, when accessed via that URL when exposed outside the cluster with a proper hostname, you can only use it by using ``--insecure-skip-tls-verify=true`` with ``kubectl``. Otherwise get an error like:

```
$ KUBECONFIG=/tmp/kubeconfig.yaml k get ns
Unable to connect to the server: x509: certificate is valid for kubernetes.default.svc.cluster.local, kubernetes.default.svc, kubernetes.default, kubernetes, localhost, not vcluster-1.green.advok8s.io
```

Would it be possible to extract the hostname from the URL (ie., stripping ``https://``) from the ``--out-kube-config-server`` option and add that hostname into the hosts which the self signed certificate is generated for?

Seems it is not enough to modify the kubeconfig to add against the server ``insecure-skip-tls-verify: true`` as then you get an error:

```
error: specifying a root certificates file with the insecure flag is not allowed
```

So looks like having the correct hostname in the self signed certificate might be the only way of avoid having to explicitly give ``--insecure-skip-tls-verify=true`` to ``kubectl``.

**Comment by GrahamDumpleton** [comment]
Haha, I didn't even read my own original report for this issue to realise I can use ``--tls-san`` option to change it. I'm an idiot. Had totally forgotten what that option did. Thanks. Will give that a try.

**Comment by GrahamDumpleton** [comment]
Yeah, that works a treat.

BTW, is the operator that creates virtual clusters which is part of https://github.com/loft-sh/loft functionality a separate thing. I can't seem to find it. I wrote my own for fun, but still curious if the code can be seen somewhere.

Anyway, this issue can probably be closed out.

**Comment by FabianKramm** [comment]
@GrahamDumpleton great! Regarding the operator code of loft, this code is currently proprietary and part of our commercial solution loft. However, we might open source it in the future.
