### ISSUE TITLE
Support new PDB fields [Alpha in v1.26]

### ISSUE THREAD

**Issue by matskiv** [loft-sh/vcluster#844]
### Is your feature request related to a problem?

[KEP 3017](https://github.com/kubernetes/enhancements/blob/master/keps/sig-apps/3017-pod-healthy-policy-for-pdb/README.md) introduces new fields to the PDB spec. We should ensure that vcluster handles these correctly and in a way that is compatible with older host versions.

### Which solution do you suggest?

One of the things that will need to be updated is [translateUpdate function](https://github.com/loft-sh/vcluster/blob/11ea0b858ec4bcd9738a0df205a9ce2f8c044b8b/pkg/controllers/resources/poddisruptionbudgets/translate.go#L17) of the PDB syncer.

### Which alternative solutions exist?

*No response*

### Additional context

Feature gate: `PDBUnhealthyPodEvictionPolicy` Default value: false

**Comment by kfox1111** [comment]
This issue will probably end up having similar issues to: https://github.com/loft-sh/vcluster/issues/894
