### ISSUE TITLE
vcluster 0.13.0 build failure

### ISSUE THREAD

**Issue by chenrui333** [loft-sh/vcluster#847]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>build failure</summary>

```
  ==> go build -mod vendor -trimpath -o=/opt/homebrew/Cellar/vcluster/0.13.0/bin/vcluster -ldflags=-s -w -X main.commitHash=d147bd9a0599161d720eaec595c5026f278060b7 -X main.buildDate=2022-11-15T17:50:21Z -X main.version=0.13.0 ./cmd/vclusterctl/main.go
  cmd/vclusterctl/cmd/create.go:44:12: pattern charts/*.tgz: no matching files found
```

</details>

full build log, [https://github.com/Homebrew/homebrew-core/actions/runs/3484654823/jobs/5829513561](https://github.com/Homebrew/homebrew-core/actions/runs/3484654823/jobs/5829513561)
relates to Homebrew/homebrew-core#115977

**Comment by rohantmp** [comment]
Hi, you now have to run `go generate ./...`before `go build` to bundle the charts

**Comment by chenrui333** [comment]
yeah, that is the issue, thanks for the pointer.
