### ISSUE TITLE
Syncing Ingress resource require extra permission

### ISSUE THREAD

**Issue by xinnjie** [loft-sh/vcluster#848]
### What happened?

Enable ingress sync require applying ClusterRole requiring cluster-admin permission.

➜  dev-thing git:(master) ✗ helm upgrade --install my-vcluster loft/vcluster -n credit --values vcluster.values.yaml
Error: UPGRADE FAILED: rendered manifests contain a resource that already exists. Unable to continue with update: could not get information about the resource ClusterRole "vc-my-vcluster-v-credit" in namespace "": [clusterroles.rbac.authorization.k8s.io](http://clusterroles.rbac.authorization.k8s.io) "vc-my-vcluster-v-credit" is forbidden: User "system:serviceaccount:credit:sa" cannot get resource "clusterroles" in API group "[rbac.authorization.k8s.io](http://rbac.authorization.k8s.io)" at the cluster scope

It seems that vcluster need IngressClass watch permission. Then I disable IngressClass sync explicitly.
rendered manifest is as below:

# Source: vcluster/templates/rbac/clusterrole.yaml

## kind: ClusterRole

apiVersion: [rbac.authorization.k8s.io/v1](http://rbac.authorization.k8s.io/v1)
metadata:
name: vc-my-vcluster-v-credit
labels:
app: vcluster
chart: "vcluster-0.13.0"
release: "my-vcluster"
heritage: "Helm"
rules:

# Source: vcluster/templates/rbac/clusterrolebinding.yaml

kind: ClusterRoleBinding
apiVersion: [rbac.authorization.k8s.io/v1](http://rbac.authorization.k8s.io/v1)
metadata:
name: vc-my-vcluster-v-credit
labels:
app: vcluster
chart: "vcluster-0.13.0"
release: "my-vcluster"
heritage: "Helm"
subjects:

* kind: ServiceAccount
  name: vc-my-vcluster
  namespace: credit
  roleRef:
  kind: ClusterRole
  name: vc-my-vcluster-v-credit
  apiGroup: [rbac.authorization.k8s.io](http://rbac.authorization.k8s.io)

---

permission not needed anymore, but still create empty ClusterRole .

### What did you expect to happen?

syncing Ingress resource require no admin permerssion.

### How can we reproduce it (as minimally and precisely as possible)?

`helm template vcluster loft/vcluster --set sync.ingressclasses.enabled=false --set sync.ingresses.enabled=true`

### Anything else we need to know?

*No response*

### Host cluster Kubernetes version

<details>

```
$ kubectl version
# paste output here
```

</details>

### Host cluster Kubernetes distribution

<details>

```
# Write here
```

</details>

### vlcuster version

<details>

```
$ vcluster --version
# paste output here
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
# Write here
```

</details>

### OS and Arch

<details>

```
OS: 
Arch:
```

</details>

**Comment by stefanpinson** [comment]
I am seeing a similar behavior.  I am using v0.13.0 and the k0s helm chart.  Enabling ingress sync enables ingressclass sync even when ingressclassses sync is disabled. This forces the syncer container into crash loop since I do not have permissions needed to sync the ingressclasses.
