### ISSUE TITLE
Safe to evict annotations for the autoscaler should be configurable or respect pod's annotation

### ISSUE THREAD

**Issue by steved** [loft-sh/vcluster#860]
### Is your feature request related to a problem?

vcluster is setting the `safe-to-evict` cluster-autoscaler option for all replicated workloads. When dynamically creating workloads, this can lead to unbalanced nodes as workloads are added/deleted and the default setting for cluster-autoscaler is to scale down nodes with [< 50% utilization](https://github.com/kubernetes/autoscaler/blob/e8d3e9b1d986d540a21913b756cb2b47ffddb918/cluster-autoscaler/main.go#LL106C15-L106C15). That can lead to interruptions in service as the workloads are repacked.

### Which solution do you suggest?

I think there are two options:

1. Allow the `safe-to-evict` annotation to be an optional configuration
2. Respect the virtual pod's own `safe-to-evict` annotation if set

### Which alternative solutions exist?

We've configured the autoscaler to only scale down nodes that are truly unutilized (< %5 usage ignoring daemonsets).

### Additional context

*No response*

**Comment by FabianKramm** [comment]
Hey @steved ! Thanks for creating this issue! Maybe I misunderstood your issue, but I just tested this, and for me all pods that were created from a deployment or without that have `cluster-autoscaler.kubernetes.io/safe-to-evict: "false"`, have the same annotation on the host cluster, would be nice if you could verify again if this is not already working

**Comment by steved** [comment]
Hey @FabianKramm thanks for the quick response (and sorry for my late one). Yes, you're totally correct, I had mixed up the deployment and pod annotations. Sorry for the noise!
