### ISSUE TITLE
Add nodeSelector and tolerations to the hostpath-mapper DaemonSet

### ISSUE THREAD

**Issue by matskiv** [loft-sh/vcluster#861]
### Is your feature request related to a problem?

This is very useful for the vclusters that utilize nodeSelector to assign all workloads and vcluster control plane to a set of nodes.

### Which solution do you suggest?

Add new values under the `.Values.hostpathMapper`

### Which alternative solutions exist?

Manually edit the DaemonSet separately from the vcluster installation.

### Additional context

*No response*

**Comment by dobecad** [comment]
Hello! I'd be willing to work on this feature if it's still desired
