### ISSUE TITLE
Not able to access vcluster pod due to Upgrade request required

### ISSUE THREAD

**Issue by vumdao** [loft-sh/vcluster#877]
### Is your feature request related to a problem?

Issue: Not able to access vcluster Pod

```
kubectl exec -it app-95c87457d-tv4mz --kubeconfig /Users/vudao/workspace/gitlab/eks-vcluster/kube-config/dev-kubeconfig.yaml -- bash
Defaulted container "app" out of: app, glowrootapp (init)
Error from server (BadRequest): Upgrade request required
```

```
➜  ~ vcluster --version
vcluster version 0.13.0
```

EKS v1.23

Kubectl

```
➜  ~ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:57:26Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.13-eks-fb459a0", GitCommit:"55bd5d5cb7d32bc35e4e050f536181196fb8c6f7", GitTreeState:"clean", BuildDate:"2022-10-24T20:35:40Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.25) and server (1.23) exceeds the supported minor version skew of +/-1
```

I connect vcluster using

```
vcluster connect dev -n dev --server=https://dev-eks.simflexcloud.com --service-account admin --cluster-role cluster-admin  --update-current=false --insecure
```

vcluster config

```
service:
  type: NodePort

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: deployment
              operator: In
              values:
                - dev-ops

tolerations:
  - key: 'dedicated'
    operator: 'Equal'
    value: 'dev-ops'
    effect: 'NoSchedule'

syncer:
  extraArgs:
    - --tls-san=dev-eks.simflexcloud.com
    - --sync=nodes
    - --sync-all-nodes


sync:
  persistentvolumes:
    enabled: true
  storageclasses:
    enabled: true
  nodes:
    enabled: true
    syncAllNodes: true
  serviceaccounts:
    enabled: true
```

### Which solution do you suggest?

N/A

### Which alternative solutions exist?

*No response*

### Additional context

*No response*

**Comment by FabianKramm** [comment]
@vumdao thanks for the PR! This usually happens if there is a problem with the ingress controller that exposes the vcluster that is not supporting upgrade requests. What ingress controller are you using, regular ALB? We recommend to use ingress nginx as it causes the least problems there.

**Comment by vumdao** [comment]
Hi @FabianKramm, I'm using ALB controller and wonder why vcluster only support ingress nginx controller? What's blocking the access to vcluster Pod if we use ALB controller?

**Comment by vumdao** [comment]
This means that vcluster does not support ALB controller? @FabianKramm

**Comment by rohantmp** [comment]
Whenever I've seen this error, it's been that the client or the client on a proxy in the middle not supporting [upgrade requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Upgrade#overview), so this seems like a limitation of the ALB ingress controller. 

So

**Comment by rohantmp** [comment]
Perhaps there is some way to configure the ALB controller to allow the upgrade header?

**Comment by rohantmp** [comment]
The kubectl client sends a request with the Upgrade header,[ if the apiserver is forwarded the request without the upgrade request, the handler will return that error.](https://github.com/kubernetes/kubernetes/blob/bc6afee04938d29dfede98610604b944f3123602/staging/src/k8s.io/apimachinery/pkg/util/proxy/upgradeaware.go#L214-L220).

Closing as this is an ALB controller issue, and not a vcluster one.
