### ISSUE TITLE
Add resource section for hostpath-mapper to values.yaml

### ISSUE THREAD

**Issue by cinimins** [loft-sh/vcluster#881]
### Is your feature request related to a problem?

I am required to specify resources (requests and limits) in my kubernetes cluster, which I think is not possible for the hostpath-mapper unless I download and edit the helm chart (templates/daemonset-hostpath-mapper.yaml).

### Which solution do you suggest?

Would it maybe make sense to include the resources into the values.yaml?

**Comment by matskiv** [comment]
@cinimins Hello, thanks for creating this issue. I agree with you, it makes sense to add a "hostpathMapper.resources" helm value for this. Would you be interested in contributing a pull request for this? :)

**Comment by cinimins** [comment]
Sure, I just made a PR :)
