### ISSUE TITLE
Service account with GCP workload Identity annotations in vcluster

### ISSUE THREAD

**Issue by shydefoo** [loft-sh/vcluster#884]
/kind question

Hi, has anyone managed to run workloads in vclusters that make use of GCP workload identity annotations as described in this [example](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) successfully? Or is this expected to not work? I've tried but got this error (it can't authenticate with gcloud apis)

```
root@workload-identity-deployment-7b5c5d9b98-rjfzl:/# gcloud secrets versions access 1 --secret=test-secret
ERROR: (gcloud.secrets.versions.access) There was a problem refreshing your current auth tokens: ('Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/sdfoo-test-gsa@gods-dev.iam.gserviceaccount.com/token from the Google Compute Engine metadata service. Status: 403 Response:\nb"Unable to generate access token; IAM returned 403 Forbidden: Permission \'iam.serviceAccounts.getAccessToken\' denied on resource (or it may not exist).\\nThis error could be caused by a missing IAM policy binding on the target IAM service account.\\nFor more information, refer to the Workload Identity documentation:\\n\\thttps://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#authenticating_to\\n\\n"', <google.auth.transport.requests._Response object at 0x7f6ccef24a90>)
```

However, using the Google SA key locally works, ie `gcloud auth print-access-token` works, which means the permissions are also set up correctly. The same setup also works on the host cluster directly.

I see that under [https://www.vcluster.com/docs/architecture/synced-resources](https://www.vcluster.com/docs/architecture/synced-resources) there's an option to sync the ServiceAccount resource from vcluster to host cluster, I have tried that but it's also not working.

**Comment by matskiv** [comment]
@shydefoo I only have practical experience with AWS IRSA, so I might be wrong on some details, but at high level I think it works the same. One option is the ServiceAccount resource sync, but you have to realize that when this happens the workload is actually using the synced SA, which has a different name\[1], and its namespace is equal to the host cluster namespace where you installed vcluster, and this needs to be taken into account when creating the IAM policy binding.

Another option might be to configure vcluster API server in a way that it will produce ServiceAccount tokens that will be trusted by the GCP, but this was pretty involved when I did this in AWS and I am not sure how difficult would this be in GCP. Basically, you would treat your vcluster as a self-managed k8s cluster in GCP.

\[1] The name of the synced resource is calculated with [the SafeConcatName() function](https://github.com/loft-sh/vcluster/blob/main/pkg/util/translate/translate.go#L53) - `SafeConcatName(name, "x", namespace, "x", Suffix)`, where `name` and `namespace` are from the SA in virtual cluster, and `Suffix` is the name of your vcluster.

**Comment by sharkymcdongles** [comment]
It works fine if you set the iambinding to your: vclusterns/vcluster-sa and then annotate it.

E.g. your namespace and vcluster are called clooster in namespace you would set:

` gcloud iam service-accounts add-iam-policy-binding gkesa@myproject.iam.gserviceaccount.com --role roles/iam.workloadIdentityUser --member "serviceAccount:myproject.svc.id.goog[clooster/vc-workload-clooster]"`

then

`kubectl annotate serviceaccount vc-workload-clooster --namespace clooster  iam.gke.io/gcp-service-account=gkesa@myproject.iam.gserviceaccount.com`

@shydefoo
