### ISSUE TITLE
Unsleep Clusters With Precedence

### ISSUE THREAD

**Issue by sharkymcdongles** [loft-sh/vcluster#895]
### Is your feature request related to a problem?

Some spaces/vclusters have complex deployments requiring a more sophisticated unsleep strategy than all at once. Workarounds and hacks can be used like k8s-wait-for with init containers, but supporting something from the sleep/unsleep method directly would be a much cleaner approach.

### Which solution do you suggest?

I would suggest allowing some sort of rules engine for unsleeping and sleeping vclusters/spaces. Something like [https://github.com/groundnuty/k8s-wait-for](https://github.com/groundnuty/k8s-wait-for) or this old project [https://github.com/stackanetes/kubernetes-entrypoint](https://github.com/stackanetes/kubernetes-entrypoint)

### Which alternative solutions exist?

[https://github.com/groundnuty/k8s-wait-for](https://github.com/groundnuty/k8s-wait-for)

[https://github.com/stackanetes/kubernetes-entrypoint](https://github.com/stackanetes/kubernetes-entrypoint)

### Additional context

*No response*

**Comment by FabianKramm** [comment]
@sharkymcdongles thanks for creating this issue! Why not use something like `vcluster connect && ./k8s-wait-for.sh` directly? It would be pretty difficult for us to support a method that would cover more complex scenarios, so I guess using kubectl or other tooling instead is a lot easier.

**Comment by sharkymcdongles** [comment]
@FabianKramm I have already implemented k8s-wait-for, so that we have everything booting in a particular order. We still encounter problems despite using k8s-wait-for because all of the pending pods with init containers overload the virtual  cluster masters(k3s) due to all the pending pods. This wouldn't need to be a super complex implementation, even piggybacking off this feature would be sufficient:

https://loft.sh/docs/3.0/virtual-clusters/sleep-mode#advanced-configuration

An annotation like this would be more than enough:

sleepmode.loft.sh/start-first: 'true'

I tried to see if I could find the code for this and would happily submit a PR, but I don't think this part of the code is opensourced.


In general, even simply allowing certain classes of resources to boot first like statefulsets would be more than sufficient for most use cases. Typically statefulsets are the primary bottleneck for such deployments as well as being the primary costcenters meaning sleeping them is most beneficial to end users.

So far, the problem we have with our testing is all pods try to boot at once and then go to the k8s-wait-for initcontainer because they wait for the statefulsets to start. 

But the statefulsets then take far longer to boot than normal because the kubeapi hangs a bit due to all the initcontainers. I am currently trying to beef up the virtual masters with more cpu/memory and HA + external etcd to see if this helps, but I think it would just be easier if statefulsets booted first out of sleep since the vcluster only has this issue during wakeup.

**Comment by FabianKramm** [comment]
Mhh this sounds more like a problem of the host cluster though, I see why you would want to delay certain pods from getting restarted, but I guess the cleanest solution would be to make sure the host cluster can actually schedule those pods correctly. We can consider implementing a feature there in future, but I would like to first think about how we could solve this the best way.

**Comment by matskiv** [comment]
My 2 cents - we should think twice before adding new features that have reasonable alternatives to achieve the same outcome. We already provide a lot of extra features on top of the core functionality(certified Kubernetes distribution). We need to prioritize continued support of the core functionality, functionality introduced in new Kubernetes versions, and all the existing "extra" features.
I hope that explains why we might sometimes be hesitant about implementing new feature requests. :)
