### ISSUE TITLE
Add high availability support for k3s

### ISSUE THREAD

**Issue by FabianKramm** [loft-sh/vcluster#9]
k3s supports HA and currently we only support that for the k8s distribution. Would be great if we can support it for k3s as well.

**Comment by rajiteh** [comment]
Hello, did anyone figure this out?

**Comment by FabianKramm** [comment]
@rajiteh we have an example now with high available k8s at https://www.vcluster.com/docs/operator/other-distributions#high-available-vanilla-k8s

**Comment by rajiteh** [comment]
Thanks @FabianKramm however, it is also possible to run k3s on HA configurations too itseems. Which would mean less moving pieces for cluster operators to keep an eye on. I could give a shot at adapting the helm chart to work with this approach, if interested?

https://rancher.com/docs/k3s/latest/en/installation/ha-embedded/

**Comment by FabianKramm** [comment]
@rajiteh you are right, k3s is supporting that as well, sure you can give that a try if you want!

**Comment by Blackmamba23** [comment]
Is there an update on this issue, would be nice to have HA for k3s 🥹

**Comment by matskiv** [comment]
@Blackmamba23 sorry for taking so long to reply. Right now this is not on our short-term roadmap. 
But as with other issues, we would be glad to receive a PR with community contribution for this.

**Comment by dakraus** [comment]
@matskiv I created a PR that intends to add high availability support for k3s with an external database. Since I'm no expert on k3s any feedback is more than welcome (especially if I missed something basic about the high availability with k3s / vcluster ...).
