### ISSUE TITLE
`kubernetes` service sync fail with IPv6 ClusterIP

### ISSUE THREAD

**Issue by clementd64** [loft-sh/vcluster#911]
### What happened?

Syncer expect IPv4 address on IPv6 only service

```
Reconciler error Service "kubernetes" is invalid: spec.clusterIPs[0]: Invalid value: "fd01::2d22": expected an IPv4 value as indicated by `ipFamilies[0]`
```

### What did you expect to happen?

`ipFamilies[0] = IPv6` for IPv6 address on Dual stack of IPv6 only cluster

### How can we reproduce it (as minimally and precisely as possible)?

Create vcluster on cluster with IPv6 service CIDR

### Anything else we need to know?

IPv6-only service fail on k3s because of k3s-io/k3s#6847
use k8s

### Host cluster Kubernetes version

<details>

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"archive", BuildDate:"2023-01-18T22:38:55Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1+k3s1", GitCommit:"f10af367c3c96863c081ada4018e94e085c9404d", GitTreeState:"clean", BuildDate:"2023-01-26T00:40:08Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/arm64"}
```

</details>

### Host cluster Kubernetes distribution

<details>

```
k3s
```

</details>

### vlcuster version

<details>

```
$ vcluster --version
vcluster version 0.13.0
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

k8s

</details>

### OS and Arch

<details>

```
OS: Ubuntu 22.04
Arch: arm64
```

</details>

**Comment by matskiv** [comment]
Hello,
I create a KinD server with IPv6 network ([config](https://gist.github.com/matskiv/94a124aa3d0ecd7644a7cb050f72ba0d#file-kind-config-ipv6-yaml)), but I am not able to reproduce this issue. All the services in vcluster and host are created with ipv6 clusterIP and ipFamily. No errors in the syncer logs either. Logs in [this gist](https://gist.github.com/matskiv/94a124aa3d0ecd7644a7cb050f72ba0d#file-services-log).
I tried vcluster v0.13.0 k3s and k8s, and also v0.14.0-beta.0 k3s.

**Comment by clementd64** [comment]
You are running IPv6-only cluster. My error come from Dual Stack cluster
After more test, this come from cluster with Dual Stack service range.

Dual stack cluster with single stack service work
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
networking:
  ipFamily: dual
  serviceSubnet: fd01::/108
```

But with dual stack serice range (`serviceSubnet: fd01::/108,10.43.0.0/16`), the sync fail
This may come from kubernetes allocating only one family, even if dual stack service is configured
```
$ kubectl get svc -A -o custom-columns=IP:.spec.clusterIPs,FAMILY:.spec.ipFamilies
IP             FAMILY
[fd01::1]      [IPv6]
[fd01::a]      [IPv6]
[fd01::127b]   [IPv6]
[None]         [IPv6]
[fd01::438e]   [IPv6]
```

**Comment by matskiv** [comment]
Yeah, I used IPv6-only cluster. I'll retest with the dual stack.

**Comment by matskiv** [comment]
I am not able to reproduce with dual-stack either. I will check the code to see if I can spot anything that could be causing this.

**Comment by clementd64** [comment]
api server seems to run with `service-cidr=10.43.0.0/16`
```
# --distro=k3s
$ kubectl -n vcluster-test get statefulsets.apps test -o jsonpath='{.spec.template.spec.containers[0].args}'
["-c","/bin/k3s server --write-kubeconfig=/data/k3s-config/kube-config.yaml --data-dir=/data --disable=traefik,servicelb,metrics-server,local-storage,coredns --disable-network-policy --disable-agent --disable-cloud-controller --flannel-backend=none --disable-scheduler --kube-controller-manager-arg=controllers=*,-nodeipam,-nodelifecycle,-persistentvolume-binder,-attachdetach,-persistentvolume-expander,-cloud-node-lifecycle,-ttl --kube-apiserver-arg=endpoint-reconciler-type=none --service-cidr=10.43.0.0/16 \u0026\u0026 true"]
# --distro=k8s
kubectl -n vcluster-test get deployments.apps test-api -o jsonpath='{.spec.template.spec.containers[0].command}'
["kube-apiserver","--advertise-address=0.0.0.0","--allow-privileged=true","--authorization-mode=RBAC","--client-ca-file=/run/config/pki/ca.crt","--enable-bootstrap-token-auth=true","--etcd-cafile=/run/config/pki/etcd-ca.crt","--etcd-certfile=/run/config/pki/apiserver-etcd-client.crt","--etcd-keyfile=/run/config/pki/apiserver-etcd-client.key","--etcd-servers=https://test-etcd:2379","--proxy-client-cert-file=/run/config/pki/front-proxy-client.crt","--proxy-client-key-file=/run/config/pki/front-proxy-client.key","--requestheader-allowed-names=front-proxy-client","--requestheader-client-ca-file=/run/config/pki/front-proxy-ca.crt","--requestheader-extra-headers-prefix=X-Remote-Extra-","--requestheader-group-headers=X-Remote-Group","--requestheader-username-headers=X-Remote-User","--secure-port=6443","--service-account-issuer=https://kubernetes.default.svc.cluster.local","--service-account-key-file=/run/config/pki/sa.pub","--service-account-signing-key-file=/run/config/pki/sa.key","--service-cluster-ip-range=10.43.0.0/16","--tls-cert-file=/run/config/pki/apiserver.crt","--tls-private-key-file=/run/config/pki/apiserver.key","--watch-cache=false","--endpoint-reconciler-type=none"]
```

To ensure the cluster run dual stack
```
$ kubectl cluster-info dump | grep "10.43.0.0/16"
"--service-cluster-ip-range=fd01::/108,10.43.0.0/16",
"--service-cluster-ip-range=fd01::/108,10.43.0.0/16",
```

After looking at the helm chart and at how service CIDR is find
https://github.com/loft-sh/vcluster/blob/main/pkg/util/servicecidr/servicecidr.go#L129

It seems to first try IPv4 and then fallback to IPv6.
Service range here is dual stack, so creating an IPv4 one work.
```
$ kubectl create service clusterip --clusterip=4.4.4.4 --tcp 80 test
error: failed to create ClusterIP service: Service "test" is invalid: spec.clusterIPs: Invalid value: []string{"4.4.4.4"}: failed to allocate IP 4.4.4.4: the provided IP (4.4.4.4) is not in the valid range. The range of valid IPs is 10.43.0.0/16
```
vcluster will get `10.43.0.0/16`.
But since IPv6 is defined first in `service-cluster-ip-range`, k8s only allocate IPv6 service by default

> The address family of a Service defaults to the address family of the first service cluster IP range (configured via the --service-cluster-ip-range flag to the kube-apiserver).
> https://kubernetes.io/docs/concepts/services-networking/dual-stack/#services

It should be better to somehow get the `service-cluster-ip-range`, or create a valid service to query the default `ipFamilies`

**Comment by matskiv** [comment]
Ah, I did make a mistake in cluster config. I can now reproduce the issue :partying_face: :smile: 
Thanks for your patience. I'll debug the problem and hopefully get back with a PR soon.

**Comment by matskiv** [comment]
Hello, sorry for the delay. I sent a PR which should fix this issue. I also built an image which you can test with this helm value:
```
syncer:
  image: quay.io/matskiv/vcluster:PR934
```
