### ISSUE TITLE
ZSH completion does not work

### ISSUE THREAD

**Issue by PaulusTM** [loft-sh/vcluster#921]
### What happened?

After installing vcluster with homebrew and adding `source <(vcluster completion zsh)` to my `~/.zshrc` file completion does not work.

When running `source <(vcluster completion zsh)` in my current shell it also doens't work.

When I run the command I do get output that I expect.

### What did you expect to happen?

After running `source <(vcluster completion zsh)` I expect the vcluster cli commands to get completion.

### How can we reproduce it (as minimally and precisely as possible)?

Run `source <(vcluster completion zsh)` in a ZSH shell and check for completion to work.

### Anything else we need to know?

*No response*

### Host cluster Kubernetes version

n/a

### Host cluster Kubernetes distribution

n/a

### vlcuster version

vcluster version 0.14.0

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

n/a

### OS and Arch

n/a

**Comment by neogopher** [comment]
@PaulusTM . Thanks for creating this issue. 
We will check this and update you soon.

Meanwhile, I tried this on my machine which is running Ubuntu, and the completions for bash work as expected, which says this may be something specific to zsh (and on MacOS). Will keep you posted.

**Comment by neogopher** [comment]
Hi @PaulusTM . 

You will need to enable shell completion by running echo "autoload -U compinit; compinit" >> ~/.zshrc. You will get the complete set of commands required to enable vcluster command autocompletion by running `vcluster completion zsh --help`. Please follow the same and you should have it working for you. :slightly_smiling_face:

**Comment by PaulusTM** [comment]
Thank you @neogopher This solves my issues. Completely missed the clear help instructions.
