### ISSUE TITLE
Network issues with cilium in vcluster

### ISSUE THREAD

**Issue by biqas** [loft-sh/vcluster#923]
### What happened?

Installing cilium in the host cluster and then spinning up a vcluster and then also installing cilium in the vcluster causes network issues. the host cluster control planes loose connectivity.
These leads based on the configuration (in my case via cluster api) restarts and are removed and new control planes are deployed and then again restarted and removed and redeployed and so on.
Some how installing cilium in a nested environemnt causes problems.

### What did you expect to happen?

Intalling in vcluster should not cause network issues on host cluster.

### How can we reproduce it (as minimally and precisely as possible)?

* Install cilium on host cluster
* Create vcluster
* Install cilium in any vcluster

### Anything else we need to know?

*No response*

### Host cluster Kubernetes version

<details>

```
$ kubectl version
# v1.25.3
```

</details>

### Host cluster Kubernetes distribution

<details>

```
# Write here
Ubuntu 22.04.1 LTS
```

</details>

### vlcuster version

<details>

```
$ vcluster --version
# v0.14.0-alpha.2
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
# Write here
```

</details>

### OS and Arch

<details>

```
OS: Linux
Arch: amd64
```

</details>

**Comment by neogopher** [comment]
Hi @biqas .
Would be nice to know how you are planning to use cilium for your use-case if you can share that. Also, just wanted to mention that vcluster itself relies on the host cluster CNI for all its networking needs.

**Comment by biqas** [comment]
If i want to test some network policies based on the CNI, I would like to test them in isolation, but if vcluster relies on that then I guess it would not be possible or is it just a restriction at the moment? If it is not possible to have independent CNI's then at least it should be prevented in the vcluster to install a CNI because it is bringing down the host cluster.

**Comment by biqas** [comment]
@neogopher I planned to use cilium as an ingress controller, to define network policies, service mesh functions and network analysis. It is amazing what cilium can do.
Or what kind of use-cases are you interested in, maybe then I can explain more in detail.

**Comment by neogopher** [comment]
@biqas . That's really nice. 
Yes you are right. Since, vcluster relies on host network, it is not possible to use vcluster to test out a different CNI and its features. Also, I am afraid, we don't have any plans to support this capability in the near future.

**Comment by biqas** [comment]
ok can it be prevented from installing any CNI's?

**Comment by rohantmp** [comment]
You can prevent it with [isolated mode](https://www.vcluster.com/docs/operator/security#isolated-mode). If you want to try multiple CNIs, you might want to try [Multus](https://github.com/k8snetworkplumbingwg/multus-cni). This lets you install multiple CNIs and have different pods use different CNIs  (you should do it on the host cluster, installing it on the vcluster probably won't go well).

vcluster uses the same node and kubelet as the host cluster with a logical separation, so anything that effects those from the vcluster will affect the host cluster, but those can be prevented with isolated mode.
