### ISSUE TITLE
Dedicated vcluster nodes

### ISSUE THREAD

**Issue by biqas** [loft-sh/vcluster#924]
### Is your feature request related to a problem?

It is not related directly to a problem but more to security concerns. In the current satte of vcluster the pods are scheduled to the host cluster and pod to pod communication ([pod to pod traffic](https://www.vcluster.com/docs/architecture/networking)) is physically possible, to prevent these two circumstances the proposed solution would be very usefull.

### Which solution do you suggest?

The proposed solution could look like how kubermatic is doing it [kubermatic architecture](https://docs.kubermatic.com/kubermatic/v2.21/architecture/).

Host the vcluster in form of:

1. control plane(s) in pods
2. worker node(s) on defined targets (dedicated nodes)

The 1 point capability already exists in vcluster.

The 2 point could be archived to deploy node(s) via cluster api (worker nodes only). Via cluster api because it is becoming more and more the standard and implementing all the providers would not be necessary. Deploying dedicated worker node(s) for the vcluster would eliminate the need to schedule pods on the host cluster. (It could be imagined having the option to run in mixed mode).

### Which alternative solutions exist?

I'm not sure if there is an alternative solution beside kubermatic itself, but kubermatic is much havier and complex then vcluster is.

### Additional context

*No response*

**Comment by neogopher** [comment]
Hi @biqas . Thanks for creating the issue.
I understand that workload isolation can already be achieved by running the vcluster in [isolated mode](https://www.vcluster.com/docs/operator/security#isolated-mode). This will deploy a network policy that will restrict access and connectivity between vcluster workloads and other pods in the host cluster.

If you wish to have the vcluster workloads to be scheduled on dedicated nodes, it can be achieved using the [--node-selector flag](https://www.vcluster.com/docs/architecture/nodes). 

You can further read about how vcluster provides Isolation and security [here](https://www.vcluster.com/docs/operator/security#isolated-mode).

Do let us know, in case this doesn't entirely cover what you are looking for, and we would be happy to help you out. :slightly_smiling_face:

**Comment by biqas** [comment]
Hi, I have read about this, this is of course good if you want to have one host cluster, but what I was proposing is to eliminate the need to synchronise down the pods to host cluster nodes. Instead synchronise it to dedicated nodes (which have no connectivity to host cluster), which are associated with vcluster master node(s).

**Comment by matskiv** [comment]
@biqas I don't think that would be in scope for this project. There are some open source projects that do this already, e.g. [Kamaji](https://kamaji.clastix.io/).
