### ISSUE TITLE
Implement metrics server in vcluster to not require a cluster role

### ISSUE THREAD

**Issue by sandangel** [loft-sh/vcluster#927]
### Is your feature request related to a problem?

Currently, user has to install metrics server by themselves to vcluster kube-system namespace. It's not working even with the hack mentioned in the doc because it would require users to create a cluster role.

### Which solution do you suggest?

We can try to implement a feature that would replace the metrics-server in vcluster and would not require ClusterRole.

### Which alternative solutions exist?

*No response*

### Additional context

I mentioned this issue on Slack and was suggested to open a feature request here

**Comment by matskiv** [comment]
I discussed this internally and we see at least one possible path how to implement this (technical detail below). We will put this on our backlog for now.
 
We could create the "v1beta1.metrics.k8s.io" APIService(apiregistration.k8s.io/v1) resource in the vcluster and set its `.spec.service` to point to the `default/kubernetes` Service - this would forward all requests for metrics to the vcluster server component. Then in the server code we implement the endpoint that will respond to the requests for metrics with the rewritten data from the host metrics server. The "rewriting" step will ensure that names of resources in the host cluster are translated back to their original state(how they are named in the virtual cluster).

**Comment by sandangel** [comment]
That is awesome 😀😀

**Comment by SmsS4** [comment]
It's not possible to do this by writing a plugin am I right?

**Comment by matskiv** [comment]
@SmsS4 That would be possible. btw, we are already implementing this and a PR with the initial version is up already.

**Comment by matskiv** [comment]
@evalsocket We will try to include this particular feature in the release next week.
As for the workaround, you can install metrics-server inside vcluster - https://www.vcluster.com/docs/operator/monitoring-logging#installing-metrics-server

**Comment by matskiv** [comment]
@evalsocket We can look into that if you create a new issue. But please beware that with the upcoming release, public holidays and KubeCon, it will take us a while to get to this.
