### ISSUE TITLE
may not expose port 10250 externally since it is used by kubelet - when installing vcluster 0.14.0 in eks v.120

### ISSUE THREAD

**Issue by magnusboman** [loft-sh/vcluster#930]
### What happened?

WHen I'm trying to install vcluster in EKS v1.12:

`vcluster create vhub --connect  --expose`

It errors out:

```
info   Creating namespace vcluster-vhub
info   Chart not embedded: "open charts/vcluster-0.14.0.tgz: file does not exist", pulling from helm repository.
info   Create vcluster vhub...
info   execute command: helm upgrade vhub https://charts.loft.sh/charts/vcluster-0.14.0.tgz --kubeconfig /tmp/4242247591 --namespace vcluster-vhub --install --repository-config='' --values /tmp/2302960037
fatal  error executing helm upgrade vhub https://charts.loft.sh/charts/vcluster-0.14.0.tgz --kubeconfig /tmp/4242247591 --namespace vcluster-vhub --install --repository-config='' --values /tmp/2302960037: Release "vhub" does not exist. Installing it now.
Error: Service "vhub" is invalid: spec.ports[1]: Invalid value: 10250: may not expose port 10250 externally since it is used by kubelet
```

### What did you expect to happen?

I expected the installation to succeed

### How can we reproduce it (as minimally and precisely as possible)?

Install EKS v1.20 (if possible)
Run `vcluster create vhub --connect  --expose`

### Anything else we need to know?

*No response*

### Host cluster Kubernetes version

<details>

```
$ kubectl version
clientVersion:
  buildDate: "2022-06-15T14:22:29Z"
  compiler: gc
  gitCommit: f66044f4361b9f1f96f0053dd46cb7dce5e990a8
  gitTreeState: clean
  gitVersion: v1.24.2
  goVersion: go1.18.3
  major: "1"
  minor: "24"
  platform: linux/amd64
kustomizeVersion: v4.5.4
WARNING: version difference between client (1.24) and server (1.20) exceeds the supported minor version skew of +/-1
serverVersion:
  buildDate: "2022-10-24T20:31:58Z"
  compiler: gc
  gitCommit: 165a4903196b688886b456054e6a5d72ba8cddf4
  gitTreeState: clean
  gitVersion: v1.20.15-eks-fb459a0
  goVersion: go1.15.15
  major: "1"
  minor: 20+
  platform: linux/amd64
```

</details>

### Host cluster Kubernetes distribution

<details>

```
EKS
```

</details>

### vlcuster version

<details>

```
$ vcluster --version
# paste output here
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
vcluster version 0.14.0
```

</details>

### OS and Arch

<details>

```
OS:  Linux
Arch: x86
```

</details>

**Comment by rohantmp** [comment]
Hi @magnusboman, is this something impacting you currently? K8s v1.20 is EOL and v1.22 is too. I try and reproduce and fix if it is important.

**Comment by magnusboman** [comment]
Hi @rohantmp
 @matskiv asked me to create a issue for this. I thought maybe there is more to this than just the versions I'm running. 
I have worked around it for now so maybe check with  @matskiv?

**Comment by rohantmp** [comment]
Thanks for creating the issue by the way @magnusboman :)

Could I also trouble you to comment the workaround?

**Comment by magnusboman** [comment]
I created an Ingress without SSL-Passthrough, as per this page:
https://www.vcluster.com/docs/operator/external-access#ingress

**Comment by sgreene570** [comment]
I am running into this issue when deploying vclusters on top of GKE 1.24.9.

Happy to provide any additional information to help debug @rohantmp .

**Comment by rohantmp** [comment]
@sgreene570 yes please, could you provide:
- k8s version (1.24.9)
- vcluster version
- Used values and arguments
- Method of deployment
- Any other relevant config 

Thanks :)

**Comment by sgreene570** [comment]
@rohantmp 

k8s cluster version: v1.24.9-gke.2000
vcluster version: 0.14.0
vcluster command: `vcluster create -f values.yaml --upgrade --expose`
values.yaml:

```yaml
sync:
  persistentvolumes:
    enabled: true
  persistentvolumeclaims:
    enabled: true
  storageclasses:
    enabled: true
  ingresses:
    enabled: false
rbac:
  clusterRole:
      create: true
```

I suspect this has something to do with `--expose`? Any suggestions for a workaround in the interim?

**Comment by rohantmp** [comment]
Investigating

**Comment by rohantmp** [comment]
Working on a fix!
