### ISSUE TITLE
Namespaces, pods and services not deleted in Multi-namespace mode

### ISSUE THREAD

**Issue by famarting** [loft-sh/vcluster#932]
### What happened?

I created a cluster with [Multi-namespace mode](https://www.vcluster.com/docs/architecture/synced-resources#multi-namespace-mode) enabled

```
helm upgrade --install my-vcluster vcluster --repo https://charts.loft.sh --namespace host-namespace-1 --create-namespace --set multiNamespaceMode.enabled=true
```

Deployed some apps to the vcluster, because the way multi-namespace mode is deployed a new namespace was created in the host k8s cluster i.e `vcluster-b5236ce5-8f4d2c90` and my app pods are deployed into that namespace.

Then I deleted the vcluster `vcluster delete my-vcluster` , the vcluster api server got deleted by the namespace `vcluster-b5236ce5-8f4d2c90` and the pods running on it are still there.

### What did you expect to happen?

The created namespaces to be deleted or at least instructions to cleanup the orphaned namespaces and pods....

### How can we reproduce it (as minimally and precisely as possible)?

```
helm upgrade --install my-vcluster vcluster --repo https://charts.loft.sh --namespace host-namespace-1 --create-namespace --set multiNamespaceMode.enabled=true
```

```
kubectl create namespace foo
```

```
vcluster delete my-vcluster
```

### Anything else we need to know?

*No response*

### Host cluster Kubernetes version

<details>

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:17:11Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.15-gke.1400", GitCommit:"db5715dcbf86b6d79ed6b017e8bb2f097efb7b0a", GitTreeState:"clean", BuildDate:"2022-12-28T09:37:50Z", GoVersion:"go1.17.13b7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Host cluster Kubernetes distribution

<details>

```
GKE
```

</details>

### vlcuster version

<details>

```
$ vcluster --version
vcluster version 0.13.0
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
default
```

</details>

### OS and Arch

<details>

```
OS: macOS
Arch: arm64
```

</details>

**Comment by matskiv** [comment]
@famarting Hi, could you please re-try with a newer version(v0.14.0+) of vcluster CLI? This should do the CLI upgrade - `vcluster upgrade` :)

**Comment by matskiv** [comment]
Closing based on the lack of response. This is like not an issue. Feel free to create a new issue if the problem persists in the latest version of the CLI.
