### ISSUE TITLE
Disable node/proxy functionality in Isolated mode and add a flag to optionally enable it

### ISSUE THREAD

**Issue by matskiv** [loft-sh/vcluster#937]
### Is your feature request related to a problem?

The `node/proxy` functionality in Kubernetes can potentially allow circumvention of the security measures introduced by the Isolated mode of vcluster. AFAIK it is mitigated when "fake nodes" are used, but not with the "real nodes" sync.

### Which solution do you suggest?

The `node/proxy` RBAC permission should not be added to the ClusterRole in the Helm template whenever isolated mode is enabled.
A new Helm value should be added to optionally allow original behavior even in the isolated mode.

### Which alternative solutions exist?

Manually adjusting the ClusterRole to remove the `node/proxy` RBAC permission.

### Additional context

This can be considered a breaking change and should not be included only in a new minor release + it should be highlighted in the release notes.

**Comment by sigmabaryon** [comment]
@matskiv I'd like to contribute to this issue, could you please assign it to me.
