### ISSUE TITLE
Add the possibility to assign coredns pods to specific nodes

### ISSUE THREAD

**Issue by marwenguesmii** [loft-sh/vcluster#939]
### Is your feature request related to a problem?

Yes. We can't specify the nodes for the coredns pods

### Which solution do you suggest?

Add the possibility to mutate the `nodeSelector` field of the coredns deployment via `values.yaml`

### Which alternative solutions exist?

* Mutate the cordns pods after creating
* Create the whole coredns manifests

### Additional context

*No response*

**Comment by matskiv** [comment]
Could you please provide more details about your use case, why do you need to set nodeSelector for the CoreDNS?
Personally, I'd like to avoid adding new helm values for less popular use cases, especially if there is a workaround, at least until we have some good setup for testing the charts and good coverage.

**Comment by Marwennnne** [comment]
@matskiv we are using SPOT instances for our host clusters. And we would like to have a node group with ON DEMAND instances to put critical pods in it. 
SPOT and coredns pods its not a good combo

**Comment by joaocc** [comment]
We also have a similar need for the exact same reason. Some core services should be assignable to on_demand nodes :)

**Comment by ThomasK33** [comment]
Hey, it looks like the issue was fixed in #1214.

Feel free to re-open if you need more than the above PR to satisfy your needs.
