### ISSUE TITLE
k3s send warnings about node info

### ISSUE THREAD

**Issue by sandangel** [loft-sh/vcluster#941]
### What happened?

k3s version: v1.26.0-k3s1

We got some warning logs in k3s container after started vcluster and put some pods to sync to the host cluster

```
ime="2023-02-27T08:48:21Z" level=warning msg="Unable to remove node password: secrets \"ip-10-20-181-255.ap-northeast-1.compute.internal.node-password.k3s\" not found"
W0227 08:48:21.286428       7 topologycache.go:232] Can't get CPU or zone information for ip-10-20-69-232.ap-northeast-1.compute.internal node
time="2023-02-27T08:48:22Z" level=warning msg="Unable to remove node password: secrets \"ip-10-20-116-214.ap-northeast-1.compute.internal.node-password.k3s\" not found"
W0227 08:48:22.322908       7 topologycache.go:232] Can't get CPU or zone information for ip-10-20-218-86.ap-northeast-1.compute.internal node
time="2023-02-27T08:48:22Z" level=warning msg="Unable to remove node password: secrets \"ip-10-20-248-158.ap-northeast-1.compute.internal.node-password.k3s\" not found"
W0227 08:48:22.442956       7 topologycache.go:232] Can't get CPU or zone information for ip-10-20-69-232.ap-northeast-1.compute.internal node
```

### What did you expect to happen?

No warning logs

### How can we reproduce it (as minimally and precisely as possible)?

Start vcluster k3s with fake-nodes = true and schedule some pods on vcluster

### Anything else we need to know?

*No response*

### Host cluster Kubernetes version

<details>

```
$ kubectl version
1.23
```

</details>

### Host cluster Kubernetes distribution

<details>

```
k8s 
```

</details>

### vlcuster version

<details>

```
$ vcluster --version
0.14.1
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
k3s
```

</details>

### OS and Arch

<details>

```
OS: linux
Arch: amd64
```

</details>

**Comment by ishankhare07** [comment]
Hi @sandangel , I tried reproducing your issue. As mentioned you started vcluster with `fake-nodes = true`, which is also the default value - https://github.com/loft-sh/vcluster/blob/main/charts/k3s/values.yaml#L53 – but couldn't see those log lines. I also noticed a few things:

* You are using v0.14.1 of vcluster, can you try upgrading to v0.14.2 and give the same a try?
* You seem to be getting this on AWS, can you check if this is not specific to your EKS Nodes? I tried with DO just to be sure.

I tried creating the vcluster with the command `vcluster create vcluster`, followed by creating some pods on vcluster `kubectl run nginx --image=nginx`. I don't seem to be able to reproduce this issue.
