### ISSUE TITLE
parse error at (vcluster/templates/_helpers.tpl:31): unclosed action

### ISSUE THREAD

**Issue by shenkonghui** [loft-sh/vcluster#972]
### What happened?

\~ vcluster create my-vcluster --expose
warn   failed to find IPv6 service CIDR: invalid IP family, got IPv4 when trying to determine IPv6 Service CIDR
info   Create vcluster my-vcluster...
info   execute command: helm upgrade my-vcluster /var/folders/bs/5jnk2s415154dq97tx48j99w0000gn/T/vcluster-0.14.2.tgz-4009064609 --kubeconfig /var/folders/bs/5jnk2s415154dq97tx48j99w0000gn/T/576394287 --namespace konghui --install --repository-config='' --values /var/folders/bs/5jnk2s415154dq97tx48j99w0000gn/T/674040821
fatal  error executing helm upgrade my-vcluster /var/folders/bs/5jnk2s415154dq97tx48j99w0000gn/T/vcluster-0.14.2.tgz-4009064609 --kubeconfig /var/folders/bs/5jnk2s415154dq97tx48j99w0000gn/T/576394287 --namespace konghui --install --repository-config='' --values /var/folders/bs/5jnk2s415154dq97tx48j99w0000gn/T/674040821: Release "my-vcluster" does not exist. Installing it now.
Error: parse error at (vcluster/templates/\_helpers.tpl:31): unclosed action

\~ helm version
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}

### What did you expect to happen?

create k3s cluster

### How can we reproduce it (as minimally and precisely as possible)?

vcluster create my-vcluster --expose

### Anything else we need to know?

*No response*

### Host cluster Kubernetes version

<details>

```
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:40:17Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.26) and server (1.17) exceeds the supported minor version skew of +/-1
```

</details>

### Host cluster Kubernetes distribution

<details>

```
```

</details>

### vlcuster version

<details>

```
$ vcluster --version
vcluster version 0.14.2
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
k3s
```

</details>

### OS and Arch

<details>

```
OS: cenot7
Arch: amd64
```

</details>

**Comment by neogopher** [comment]
Hi @shenkonghui :wave: . Thanks for creating the issue.
Is it possible for you to update the helm version on your machine to a version you are comfortable with. The issue doesn't occur in the newer versions of helm.

**Comment by shenkonghui** [comment]
```
