### ISSUE TITLE
Add support for InitContainers in the charts

### ISSUE THREAD

**Issue by MohamedZ3kri** [loft-sh/vcluster#979]
### Is your feature request related to a problem?

no

### Which solution do you suggest?

Update the chart's `values.yaml` file + `templates/statefulset.yaml` file to support templating initcontaienrs.

### Which alternative solutions exist?

*No response*

### Additional context

This can have multiple use cases, I need this to place some custom certificates (read from secrets) under `/data/server/tls` before the server's initial start.

**Comment by FabianKramm** [comment]
Hey @MohamedZ3kri ! You should be able to mount these via regular ConfigMaps / Secrets, which is usually a better approach than using init containers.

**Comment by MohamedZ3kri** [comment]
Unfortunately regular ConfigMaps / Secrets won't work, I'm trying to mount the certificates based on the solution described [here](https://github.com/k3s-io/k3s/issues/1868#issuecomment-639690634), If I mount the configmap directly under `/data/server/tls` I get a `read-only file system` error.
```
level=fatal msg="starting kubernetes: preparing server: open /data/server/tls/client-ca.nochain.crt: read-only file system"
```

**Comment by FabianKramm** [comment]
@MohamedZ3kri do you mount the complete folder? I guess you need to mount the individual files only as k3s is trying to write other things into the folder

**Comment by MohamedZ3kri** [comment]
yes mounting the 6 files separately solved the read-only file system error, thank you.
