### ISSUE TITLE
Add `loft.sh/paused-date` annotation to paused clusters

### ISSUE THREAD

**Issue by Piroddi** [loft-sh/vcluster#981]
### Is your feature request related to a problem?

Unable to determine when clusters were paused

### Which solution do you suggest?

Add the following annotation when pausing a cluster:

`loft.sh/paused-date: "2000-01-01T00:00:00Z"`

Then remove annotation when cluster is resumed.

The following is already happening for:

```
loft.sh/paused: "true"
loft.sh/paused-replicas: "1"
```

### Which alternative solutions exist?

*No response*

### Additional context

*No response*

**Comment by Piroddi** [comment]
Happy to submit a PR, if this feature is approved

**Comment by FabianKramm** [comment]
Hey @Piroddi ! Thanks for creating this issue, sure you can take a shot at this, thanks!
