### ISSUE TITLE
Automate the releases of loftsh/vcluster-docker-desktop

### ISSUE THREAD

**Issue by kkapelon** [loft-sh/vcluster#985]
### Is your feature request related to a problem?

I would like to have the latest version of vcluster CLI in a dockerhub image. This could be easily used in Docker based CI systems such as GitHub actions, Codefresh, [Drone.io](http://Drone.io) etc

* loftsh/vcluster seems to be only the server component
* loftsh/loft-ci includes loft and devspace but not the vcluster CLI
* vcluster-docker-desktop seems to be exactly what I want but it is not automated (last release was 8 months ago)

### Which solution do you suggest?

Either

1. include the CLI in the vcluster image OR
2. automate vcluster-docker-desktop releases OR
3. include the vcluster CLI in loft-ci OR
4. create a brand new dockerhub image called "vcluster-cli" (something similar) that is automatically updated when a new vcluster release comes out

### Which alternative solutions exist?

I will use vcluster-docker-desktop for now

### Additional context

*No response*

**Comment by rohantmp** [comment]
From the next release, with the push to ghcr.io/loft-sh, docker run ghcr.io/loft-sh/vcluster-cli  will be available.

So you can do `docker run ghcr.io/loft-sh/vcluster-cli  vcluster list`

We have been pushing loftsh/vcluster-cli for older versions, but looks like that's not public. 

The current docker run ghcr.io/loft-sh/vcluster-cli image is tagged [v0.15.0-alpha.2](https://github.com/loft-sh/vcluster/releases/tag/v0.15.0-alpha.2), but you can use it like `vcluster create --chart-version v0.14.2` to create stable releases of vcluster.

**Comment by rohantmp** [comment]
Closing as fixed, feel free to reopen if you feels this needs more discussion, thanks :)
